### ISSUE TITLE
appsscript.json missing?

### ISSUE THREAD

**Issue by yellowbarchetta** [derekantrican/GAS-ICS-Sync#103]
Not technically a bug, but I've noticed that when copying across the latest version of the scripts, the script "appsscript.json" does not copy across into my scripting library.  When I try to create such a script, google script insists on calling it "appsscript.json.gs".  This may or may not be an issue!

**Comment by derekantrican** [comment]
Interesting. You're talking about doing "File > Make a Copy" to make a copy of the script?

**Comment by derekantrican** [comment]
(For reference - `appsscript.json` is the manifest file and you can view the manifest file of any script project by going to "View > Show manifest file")

**Comment by yellowbarchetta** [comment]
Doh!!  Yes, that's what I needed to do.  On your version the file was explictly showing, but it was hidden in mine.  Thanks for that!

**Comment by derekantrican** [comment]
No prob! Yeah, it's a little weird that it acts like a "hidden file"
