### ISSUE TITLE
Trigger only working once

### ISSUE THREAD

**Issue by yellowbarchetta** [derekantrican/GAS-ICS-Sync#104]
I'd been using the previous version of the script successfully, but have now copied across the latest version.

On first run "install" runs fine, adds a trigger for "StartSync" and the calendar syncs properly.  "install" is then executed again successfull from the trigger in "StartSync" but then nothing further happens.

Attached screenshot shows the pattern - install run from editor, startsync run from trigger, install run from trigger then nothing.  In the screenshot I've tried this twice.

I believe I have allowed the script to use the new Chrome V8 scripting, but I've also posted an issue with the appsscript.json file not coming across.  This may or may not be related!

![image](https://user-images.githubusercontent.com/58736713/75264709-b725ef80-57e7-11ea-9899-9a2883257454.png)

**Comment by derekantrican** [comment]
The big question is: does `startSync` keep happening eventually?

This looks to me to be "as designed". In the script, the `Install` function runs which schedules a trigger for itself later and starts the `startSync` function after 1 second. When the `Install` function gets triggered again, it repeats that process.

If you end up seeing a list of triggers (like your screenshot) where there is no recent `startSync` function, please let us know

**Comment by yellowbarchetta** [comment]
On the previous version, I'd see the pattern of "install" "StartSync" running every 15 minutes as executions.  

As it is operating now, the sync will happen and my calendar will get updated when I run it from the editor, but it fails to do any sync'ing after that.  I'm diagnosing that as being because it is failing to trigger "startSync" to run ever 15 minutes.  I might be misunderstanding the script, and as the code for "install" hasn't changed between the version I'm running now and the previous iteration, I'm a little perplexed!!

**Comment by jonas0b1011001** [comment]
I just set up a fresh copy directly from Derek's Google Drive and it installs/runs just fine so the new runtime does not seem to have broken anything.

Hard to tell what's going wrong there for you..maybe try manually deleting all triggers associated with the script and just copy and install once again.

**Comment by yellowbarchetta** [comment]
After deleting the old versions and the version I'd copied, now I can't get a fresh copy as it says there's too many people accessing the Google Drive!  

I noticed in the triggers it was showing "trigger disabled for unknown reason" (or words to that effect). 

When I can get access to the code again I'll reinstall and report back.

**Comment by derekantrican** [comment]
@yellowbarchetta Here are the instructions to set up the script without accessing my Google Drive: https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually

**Comment by yellowbarchetta** [comment]
Copied across successfully.  Same issue.  Install runs, StartSync runs, Install runs again but then the triggers are disabled so no further running.

Both triggers are showing as "This trigger has been disabled for an unknown reason." which I'm presuming explains why it then fails to start "startSync" again.

I'm running with 15 minute intervals, same calendar as was working previously, email alerts in use.  I will try disabling the emails in case that is exceeding a quota of some sort perhaps?  But I'm not getting any failed executions.

**Comment by derekantrican** [comment]
You could remove the "try" and "catch sections in the `Install` function and see what errors happen. I think Google will send you a daily digest of errors (like an email in the morning with all the errors encountered the day before)

**Comment by yellowbarchetta** [comment]
I had the try / catch in the code in the previous working version.  I've experimented with removing the emailing and get the same outcome - at some point between the operation of the triggers, both get disabled for "unknown reason"s.

I'm going to reinstate the previous working version that I had and see if that presents any different outcomes.

**Comment by yellowbarchetta** [comment]
No matter how many times I try this with the latest code version, it still drops the triggers after one cycle with the "unknown reason".

I'm back on the old code and it's working fine.  Very odd!

Anything at all to do with the V8 engine etc?

**Comment by derekantrican** [comment]
That's definitely strange. I guess it's probably possible and, if so, probably something that Google will fix soon (hopefully).

Please do let us know if it comes back. In the meantime, I'm going to close this ticket and we'll reopen it if someone else comes across it and it needs future investigation

**Comment by yellowbarchetta** [comment]
After playing around a little more, including replicating the "install" process as a standalone set of functions to discount something in the main body of the script getting in the way, the workaround fix to this issue is in this issue (accepted by Google).  https://issuetracker.google.com/issues/150756612

There's something going on with creation of triggers from other triggered functions in the V8 engine, so (for me at least) the only answer was to set the runtime version to deprecated_es5 which solved the issue for me.  Though means I am behind the main development tree.

Surprised this seems to be only affecting me and not others?

**Comment by derekantrican** [comment]
Thanks for linking us that issue. If it is indeed a problem with the V8 engine, I do hope Google will see this and resolve it. I've starred the issue so I can track it

**Comment by yellowbarchetta** [comment]
Two final comments.  Firstly, I've now worked around it by modifyin the install code (similar to others where the code was crashing) by replacing the iterative install / startSync process to simply add a triggered startSync everyMinutes(howFrequent).  

Secondly, I extracted the install code and modified slightly to confirm that it was the V8 runtime that was causing the issues (scripting changes in the code itself I think mean you can't just change the manifest file from V8 to the deprecated es5 version on the current version of the code).  

My version just sets up a trigger for the startSync / Install options as the main code does, but the startSync does very little.  I removed the try/catch loop for simplicity.

That extracted code, which others might want to test to see if the V8 issue is also present when they run it, was:-
var ml_howFrequent = 3;

function ml_install(){
    //Delete any already existing triggers so we don't create excessive triggers
    deleteAllTriggers();
    
    if (ml_howFrequent < 1){
      throw "[ERROR] \"ml_howFrequent\" must be greater than 0.";
    }
    else{
      ScriptApp.newTrigger("ml_install").timeBased().after(ml_howFrequent * 60 * 1000).create();//Schedule next Execution
      ScriptApp.newTrigger("ml_startSync").timeBased().after(1000).create();//Start the sync routine
    }
}

function ml_startSync(){
  Logger.log("Output this");
}

function deleteAllTriggers(){
  var triggers = ScriptApp.getProjectTriggers();
  for (var i = 0; i < triggers.length; i++){
    if (triggers[i].getHandlerFunction() == "ml_startSync" || triggers[i].getHandlerFunction() == "ml_install"){
      ScriptApp.deleteTrigger(triggers[i]);
      Logger.log(triggers[i].getHandlerFunction(), " has been deleted");
    }
  }
}

**Comment by yellowbarchetta** [comment]
(apologies for the formatting!)

**Comment by geogolem** [comment]
@yellowbarchetta : your workaround is working great for me :) thanks
