### ISSUE TITLE
TypeError: calendarMap is not iterable (row 13, file 'Helpers')

### ISSUE THREAD

**Issue by United57** [derekantrican/GAS-ICS-Sync#106]
Hi, I installed the script via the manual.
Now I'm getting the error: TypeError: calendarMap is not iterable (rule 13, file 'Helpers'). And indeed, it doesn't work.
I haven't made any adjustments in 'Helpers'. The only file I've adjusted is the Code.gs (see below, have I done this correctly?).
What to do to fix it?
Hope you can help, because I really hope this will fix my syncing problem!

In the file Code.gs, I've made :

```
var sourceCalendars = ["https://outlook.office365.com/owa/calendar/.x.x.x.x./reachcalendar.ics", "Work agenda"] 
 ["https://calendar.google.com/calendar/embed?src=myusername%40gmail.com&ctz=Europe%2FAmsterdam", "my name"];

var howFrequent = 15;                  // What interval (minutes) to run this script on to check for new events
var onlyFutureEvents = false;         
```

**Comment by derekantrican** [comment]
Are you using the https://outlook.office365.com/owa/calendar/.x.x.x.x./reachcalendar.ics as your url or did you modify the url before you put it here?

**Comment by United57** [comment]
> Are you using the https://outlook.office365.com/owa/calendar/.x.x.x.x./reachcalendar.ics as your url or did you modify the url before you put it here?

Thanks for your quick reply!
I modified it: '.x.x.x.x.' as well as 'myusername'...

**Comment by jonas0b1011001** [comment]
you are missing the outer brackets.

**Comment by derekantrican** [comment]
Yup. Here you go @United57 

```
ar sourceCalendars = [["https://outlook.office365.com/owa/calendar/.x.x.x.x./reachcalendar.ics", "Work agenda"],
 ["https://calendar.google.com/calendar/embed?src=myusername%40gmail.com&ctz=Europe%2FAmsterdam", "my name"]];
```

**Comment by United57** [comment]
> Yup. Here you go @United57
> 
> ```
> ar sourceCalendars = [["https://outlook.office365.com/owa/calendar/.x.x.x.x./reachcalendar.ics", "Work agenda"],
>  ["https://calendar.google.com/calendar/embed?src=myusername%40gmail.com&ctz=Europe%2FAmsterdam", "my name"]];
> ```

Thanks! Now it works! Happy!

Any idea when the color tags from Outlook will be supported to sync? I would be very grateful to have this clear overview over the week.

**Comment by derekantrican** [comment]
@United57 Glad to hear it! I'm not sure yet. This is a hobby project for Jonas and I so we only work on this when we have free time. But you can follow any updates at #93
