### ISSUE TITLE
Keep Old Events in the Calendar

### ISSUE THREAD

**Issue by SusyV** [derekantrican/GAS-ICS-Sync#109]
First let me thank for such a great Script. It is already  making my life easier.

The only issue I have is the script deleting my past events (which were created by the script). 

**NOTE that PAST events are DELETED a DAY after it has passed** when is not longer in the feed

I have "onlyFutureEvents = true". I understand the problem is that I also have "removeEventsFromCalendar = true", because I do  want the script to delete future events that have been Cancelled or deleted, but wish that didn't also deleted all my past Events.

I also tried "onlyFutureEvents = false" and "removeEventsFromCalendar = true" with same results. It deletes past events!!. If I try "removeEventsFromCalendar = false" then past events stay but deleted events also stay.

How can I make that possible? How can I have the script remove Events that have been deleted or cancelled in the future while still keeping past event not longer included in the feed?

**Comment by jonas0b1011001** [comment]
Have you ever tried syncing with onlyFutureEvents=false?

The event status will always be synced regardless of the options you mentioned. Therefore cancelled events should also be cancelled in your target calendar.

**Comment by SusyV** [comment]
> Have you ever tried syncing with onlyFutureEvents=false?
 Yes, that is how it was a first until I realized it deleted all past events the following day.

**Comment by jonas0b1011001** [comment]
> NOTE that PAST events are DELETED a DAY after it has passed when is not longer in the feed

This is normal behaviour with  _removeEventsFromCalendar = true_.
The script will not delete **any** events if this is set to false, regardless of any other setting!
Please keep in mind that past events will not reappear if you switch to _removeEventsFromCalendar = false_ if the events are no longer present in the source calendar you are syncing (as we obviously can't sync additional events that are not in the source).

In addition to the above, setting _onlyFutureEvents = true_ will delete **all** past events even if they are still present in the source calendar.

> I do want the script to delete future events that have been Cancelled or deleted

1. Cancelled events (i.e. _"STATUS:CANCELLED"_ , according ical standard) should be synced just fine regardless of the settings above. I will have to recheck if Google is actually handling this case as it is intended from our side.
2. Deleted events are treated the same whether they are in the future or in the past. Therefore you would have to set _removeEventsFromCalendar = true_ to get rid of them.

So from how i understand it, you want to run the script with
_removeEventsFromCalendar = true_
_onlyFutureEvents = false_
and need an additional option to keep **all** past events even if they are no longer in the source calendar. Is that correct?

**Comment by SusyV** [comment]
"In addition to the above, setting onlyFutureEvents = true will delete all past events even if they are still present in the source calendar." **If set to true Past event are NOT deleted!**

"So from how i understand it, you want to run the script with
removeEventsFromCalendar = true 
onlyFutureEvents = false **I will need onlyFutureEvents = true So Past events stay in the calendar**
and need an additional option to keep all past events even if they are no longer in the source calendar. Is that correct?"   **and Yes I need to keep past events even if they are no longer in the source calendar**

**Comment by derekantrican** [comment]
>I will need onlyFutureEvents = true So Past events stay in the calendar

That doesn't make any sense. By definition, "onlyFutureEvents" means that there are no past events in the calendar.

You said "Past events are NOT deleted" but also "So Past events stay in the calendar" - do you want past events in your calendar or not?

**Comment by SusyV** [comment]
Yes I do want Past Events in the calendar!!
I'm using google calendar and if "onlyFutureEvents = true" then Past events created by the script are NOT removed when not longer in the feed. Those event Stay in the calendar as long as removeEventsFromCalendar = false. Which also keeps future Cancelled events in the Calendar.

**Comment by jonas0b1011001** [comment]
Please try the following adjustments to the scripts.

Add a new line in _Code.gs_ after line 26:
`var keepPastEvents = true;`

Change _Code.gs_ line 122 from
`if (onlyFutureEvents)`
to
`if (onlyFutureEvents || keepPastEvents)`

Replace _Helpers.gs_ lines 512-527 with
```
function processEventCleanup(){
  for (var i = 0; i < calendarEvents.length; i++){
    var currentID = calendarEventsIds[i];
    var feedIndex = icsEventsIds.indexOf(currentID);
    var calEventEnd;
    if (calendarEvents[i].start.date){
      calEventEnd = new ICAL.Time.fromString(calendarEvents[i].end.date);
    }
    else{
      calEventEnd = new ICAL.Time.fromString(calendarEvents[i].end.dateTime);
    }
  }
  
  if(feedIndex  == -1 && calendarEvents[i].recurringEventId == null && (keepPastEvents && calEventEnd.compare(startUpdateTime) >= 0)){
    Logger.log("Deleting old event " + currentID);
    try{
      Calendar.Events.remove(targetCalendarId, calendarEvents[i].id);
    }
    catch (err){
      Logger.log(err);
    }
  }
}
```

Run the script with
```
removeEventsFromCalendar = true
onlyFutureEvents = false
keepPastEvents = true
```
This should always keep past events in your taget calendar even if they disappear in your source.

Please let me know if this gets us any closer to what you are looking for.

**Comment by SusyV** [comment]
It removed past events as soon as I run the script with your changes :-(
And of course also future cancel events which is good.

**Comment by jonas0b1011001** [comment]
Is there any chance you can share the calendar you are syncing? You can use [https://derekantrican.github.io/icssanitizer.html](https://derekantrican.github.io/icssanitizer.html) to remove personal data.

**Comment by SusyV** [comment]
I realized I had not saved the Helpers.gs
I thought both pages were saved at the same time. Sorry
After I made sure to save both pages and run the script. Got the following error message:
TypeError: Cannot read property 'recurringEventId' of undefined (line 525, file "Helpers")Dismiss

**Comment by jonas0b1011001** [comment]
Sorry, try this.
```
function processEventCleanup(){
  for (var i = 0; i < calendarEvents.length; i++){
    var currentID = calendarEventsIds[i];
    var feedIndex = icsEventsIds.indexOf(currentID);
    var calEventEnd;
    if (calendarEvents[i].end.date){
      calEventEnd = new ICAL.Time.fromString(calendarEvents[i].end.date);
    }
    else{
      calEventEnd = new ICAL.Time.fromString(calendarEvents[i].end.dateTime);
    }
    
    if(feedIndex  == -1 && calendarEvents[i].recurringEventId == null && !(keepPastEvents && calEventEnd.compare(startUpdateTime) < 0)){
      Logger.log("Deleting old event " + currentID);
      try{
        Calendar.Events.remove(targetCalendarId, calendarEvents[i].id);
      }
      catch (err){
        Logger.log(err);
      }
    }
  }
}
```

**Comment by SusyV** [comment]
Seems to be working great. Past Events are staying
I have no way to tell yet if cancel future events are being removed. Will test tomorrow and let your know

**Comment by SusyV** [comment]
I'm happy to say it is working perfectly. 
Past Events are staying. Future events are being modified and cancelled events in the future are deleted.
Event's Cancelled on the same day sometimes don't get removed. But that is not a big deal at all. So Thank you  so much for an awesome Script.

**Comment by derekantrican** [comment]
Excellent! Glad Jonas' fix could work for you. I'll close this issue but let us know if you have other issues in the future
