### ISSUE TITLE
TypeError: Cannot read property 'dateTime' of undefined

### ISSUE THREAD

**Issue by jerobins** [derekantrican/GAS-ICS-Sync#115]
- Description of the problem

This just started happening with the script about a week ago. Until then, it was running normally. Now it is throwing an error for every iteration:

- Screenshots

4/10/20 3:53 AM | startSync | TypeError: Cannot read property "dateTime" from undefined. (line 488, file "Helpers") | time-based | 4/10/20 3:53 AM
-- | -- | -- | -- | --

- An input ics string that can reproduce the problem

I don't know which ICS entry is causing the error, but will share ICS link privately and reference this issue.

**Comment by jonas0b1011001** [comment]
Seems like you are running Version 5.1, i'd recommend updating to [5.2](https://github.com/derekantrican/GAS-ICS-Sync/releases).

Does the error also occur when you sync to an empty target calendar?

**Comment by jerobins** [comment]
I should add, this is with the most recent public version of the script in Google Drive. Was running an older version, updated to the most recent and tried syncing to a new Google Calendar. Got same error.

Private link to ICS file sent.

**Comment by jerobins** [comment]
Yes, it is version 5.2 on Chrome V8 and triggered same error with a new empty target.

**Comment by jonas0b1011001** [comment]
Hi, i just got hold of your ics file.
The issue is cause by several events having an empty uid-property.

You can make it work by changing Helpers.gs lines 493-502 (Version 5.2)
```
var eventInstanceToPatch = calendarEvents.filter(function(item){
    var origStart = item.originalStartTime.dateTime || item.originalStartTime.date;
    var instanceStart = new ICAL.Time.fromString(origStart);

    return (instanceStart.compare(recIDStart) == 0);
  });

  if (eventInstanceToPatch.length == 0){
    Logger.log("No Instance found, skipping!");
  }
```
to:
```
  var eventInstanceToPatch = calendarEvents.filter(function(item){
    if (item.originalStartTime){
      var origStart = item.originalStartTime.dateTime || item.originalStartTime.date;
      var instanceStart = new ICAL.Time.fromString(origStart);

      return (instanceStart.compare(recIDStart) == 0);
    }
    else{
     return false; 
    }
  });

  if (eventInstanceToPatch.length == 0){
    Logger.log("No Instance found, adding as new event!");
    try{
      Calendar.Events.insert(recEvent, targetCalendarId);
    }
    catch(error){
      Logger.log(error); 
    }
  }
```

Let me know if it works!

**Comment by derekantrican** [comment]
We also contacted Zoho to let them know of this issue. Here is their response that I just received:

![image](https://user-images.githubusercontent.com/1558019/79473334-d6f0bd00-7fb9-11ea-8cc5-79c4562048ee.png)

**Comment by derekantrican** [comment]
@jerobins did Jonas' solution work for you?

**Comment by jerobins** [comment]
Unfortunately, it did not. I appreciate y'all taking a look at this. Since this really is a ZoHo issue, I'm going to punt and wait for them to fix.  Thanks for a great script and for the help.
