### ISSUE TITLE
Period to sync seems to be limited to 26 weeks

### ISSUE THREAD

**Issue by lededude** [derekantrican/GAS-ICS-Sync#125]
The sync function seems to be limited to 26 weeks or so. 

We are at week 20 now (15th of May 2020), and it only syncs all events up to week 46 (15th of November 2020). If I add any items past that week, they will not sync, all events up to that date do sync. And it will not sync recurring events in November, even though it syncs them to October. A progress review meeting for example, scheduled for the first Monday of every month.

Not sure if this is intentional, but to be usable, this script could let us choose whether to sync all events, or if we wish to limit the time period.

Outlook calendar
![image](https://user-images.githubusercontent.com/47421609/82067312-389b6880-96d9-11ea-970c-3a4e1c446894.png)

Google calendar, missing recurring event on first Monday of the month in November and doesn't sync past week 46.
![image](https://user-images.githubusercontent.com/47421609/82067380-54067380-96d9-11ea-91c8-4b7d857fb706.png)

**Comment by derekantrican** [comment]
If you are comfortable with it, please share your ICS/ICAL url so we can take a look

**Comment by lededude** [comment]
> If you are comfortable with it, please share your ICS/ICAL url so we can take a look

This is my work calendar, so I'd get into trouble for that. I can try to repeat this with 2 other calendars. Please bear with me.

**Comment by jonas0b1011001** [comment]
Try opening the *.ics in a text editor and check if "Test week 47" is included.
The script will import all events present in the calendar no matter how far in the future it is, however there is a option in outlook to only publish events up to a certain date.

**Comment by derekantrican** [comment]
@lededude You can view and "sanitize" the ics here: https://derekantrican.github.io/icssanitizer.html
(I haven't made it work entirely for organizers & attendees yet but it should get pretty close)

**Comment by lededude** [comment]
I now managed to create an empty calendar, and inserted the same test events, the issue recurs. [Calendar link.](https://outlook.office365.com/owa/calendar/2f4a09b4ff524cf39d11b89200e6e4e8@msxi-euro.com/835eda32b5e442c7bf09afa6902008754062292664243481651/calendar.ics) The recurring event appears but the events do not appear past week 46.

**Comment by derekantrican** [comment]
This seems odd (The event seems to recur until its own date?):
```
BEGIN:VEVENT
DESCRIPTION:\n
RRULE:FREQ=MONTHLY;UNTIL=20201102T060000Z;INTERVAL=1;BYDAY=1MO
UID:040000008200E00074C5B7101A82E008000000008E72ABB2D52AD601000000000000000
 010000000C5A8FB576234584EBCB60C92E538175B
SUMMARY:Recurring 1st Monday
DTSTART;TZID=FLE Standard Time:20201102T080000
DTEND;TZID=FLE Standard Time:20201102T083000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20200515T164243Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

**Comment by lededude** [comment]
I now managed to create an empty calendar, and inserted the same test events, the issue re-occurs. The recurring events appear until week 46 but strangely none of the events appear past week 46.

I tracked it down to the events of week 47 not being included in the ICS file, so the issue is a Microsoft issue.... :( I have no idea where to check this

**Comment by jonas0b1011001** [comment]
How are you creating the link within outlook?

(While 26 weeks seems like a rather random period, 180 days (26 weeks - 2 days) is a quite common restriction for microsoft products)

**Comment by lededude** [comment]
> How are you creating the link within outlook?
> 
> (While 26 weeks seems like a rather random period, 180 days (26 weeks - 2 days) is a quite common restriction for microsoft products)

This is Office365 Exchange server, corporate, it has all of these options in the select menu, no problem getting these files for sharing or publishing a calendar etc.

This is not available in the Outlook Live, I checked.
![image](https://user-images.githubusercontent.com/47421609/82076959-435cfa00-96e7-11ea-9b67-8baf528ba5d4.png)

**Comment by derekantrican** [comment]
I believe this is an Outlook/Microsoft thing, unfortunately (I just checked and I'm seeing a similar limit on my personal `Outlook -> GAS-ICS-Sync -> Google Calendar` results). I'll do some digging and see if I can find some hard confirmation of this limit

**Comment by lededude** [comment]
I was really hoping this was a setting somewhere...... but, all in all, this script is very good. Thank you for the effort.

I wonder what kind of method does iPhone use to sync the events, because I see all events ... there must be some kind of magic involved between those frenemies.

**Comment by jonas0b1011001** [comment]
Are you using the exact same link on iPhone as with the script?

**Comment by lededude** [comment]
> Are you using the exact same link on iPhone as with the script?

No, on iPhone I logged in with credentials and selected to sync the calendar. Maybe this way removes the restrictions.

**Comment by derekantrican** [comment]
Is this Google Calendar on iPhone? Or some built-in Apple/iPhone calendar?

**Comment by derekantrican** [comment]
Oh, then maybe iPhone calendar directly interacts with the O365 API or something

**Comment by lededude** [comment]
This is built in... I think this would not work other way. 

Microsoft and Google are not exactly friends, so they do everything they can to avoid this kind of cooperation. Dang.

**Comment by derekantrican** [comment]
I'm doing some tests on my side to hopefully gather enough information to report it to Microsoft and see what the official answer is. I'm seeing the limit at 184/185 days out

**Comment by lededude** [comment]
> I'm doing some tests on my side to hopefully gather enough information to report it to Microsoft and see what the official answer is. I'm seeing the limit at 184/185 days out

Looking forward to it!

**Comment by derekantrican** [comment]
Since this has been identified as not an issue with our code, I'm going to close it. But I'll update it if I find out any new information

**Comment by derekantrican** [comment]
Just got internal confirmation that the range when publishing an ICS is from 3 months ago up to 6 months in the future. I'll let you know if anything changes

**Comment by derekantrican** [comment]
More info (though it may not apply to you @lededude - depending on your permissions)

In addition, if you are an admin of your office 365, you can use PowerShell to change the date range value to at most one year.

Here are the steps to do this.
1. Connect to Exchange Online with PowerShell
2. Run the command below.
    `Set-MailboxCalendarfolder -Identity EMAIL_ADDRESS:/Calendar -PublishEnabled $true -PublishDateRangeFrom sixMonths -PublishDateRange to OneYear`
   `Set-MailboxCalendarFolder -Identity EMAIL_ADDRESS:\Calendar\subfolder –PublishEnabled $true -PublishDateRangeFrom SixMonths -PublishDateRangeTo OneYear`

However, the date range value can only be change to these values: OneDay, ThreeDays, OneWeek, OneMonth, ThreeMonth, OneYear. IF you need to change it to other values, it is not feasible.

**Comment by lededude** [comment]
@derekantrican Thank you for this!!! It worked. 

I used This:

First I got the default settings which I saved:
`Get-MailboxCalendarFolder -Identity my_email:\Calendar`

Then I set as follows:
`Set-MailboxCalendarfolder -Identity my_email:\Calendar -PublishEnabled $true -PublishDateRangeFrom OneYear -PublishDateRangeTo OneYear`

Now it syncs 1 year to both directions.

You are a life saver :)

**Comment by derekantrican** [comment]
Glad it could help! If you would like to donate you can go to PayPal.me/derekantrican . I split all donations on this program with the other developer, Jonas (so I'll send him half)

**Comment by lededude** [comment]
> Glad it could help! If you would like to donate you can go to https://www.paypal.me/derekantrican . I split all donations on this program with the other developer, Jonas (so I'll send him half)

SENT :)

**Comment by lededude** [comment]
> How are you creating the link within outlook?
> 

@jonas0b1011001 

There is an undocumented way to create this link for non-enterprise accounts, like hotmail.com, live.com and outlook.com etc.

I just discovered it. I'd rather not share it publicly, since Microsoft will close it immediately if they see this.

**Comment by workjoeea** [comment]
@lededude I'm curious to know about the "undocumented way" you allude to above.  I don't see a way to message one another, though.  Please advise, thanks.
