### ISSUE TITLE
Detect events that have been modified manually

### ISSUE THREAD

**Issue by ande2413** [derekantrican/GAS-ICS-Sync#126]
I would like to see a feature where the script detects if an event has been modified manually and allow those events to be excluded from any overrides during a re-sync.  Thanks!

**Comment by derekantrican** [comment]
Thanks for the feature request. There is the `event.updated` (https://developers.google.com/calendar/v3/reference/events#updated) property. We could compare that to the last time the script ran. This could still be hard, though. What if the event gets deleted from the source? Or moved to a different date? Should all of these "changes" be ignored if you have edited it manually?

**Comment by ande2413** [comment]
Good questions.  In my case, they could be ignored all together.  Our teacher schedules don’t shift all that frequently.  And now that we are distance learning, a calendar event with modified zoom links and invites could create frustration if it kept being over-ridden.  But of course, this is just one case. Perhaps the ability to toggle that functionality on or off could be helpful.

**Comment by jonas0b1011001** [comment]
I have to revise my [comment](https://github.com/derekantrican/GAS-ICS-Sync/issues/21#issuecomment-629375290):
A manually edited event will be overridden **only** if the event in the feed changed.
That's how it currently is without changing anything, which basically only leaves the Questions Derek asked.

I'm not sure what the best solution is, but **in general** i'd assume people want the changes from the feed to be synced. Maybe having an option to _override/skip/keep both_ would cover all use cases?

**Comment by ande2413** [comment]
Thanks! That’s good to know.  In that case, the re-syncing should not create issues for me as events on the source feed rarely change.  I run a few tests to confirm.

**Comment by ande2413** [comment]
@jonas0b1011001 I manually modified an event yesterday on my Google calendar.  The source feed didn't change, but I noticed that that modification is now gone so it appears that the script is overriding all events even if the source feed doesn't change.  Happy to test any override setting you develop.

**Comment by jonas0b1011001** [comment]
Interesting, is it possible for you to share the ical-source of the event that resynced?

- open the *.ics file in a texteditor
- search for the event title
- post everything between BEGIN:VEVENT and END:VEVENT (you can remove any sensitive data of course)

I'm hoping to get a first solution by the weekend.

**Comment by ande2413** [comment]
@jonas0b1011001 Thanks.  Here's what I have from the ical source.  I simply updated my Google Calendar event description to read "This is a test".  That text disappeared from the event.

BEGIN:VEVENT
UID:27974cbc-a23b-491b-bf94-6c19334dfe1b
DTSTART;TZID=America/New_York:20200602T091500
DTEND;TZID=America/New_York:20200602T101000
DTSTAMP:20200518T164356
SUMMARY:9 French A - 1 (Epsilon)
STATUS:CONFIRMED
CLASS:PUBLIC
PRIORITY:3
CATEGORIES:podium,events
END:VEVENT

**Comment by jonas0b1011001** [comment]
Can you test if [this](https://script.google.com/d/1yKBpHJ9jKWyi4oe8yqXuhF3xafHgexrJLUQES5K1pxIk7cjQ6Tvrufwg/edit?usp=sharing) version keeps manually edited events (sync to a fresh calendar)?

**Comment by ande2413** [comment]
So I tested it it with some interesting results. When I ran this on the
same calendar, the events wouldn't show despite deleting all of the events
in range and deleting permissions for my previous web app. When I looked at
the logs, it definitely listed all of the right events.  I did change the
settings to only future events.  I don't see any error messages anywhere
and the execution indicates it was successful

[image: Screen Shot 2020-05-20 at 9.58.02 PM.png]

When I ran it on a fresh calendar, the events showed.  I manually edited
the event on June 4th and we'll watch what happens to that one.

[image: Screen Shot 2020-05-20 at 10.18.30 PM.png]

**Comment by ande2413** [comment]
This morning when I checked, the changes I made to the June 4th event were gone.  If it will help you debug here is the [Apps Script file](https://script.google.com/a/gtrainerdemo.richardaanderson.org/d/1GHcV03C1RI9I2X5YFlwhxJ5RwAJNrqaTCnuB9IM2MAg3eY2CBwDy5_BA/edit?usp=drive_web) for the web app I'm using with your newly modified code.

And here is the webcal:// feed i've been working with.

webcal://wis.myschoolapp.com/podium/feed/iCal.aspx?z=%2fy4GT9X12bRcEnSaFL7eU8RdnWAWsmTME6FK5nr%2fc1v5Zs5820Z4A87nwQOjITY4TIKNFXqSr4cz2Gi9DpX%2bRg%3d%3d

**Comment by jonas0b1011001** [comment]
Thanks for sharing the ics.
Comparing the current ics with the event definition you shared earlier it seems like the service you are using is for some reason changing the events' uids from time to time.

```
BEGIN:VEVENT
UID:cc281f2a-06af-40e5-83f5-d4605b7d96de
DTSTART;TZID=America/New_York:20200602T091500
DTEND;TZID=America/New_York:20200602T101000
DTSTAMP:20200521T081530
SUMMARY:9 French A - 1 (Epsilon)
STATUS:CONFIRMED
CLASS:PUBLIC
PRIORITY:3
CATEGORIES:podium,events
END:VEVENT
```

This basically makes it impossible for us the match events we synced earlier to the ones we are processing from the feed.

What you are experiencing when the modifications are overridden is that the script thinks all existing events in your calendar have been deleted from the feed (and therefore also delete them in your calendar) and add all events from the feed as 'new' ones to the calendar. This also explains why my [comment](https://github.com/derekantrican/GAS-ICS-Sync/issues/126#issuecomment-629619008) earlier was not true for you.

You can confirm all of that by setting up the script to run with
_var removeEventsFromCalendar = false;_
which should lead to events duplicating whenever the uids get changed by your service.

**Comment by ande2413** [comment]
That's exactly right.  I just looked at the June 4th event from a previously exported ics and the UID is different.  I think in my case I will need to simply sync one time and make that known to teachers that it's a one time sync.  I have another idea about limiting synced events within a specific range, but i'll elaborate on that in a new request if I see that it hasn't been asked about already.

BEGIN:VEVENT
**UID:181ec646-8f55-486b-b51a-e63789c7c91e**
DTSTART;TZID=America/New_York:20200604T103000
DTEND;TZID=America/New_York:20200604T113000
DTSTAMP:20200521T102056
SUMMARY:9 French A - 1 (Epsilon)
STATUS:CONFIRMED
CLASS:PUBLIC
PRIORITY:3
CATEGORIES:podium,events
END:VEVENT

BEGIN:VEVENT
**UID:0263f02b-5df1-4060-89b7-2c0623ce1921**
DTSTART;TZID=America/New_York:20200604T103000
DTEND;TZID=America/New_York:20200604T113000
DTSTAMP:20200518T164356
SUMMARY:9 French A - 1 (Epsilon)
STATUS:CONFIRMED
CLASS:PUBLIC
PRIORITY:3
CATEGORIES:podium,events
END:VEVENT

**Comment by derekantrican** [comment]
@ande2413 were you able to meet your needs here with the other issue you opened, #129?

**Comment by ande2413** [comment]
Yes.  Thank you!
