### ISSUE TITLE
Modified Recurrence of All-Day Meetings Fails With "Error: invalid date-time value"

### ISSUE THREAD

**Issue by k3vmcd** [derekantrican/GAS-ICS-Sync#127]
- Description of the problem
Steps to Reproduce:

1. Create All-Day recurring event
![image](https://user-images.githubusercontent.com/5653317/82474507-617c7e80-9a88-11ea-86c5-da043192b01d.png)
2. Modify recurrence of one meeting instance (i.e., "break" recurrence pattern)
![image](https://user-images.githubusercontent.com/5653317/82475022-157e0980-9a89-11ea-89bb-2fe13d5c121d.png)
3. Run GAS-ICS-Sync function
4. Fail with "Error: invalid date-time value" with stacktrace:
```
Error: invalid date-time value: "<MODIFIED_DATE_VALUE_OF_BROKEN_RECURRENCE_MEETING>"
    at ICAL.Time.fromDateTimeString(ical.js:5837:13)
    at processEvent(Helpers:170:17)
    at [unknown function](Code:175:9)
    at startSync(Code:174:15)
```
<br /><br />

- An input ics string that can reproduce the problem
```
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20200520T165046Z
DTEND;VALUE=DATE:20200522
DTSTAMP:20200520T165219Z
DTSTART;VALUE=DATE:20200521
LAST-MODIFIED:20200520T165200Z
PRIORITY:5
RRULE:FREQ=DAILY;COUNT=45;INTERVAL=2
SEQUENCE:0
SUMMARY;LANGUAGE=en-us:Test Event
TRANSP:TRANSPARENT
UID:64416C02-38FD-4605-A8CD-DB4028A4771A
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20200520T165200Z
DTEND;VALUE=DATE:20200523
DTSTAMP:20200520T165219Z
DTSTART;VALUE=DATE:20200522
LAST-MODIFIED:20200520T165200Z
PRIORITY:5
RECURRENCE-ID;VALUE=DATE:20200523
SEQUENCE:0
TRANSP:TRANSPARENT
UID:64416C02-38FD-4605-A8CD-DB4028A4771A
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-IMPORTANCE:1
END:VEVENT
```

**Comment by jonas0b1011001** [comment]
Hi,

thanks for the report, there should be an easy fix:

1. Open the script in your Google Drive
2. Open Helpers.gs
3. Press ctrl + F, search for "_fromDateTimeString_" and replace all with "_fromString_"

**Comment by k3vmcd** [comment]
Confirmed this change works. Thanks!

All other functionality appears to function as normal with this modification. Why not make this the default?

**Comment by jonas0b1011001** [comment]
Because I was not aware of the bug until now :)
Will be in the next version!

**Comment by k3vmcd** [comment]
Ah, perfect. I appreciate the help!
