### ISSUE TITLE
Limit Date Range of one-time Synced Events.

### ISSUE THREAD

**Issue by ande2413** [derekantrican/GAS-ICS-Sync#129]
When performing a one-time sync I'd like to limit the date range if possible.  For example, if I know the last day of Semester 1, I'd like the script to only add events from Semester 1.  Then, as Semester 2 approaches and any scheduling changes are worked, I would like a subsequent execution to add only Semester 2 events.  Not interested in automatic re-syncing in this case, but rather just limiting the range for one-time syncs.

**Comment by jonas0b1011001** [comment]
I will provide you the changes necessary to accomplish this in your own version of the script:

**Code.gs**
Add these Settings somewhere in between the existing settings at the top
```
var limitSyncRange = false;            // If you turn this to "true", only events taking place between syncStartDate and syncEndDate will be synced
var syncStartDate = "YYYY-MM-DD";
var syncEndDate = "YYYY-MM-DD";
```

add above _function startSync()_
```
var syncLimitStart;
var syncLimitEnd;
```
Add at the beginning of _function startSync()_
```
  if (limitSyncRange){
    try{
      syncLimitStart = new ICAL.Time.fromDateString(syncStartDate);
      syncLimitEnd = new ICAL.Time.fromDateString(syncEndDate);
    }
    catch(e){
      limitSyncRange = false; //disable if provided dates are invalid
    }
  }
```
**Helpers.gs**
In _function parseResponses(responses)_ add the following right above _if (onlyFutureEvents){_
```
  if (limitSyncRange){
    try{
      syncLimitStart = new ICAL.Time.fromDateString(syncStartDate);
      syncLimitEnd = new ICAL.Time.fromDateString(syncEndDate);
    }
    catch(e){
      limitSyncRange = false; //disable if provided dates are invalid
    }
  }
```

**Comment by ande2413** [comment]
Thanks! That works perfectly!
