### ISSUE TITLE
Ability to pass optional overrides for each calendar

### ISSUE THREAD

**Issue by marcingminski** [derekantrican/GAS-ICS-Sync#130]
Some ical feeds do not contain organizer or calendar names. For example, the WordPress plugin [wp-events-plugin.com](wp-events-plugin.com) either does not provide the organiser or has the ability to disable it and thus not showing in the ical feed. This, of course, makes the `addOrganizerToTitle` and `addCalToTitle` redundant potentially leaving events with vague descriptions or even with the same titles.

Proposal to add the ability to pass Organiser or/and Calendar Name overrides to the calendars array `var sourceCalendars = [];` for example:

```
var sourceCalendars = [
   "ical.url", "Google Calendar Name", "Organizer", "Calendar Name"
];
```

Since these would be optional, there should be no impact on existing users or those who do not require this feature.

I have attempted this but unsuccessful. I tried to pass these parameters down the line but It was getting messed up in `condenseCalendarMap`. Suppose instead of changing the whole logic, the functions responsible for adding Organizer and Calendar Names could do a lookup in the original array and search by URL. URLs should be unique in the array:

```
if (addOrganizerToTitle){
   //do lookup in var sourceCalendars = []; 
   //assume override takes precedence over the "event.hasProperty('organizer')"

   if (override found) {
     //then apply override
   } else {
    //get from event.hasProperty('organizer')
   }
}
```

Thanks

**Comment by jonas0b1011001** [comment]
If you want to do the changes yourself i have a [custom version](https://script.google.com/d/1y_Rd2bBMilykEoPvp3nM8mSSuueQO9MQbunAKpDZl4jNEUr_1H_7hRC7/edit?usp=sharing) of the script with 2 additional parameters in the sourceCalendars array just like you suggested.
You can basically adopt these changes and add the additional properties to each event in _function parseResponses(responses)_. From that point onward there are no additional changes needed.

If you are not successful i might manage to create a custom version for you by tomorrow, not sure if this is an addition that will make it to the main branch though.

**Comment by marcingminski** [comment]
ah right, I see where I went wrong! Magic! Thank you kindly! Appreciate the quick response!

**Comment by marcingminski** [comment]
Your example works well for me. I am happy for you to close this ticket if you feel this isn't going to make it into the master branch. Thank you, once again for your help.
