### ISSUE TITLE
"GoogleJsonResponseException: API call to calendar.events.insert failed with error: You need to have writer access to this calendar."

### ISSUE THREAD

**Issue by alexandramclarty** [derekantrican/GAS-ICS-Sync#131]
Here are my settings:

var sourceCalendars = [                                          
  ["http://msb1.wpengine.com/events/?ical=1&tribe_display=custom&start_date=2020&end_date=2023.ics", "Mangala Shri Bhuti"],
  
];

var howFrequent = 1;                
var onlyFutureEvents = false;         
var addEventsToCalendar = true;     
var modifyExistingEvents = true;     
var removeEventsFromCalendar = true; 
var addAlerts = false;                  
var addOrganizerToTitle = false;       
var descriptionAsTitles = false;       
var addCalToTitle = false;           
var addAttendees = false;             
var defaultAllDayReminder = -1;    
var addTasks = false;

var emailWhenAdded = true;           
var emailWhenModified = true;       
var email = "alex@justpeachy.io";                     

When I check the logs, I see "	Error, Retrying...GoogleJsonResponseException: API call to calendar.events.insert failed with error: You need to have writer access to this calendar."

Any ideas? Thanks for making this script!

**Comment by alexandramclarty** [comment]
Sorry, to be specific, that error is from the Stackdriver Logs. View > Logs returns:

 [20-05-28 07:46:02:685 PDT] Missing ; after for-loop initializer.
    at [unknown function](Code:127)

**Comment by jonas0b1011001** [comment]
```
var sourceCalendars = [
["http://msb1.wpengine.com/events/?ical=1&tribe_display=custom&start_date=2020&end_date=2023.ics", "Mangala Shri Bhuti"],

];
```
Remove the "," after the inner Brackets.

```Error, Retrying...GoogleJsonResponseException: API call to calendar.events.insert failed with error: You need to have writer access to this calendar.```
Is the "Mangala Shri Bhuti" Calendar a calendar you subscribed to? Seems like you do not have write permission to it.

**Comment by alexandramclarty** [comment]
> Remove the "," after the inner Brackets.

Done, thanks!

> Is the "Mangala Shri Bhuti" Calendar a calendar you subscribed to? Seems like you do not have write permission to it.

I used "Add Calendar > From URL" to add it to my Other Calendars list in Calendar . I can't add new events to it directly from Google Calendar, since it just pulls events from the ics feed. I thought the purpose of this script was to force Google Calendar to check subscribed calendars for updates more frequently. Is that not the case?

**Comment by alexandramclarty** [comment]
That worked like a charm. Thank you so much!
