### ISSUE TITLE
Suspected TimeZone/DST bug with certain events

### ISSUE THREAD

**Issue by LJUK2020** [derekantrican/GAS-ICS-Sync#136]
I add events to my O365 Outlook calendar directly - those events sync to Google fine. 

I have a 3rd party system (AutoTask) that also syncs with my O365 calendar. Events from AutoTask appear corretly in my Outlook calendar. However, these events display a hour early in my Google calendar.

I'm in the UK, and we're currently in daylight saving time, aka British Summer Time, which is GMT/UCT + 0100. So I'm guessing there's something different with the events from Autotask, where Outlook is able to display the times correctly, but either the script or Google is missing something and displaying the event as the unadjusted GMT time.

For example, I create an event in Autotask for 10am (0900 GMT+0100). This event syncs to Outlook and displays at 10am - correct. I look at the event in Google calendar, and it's showing up at 9am. 

To clarifty, the events created directly in the Outlook calendar display at the correct time in the Google calendar.

If you need anymore info to diagnose this please let me know, as this suspected bug will cause me a massive headache and render the script unusable which would be such a shame, as otherwise it seems to be working perfectly.

**Comment by LJUK2020** [comment]
Just thought of downloading the ics file and trying to identify what's different and found this:

The events that show an hour early in Google have the following DTSTART and DTEND's:

DTSTART;TZID=UnnamedCustomTimeZone:20200527T120000
DTEND;TZID=UnnamedCustomTimeZone:20200527T123000

They show 'UnnamedCustomerTimeZone' - Is there something we can tweak in the script to define this as being UCT/GMT time, so that Google then shows it correctly based on the time zone set in the Google calendar (+0100)?

Thanks

**Comment by LJUK2020** [comment]
OK I managed to work things out and fix this myself. So....

In: tzid.gs
Under: tzidreplace = {
I added: "UnnamedCustomTimeZone": "Etc/GMT", 

I ran the script = no change. I guessed this maybe because the events had already been imported to Google and hadn't been altered. 

So I changed the ics URL to something invalid so that the script wouldn't find any events (note that I suspect [removeEventsFromCalendar = true;] is needed for this to work, so that all existing events are removed when nothing is found at the invalid ics URL). This cleared out all events. 

I then corrected the ics URL and ran the script again, and hey presto, all events now displaying in the Google calendar at the correct time.

Happy :) Hope this helps anyone else having similar issue.

**Comment by derekantrican** [comment]
Glad you got it figured out! Yes, I hope it can help someone else too!

**Comment by jonas0b1011001** [comment]
You can also change [this](https://github.com/derekantrican/GAS-ICS-Sync/blob/115531fd1faab4b61b1dbab960e1d6367b21f285/Helpers.gs#L259) line to make it default to the timezone you need whenever it is encountering an unknown timezone id.

**Comment by LJUK2020** [comment]
Thanks Jonas, I think that's a better option. Updated, tested and working a treat. Thanks!
