### ISSUE TITLE
Rescheduled events are not being updates

### ISSUE THREAD

**Issue by Freedom9339** [derekantrican/GAS-ICS-Sync#139]
If there is an event that has been rescheduled to another day, the event is not updated.

I've ran a test by rescheduling an event and creating a new event. After I run the sync function, the new event appears, but the rescheduled event does not get updated and still shows on the old date.

**Comment by derekantrican** [comment]
Can you share your ICS url/file? (if you are worried about privacy of your calendar, you can use the ICS Sanitizer that I wrote)

**Comment by Freedom9339** [comment]
This is the ics link I used.
webcal://outlook.live.com/owa/calendar/010b96a9-a122-466d-a23a-04cc2472dbb8/26fa16d9-f1fe-4d7d-b439-f5b79327f130/cid-00052366C3925291/calendar.ics

**Comment by jonas0b1011001** [comment]
I don't see why it should not update.

Is 'Test1' the one you rescheduled? What is the old and the new date of it?

**Comment by Freedom9339** [comment]
I had it on Friday, then rescheduled it to Saturday. I just rescheduled it again for Sunday, if you want to test the script.

**Comment by jonas0b1011001** [comment]
Updated fine from Saturday to Sunday, maybe you set `var modifyExistingEvents = false`?

**Comment by Freedom9339** [comment]
Hmm, no, these are the set variables I used:

var howFrequent = 15;                  // What interval (minutes) to run this script on to check for new events
var onlyFutureEvents = false;          // If you turn this to "true", past events will not be synced (this will also removed past events from the target calendar if removeEventsFromCalendar is true)
var addEventsToCalendar = true;        // If you turn this to "false", you can check the log (View > Logs) to make sure your events are being read correctly before turning this on
var modifyExistingEvents = true;       // If you turn this to "false", any event in the feed that was modified after being added to the calendar will not update
var removeEventsFromCalendar = true;   // If you turn this to "true", any event created by the script that is not found in the feed will be removed.
var addAlerts = true;                  // Whether to add the ics/ical alerts as notifications on the Google Calendar events, this will override the standard reminders specified by the target calendar.
var addOrganizerToTitle = false;       // Whether to prefix the event name with the event organiser for further clarity
var descriptionAsTitles = false;       // Whether to use the ics/ical descriptions as titles (true) or to use the normal titles as titles (false)
var addCalToTitle = false;             // Whether to add the source calendar to title
var addAttendees = false;              // Whether to add the attendee list. If true, duplicate events will be automatically added to the attendees' calendar.
var defaultAllDayReminder = -1;        // Default reminder for all day events in minutes before the day of the event (-1 = no reminder, the value has to be between 0 and 40320)
                                       // See https://github.com/derekantrican/GAS-ICS-Sync/issues/75 for why this is neccessary.
var addTasks = false;

var emailSummary = false;              // Will email you when an event is added/modified/removed to your calendar
var email = "";                        // OPTIONAL: If "emailWhenAdded" is set to true, you will need to provide your email

**Comment by jonas0b1011001** [comment]
Settings seem fine.

Please visit [https://script.google.com/home/executions](https://script.google.com/home/executions), you will be able to view the execution log by clicking on an entry. Can you share the log of the last execution?

**Comment by Freedom9339** [comment]
I can. It does a bunch of events, then it has a failure.

```
Jul 2, 2020, 12:18:14 PM	Error	TypeError: Cannot read property 'dateTime' of undefined
    at [unknown function](Helpers:493:44)
    at processEventInstance(Helpers:492:45)
    at startSync(Code:203:7)
```

**Comment by jonas0b1011001** [comment]
[This](https://github.com/derekantrican/GAS-ICS-Sync/issues/135#issuecomment-644348397) should fix it.

**Comment by Freedom9339** [comment]
Ok, yea that seems to of solved the issue. Thank You!
