### ISSUE TITLE
Issue with validation

### ISSUE THREAD

**Issue by Ankit-Sati** [derekantrican/GAS-ICS-Sync#142]
In need to update a macro in excel, 
Normally the macro is running in offline excel however upon shifting the same to google sheet it shows this error
SyntaxError: Unexpected token '{' (line 1, file "Code.gs")
Pls. help to rectify.
[Book4.zip](https://github.com/derekantrican/GAS-ICS-Sync/files/4974856/Book4.zip)

**Comment by derekantrican** [comment]
Could you clarify? This script has nothing to do with Excel. Please share an ICS url or a link to your copy of the script and we can take a look

**Comment by Ankit-Sati** [comment]
Using the below mentioned macro in Google sheet to scan a barcode and timestamp the same, pls. check how this macro would run in google sheets

Sub Attendance()
Dim barcode As String
Dim rng As Range
Dim rownumber As Long

barcode = Worksheets("Sheet1").Cells(2, 2)

    Set rng = Sheet1.Columns("a:a").Find(What:=barcode, _
    LookIn:=xlFormulas, LookAt:=xlWhole, SearchOrder:=xlByRows, _
    SearchDirection:=xlNext, MatchCase:=False, SearchFormat:=False)
    If rng Is Nothing Then
        ActiveSheet.Columns("a:a").Find("").Select
        ActiveCell.Value = barcode
        ActiveCell.Offset(0, 1).Select
        ActiveCell.Value = Date & "  " & Time
        ActiveCell.NumberFormat = "m/d/yyyy h:mm AM/PM"
        Worksheets("Sheet1").Cells(2, 2) = ""
    Else
        rownumber = rng.Row
        Worksheets("Sheet1").Cells(rownumber, 1).Select
        ActiveCell.Offset(0, 2).Select
        ActiveCell.Value = Date & "  " & Time
        ActiveCell.NumberFormat = "m/d/yyyy h:mm AM/PM"
        Worksheets("Sheet1").Cells(2, 2) = ""
            
    End If
End Sub

**Comment by derekantrican** [comment]
This is not a place to help you with Excel macros. This is for the Google Apps Script "GAS-ICS-Sync"
