### ISSUE TITLE
add identifier to title 

### ISSUE THREAD

**Issue by rinzula** [derekantrican/GAS-ICS-Sync#144]
wondering if i can add a prefix to the title of event before. example event title is "John Doe" I would like to add a prefix before so that it would say "client: John Doe" 
is there a line in there that i can type "client" so that the title will insert the word before the info fetched from the ical?

**Comment by derekantrican** [comment]
Theoretically, yes. The question is: how many such cases do you have? Do you want every single event to have "client: " before it? Or are you wanting to set up some system like "John Doe" -> "client: John Doe" and "Sally" -> "friend: Sally", etc?

**Comment by rinzula** [comment]
I have used 2 icals for the script, one for my clients and one for my co-workers clients which creates two calendars for me. I would like mine to say my name before the title (I'm Lea, so "Lea: John Doe") and my co worker's name before his clients (he is Judd, so "Judd: Jane doe") it's two different icals on the same app script. This creates two different calendars and I can change the colors but it would just be easier if we could see our names before the customer name in the title. If necessary I can do two different app scripts if this is not customizable inside one script for two icals.

**Comment by jonas0b1011001** [comment]
Have a look at [this](https://github.com/derekantrican/GAS-ICS-Sync/issues/130#issuecomment-632347064), the linked script will actually do both, add a prefix and change color according to the source calendar.

**Comment by rinzula** [comment]
Will do, I'll let you know. Thanks

**Comment by rinzula** [comment]
Ok worked like a charm! TY

**Comment by rinzula** [comment]
Hi good morning! The program ran correctly at first but stopped working. On the execution log when it runs, it installs and then runs startsync each time. the install gives no logs and the start sync logs "	Another iteration is currently running! Exiting..."

**Comment by jonas0b1011001** [comment]
The custom script i linked above is based on v5.2, that version will get softlocked once an execution ends in an error. I will port the custom version to v5.3  which will resolve the **symptoms**.

In the meantime you could help us identify the error which initially caused the script to 'crash' by finding the log of the last successful execution [here](https://script.google.com/home/executions) (should be quite obvious by comparing the execution durations).  You should be able the find an error message in that log.

**Comment by rinzula** [comment]
8 executions in all before error.

1 First execution install
2,3,4,  startsync execution successful (3 in a row)
5 execution install
6 execution startsync successful
7 execution install 
8 execution startsync error:
Aug 3, 2020, 1:02:20 PM	Error	Exception: Data storage error at startSync(Code:128:41)

**Comment by rinzula** [comment]
i uninstalled it, deleted the calendars it created and triggers, then made a new copy and ran the new copy, so far it seems to be working i will let you know if the sync fails

**Comment by jonas0b1011001** [comment]
> Aug 3, 2020, 1:02:20 PM Error Exception: Data storage error at startSync(Code:128:41)

That's caused by a bug in google's services. It was first reported back in [2017](https://issuetracker.google.com/issues/36765657), according to [this](https://issuetracker.google.com/issues/162647522) it was fixed just today.

However I ported the changes to the latest dev build, [this](https://script.google.com/d/1b3rlpU4UN5WIeAJ0PPFBxMkQPCfNb5p5GR4WRs88Vh-LrG3ha6xaweBf/edit?usp=sharing) should continue working even if the error occurs again.

**Comment by derekantrican** [comment]
I don't know if "hotlist" necessarily means it was fixed (the status still
says "New"). I don't work for Google but I would imagine it means it's
queued up to be worked on

**Comment by rinzula** [comment]
Ok, so after about a half day it popped the same error code. currently uninstalling and implementing the new iteration you gave yesterday :)

**Comment by rinzula** [comment]
Running without a hitch! Thank you again for all of your help :)
