### ISSUE TITLE
Sign in with Google temporarily disabled for this app This app has not been verified yet by Google in order to use Google Sign In.

### ISSUE THREAD

**Issue by GiguereConsulting** [derekantrican/GAS-ICS-Sync#147]
hi guys new here,

I got this trying to run the script :

**Sign in with Google temporarily disabled for this app. This app has not been verified yet by Google in order to use Google Sign In.**

Can you help? appreciate it!

![Sans titre](https://user-images.githubusercontent.com/69319091/89561696-e012cd80-d7e6-11ea-969a-52b86f3d7896.png)

**Comment by GiguereConsulting** [comment]
I want to ensure this get buried @derekantrican 

Talk soon

**Comment by jonas0b1011001** [comment]
Hi, there is an unresolved [Bugreport](https://issuetracker.google.com/issues/145162820) on Google's IssueTracker. This seems to randomly affect users, nothing we can do about it unfortunately..

**Comment by GiguereConsulting** [comment]
Got around it with that https://youtu.be/_5k10maGtek?t=1m22s and the script run succesfully on my targeted G-calendar account.

but it seems like the G-calendar didn't update my office 365 calendar. Like it's Static since I imported one week ago using that process https://www.howtogeek.com/435975/how-to-show-an-outlook-calendar-in-google-calendar/#:~:text=Click%20on%20Settings%20%3E%20View%20all,%2C%20and%20click%20%E2%80%9CPublish.%E2%80%9D

Any ideas or fix?

**Comment by derekantrican** [comment]
In that "howtogeek" article you shared, make sure you are using the "publish" option and not an "export" option. Publish will update the data available at the published url but export will just share a snapshot

**Comment by GiguereConsulting** [comment]
@derekantrican I'm using the "publish" option and after 5 days of testing. still it seems like snapshot. I'm out of ideas...Any other fix or workaround?

Appreciate your contribution!

**Comment by derekantrican** [comment]
@GiguereConsulting want to ping on this - any luck with trying the "publish" option again? Could you share a screenshot of the publish screen and/or your ICS link? If it has sensitive information you can email me at derekantrican@gmail.com
