### ISSUE TITLE
TypeError: Cannot read property 'dateTime' of undefined

### ISSUE THREAD

**Issue by dfishburn** [derekantrican/GAS-ICS-Sync#149]
- I am getting periodic:
`TypeError: Cannot read property 'dateTime' of undefined in Helper.gs` @ line 492 in version 5.3

When reading a recurring calendar event created in CEST, while I am in EST (if relevant).

So I modified the code and changed these this:
```
  var eventInstanceToPatch = calendarEvents.filter(function(item){
      var origStart = item.originalStartTime.dateTime || item.originalStartTime.date;
      var instanceStart = new ICAL.Time.fromString(origStart);
      
      return (instanceStart.compare(recIDStart) == 0);
  });
```
To this:
```
  var eventInstanceToPatch = calendarEvents.filter(function(item){
    try{
      var origStart = item.originalStartTime.dateTime || item.originalStartTime.date;
      var instanceStart = new ICAL.Time.fromString(origStart);
      
      return (instanceStart.compare(recIDStart) == 0);
    }
    catch(error){
      Logger.log("eventInstanceToPatch - Invalid date");
      Logger.log(error); 
      Logger.log("eventInstanceToPatch - item");
      Logger.log(item); 
      Logger.log("eventInstanceToPatch - repeat the failure");
      var origStart = item.originalStartTime.dateTime || item.originalStartTime.date;
    }
  });
```
- I didn't know the syntax to rethrow the error, so I just called the same origStart line.  Now I get to see the error and log the item that is causing it:
```
TypeError: Cannot read property 'dateTime' of undefined
    at [unknown function](Helpers:503:46)
    at processEventInstance(Helpers:492:45)
    at startSync(Code:205:7)
```

The item which triggered the error:
`{start={dateTime=2020-07-21T13:05:00Z, timeZone=America/Phoenix}, kind=calendar#event, reminders={useDefault=true}, extendedProperties={private={rec-id=040000008200E00074C5B7101A82E0080000000080ABB95B93FED501000000000000000010000000080112D7CED60448B15B6DF19C78CC0C_2020-07-21T06:05:00, fromGAS=true, id=040000008200E00074C5B7101A82E0080000000080ABB95B93FED501000000000000000010000000080112D7CED60448B15B6DF19C78CC0C, MD5=-9,-116,-42,-107,102,-72,-15,-88,85,84,-113,118,-86,-81,79,-6}}, end={timeZone=America/Phoenix, dateTime=2020-07-21T14:00:00Z}, visibility=public, updated=2020-08-21T00:44:58.948Z, creator={email=me@gmail.com}, htmlLink=https://www.google.com/calendar/event?eid=a2dkYzRjbWQxdHYxNzhyY2NtcWYyM2djbW8gaTJmZmM4cnV1aG9pcGtvcG80MThjZjdlaGtAZw&ctz=UTC, id=kgdc4cmd1tv178rccmqf23gcmo, iCalUID=kgdc4cmd1tv178rccmqf23gcmo@google.com, organizer={email=i2ffc8ruuhoipkopo418cf7ehk@group.calendar.google.com, self=true, displayName=Work}, status=confirmed, created=2020-08-21T00:44:58.000Z, etag="3195941397896000", sequence=0.0, location=Microsoft Teams Meeting, summary=FW: Secure Cloud Delivery (Evolve) Update and Office Hours- EU}
`
The picture included is the calendar imported via Google Import URL, and through GAS, highlighted in green.
![gas_invalid_date](https://user-images.githubusercontent.com/646124/90840675-98349000-e328-11ea-8814-7771a6d1b401.jpg)

There are quite a few references to dateTime in the item I provided, how do you know which one it is complaining about?

**Comment by WhiteLupus** [comment]
TypeError: Cannot read property 'dateTime' of undefined (line 493, file "Helpers")

I am getting the same here.

Didn't quite understood if the modification solved the error for you ?

**Comment by dfishburn** [comment]
My code change simply suppressed the error and logged the item, so I at least know which calendar item was causing the failed sync.  So the sync succeeds and ignores that particular problem.
I am getting duplicates in my calendar, don't know if it is related to this or not.

**Comment by WhiteLupus** [comment]
I just tried running the function without changes it didn't show that error.
Several times sequentally.
Then showed one time....
Not sure how it repeats

**Comment by jhallenb** [comment]
I also get this, I got it when I manually run the sync from the Run menu.
My calendar is a outlook office365 .ics weblink.

**Comment by jonas0b1011001** [comment]
Have you guys tried the solution provided [here](https://github.com/derekantrican/GAS-ICS-Sync/issues/135#issuecomment-644348397)?

**Comment by joey4247** [comment]
Yep, just tried now with the updated ical.js.gs you mention, still failing sadly.

**Comment by jonas0b1011001** [comment]
> When reading a recurring calendar event

@dfishburn Is the event mentioned actually a recurring event or is it a one-time event?

@joey4247 Are you trying to sync an outlook calendar aswell?

**Comment by joey4247** [comment]
Yep. Outlook calendar hosted on office365. I'll give it a while to see if the syncs throw up more errors/anything useful.

**Comment by dfishburn** [comment]
Definitely recurring.
Here it is opened in Outlook.
Note, if came from a European, so the timezones are different.
![gcal_repeat](https://user-images.githubusercontent.com/646124/92063217-a773fe80-ed68-11ea-854c-e1055c19e70d.jpg)

**Comment by dfishburn** [comment]
@ jonas0b1011001 when you quoted the "solution", since that is a thread with lots of comments.
Are you specifically referring to trying with the "DEV" version of Code.gs linked in [his comments](https://github.com/derekantrican/GAS-ICS-Sync/issues/135#issuecomment-665943231)?

**Comment by jonas0b1011001** [comment]
@dfishburn Yes, you can either run the script from the comment you linked, or manually replace ical.js.gs in your copy of the script with [this one](https://raw.githubusercontent.com/derekantrican/GAS-ICS-Sync/dev/ical.js.gs).

@joey4247 Can you share your ics source? You can remove all sensitive data with [https://derekantrican.github.io/icssanitizer.html](https://derekantrican.github.io/icssanitizer.html) (would be helpful if Event IDs remain unchanged though)

**Comment by joey4247** [comment]
@jonas0b1011001 Sure thing. Sanitised here: https://pastebin.com/ZCFQjUrq
Switching to the dev ical.js.gs didn't gel well, so have switched back.
Here it also seems to be a recurring event, and I too am in another time zone: CEST (GMT+2)

**Comment by jonas0b1011001** [comment]
> @jonas0b1011001 Sure thing. Sanitised here: https://pastebin.com/ZCFQjUrq
> Switching to the dev ical.js.gs didn't gel well, so have switched back.
> Here it also seems to be a recurring event, and I too am in another time zone: CEST (GMT+2)

Thanks, i was able to reproduce the error with the current release, the dev build seems to sync fine though. Did you sync to a different/new calendar after switching between the two versions?

**Comment by joey4247** [comment]
Ah I forgot about the trigger, that explains why. Will go back to the dev code and also set up the triggers properly . Will report back

**Comment by dfishburn** [comment]
@jonas0b1011001 New script installed and I have removed my try catch block from Helper.gs to restore it to the original.  This will allow me to see failed syncs.
I have also deleted my calendar to start fresh.

**Comment by dfishburn** [comment]
@jonas0b1011001  the new ical,js,gs has not fixed the issue:
TypeError: Cannot read property 'dateTime' of undefined

I will add back the Helper.js.gs try catch and see if it is for the same event.

**Comment by jonas0b1011001** [comment]
> @joey4247 Can you share your ics source? You can remove all sensitive data with https://derekantrican.github.io/icssanitizer.html (would be helpful if Event IDs remain unchanged though)

@dfishburn Could you do the same? I have some ideas that might cause the issue but it would be easier if i can test for myself.

**Comment by dfishburn** [comment]
@jonas0b1011001 [Here it is with a 1 month expiry](https://pastebin.com/ePYD8fA4).

There are really 2 issues, and I don't know if they are related to the failure.

1. The datetime issue discussed in this thread
1. Duplicates (I get a lot of duplicate appointments)

I only mention the 2nd, in case you see it with the calendar source provided.

I appreciate you looking into it.

**Comment by jonas0b1011001** [comment]
Thanks, i just did a quick test and the file synced without error using [this version](https://script.google.com/d/1OEk9McqgsQ8UQeybvRfvvx6IbORexFRzSW7c2sxTfBV5v0rTnDrSWa0A/edit).
Could you please run that script (no modifications, fresh target calendar) and share the log output (you can find it at [https://script.google.com/home/executions](https://script.google.com/home/executions)).

Number 2 should be caused by the modification you made.

**Comment by joey4247** [comment]
> Ah I forgot about the trigger, that explains why. Will go back to the dev code and also set up the triggers properly . Will report back

Switched to dev code, had to manually set the trigger again as per bug #137 but yes everything is working absolutely fine!

**Comment by dfishburn** [comment]
@jonas0b1011001 failed again with the updated code.
https://pastebin.com/8Bwvxru8 (2 week expiry)
Same code spot in Helpers:

```
TypeError: Cannot read property 'dateTime' of undefined
    at [unknown function](Helpers:494:46)
    at processEventInstance(Helpers:492:45)
    at startSync(Code:202:7)
```

**Comment by jonas0b1011001** [comment]
The log you shared is not from the version i linked. Did you uninstall the version you were using initially?

**Comment by dfishburn** [comment]
@jonas0b1011001  Hmm, I renamed Code.gs to Code.orig.gs, then File -> New -> Script file -> Code.gs and pasted in the new code from the link.
Is that the wrong approach?

**Comment by derekantrican** [comment]
Google Apps Script will use functions wherever it finds them - filenames do not really mean anything other than organization. I would suggest removing that file entirely and trying again

**Comment by jonas0b1011001** [comment]
> @jonas0b1011001 Hmm, I renamed Code.gs to Code.orig.gs, then File -> New -> Script file -> Code.gs and pasted in the new code from the link.
> Is that the wrong approach?

The important files are _Helpers.gs_ and _ical.js.gs_

As Derek suggested, the easiest way would probably be to make a new copy of the dev script just like you did when you first installed the script. You can also run the sync without installing the script by running _startSync_ instead of _install_, that way you do not have to mess around with the other instance (just make sure to sync to a different target calendar).

**Comment by dfishburn** [comment]
@jonas0b1011001 So far so good.  No errors reported since I updated last night.  Also no duplicates that I can see at this point.
I really appreciate the help and your effort.
