### ISSUE TITLE
All events is always detected like modified

### ISSUE THREAD

**Issue by FabienZa** [derekantrican/GAS-ICS-Sync#150]
Hello,

Thanks for your help, I think the problem is from the provider, but I can't modify it.

In fact, all events is always detected like modified and I receive one notification with all events "updated" for each execution

![image](https://user-images.githubusercontent.com/38133819/92113831-32e4a280-edf0-11ea-96f9-f9cfba9f771a.png)

The .ics : https://pastebin.com/dUuH5QnA

Thanks again !

**Comment by derekantrican** [comment]
We've seen this problem before (particularly with Outlook calendars - but also with some others). Basically, the unique id for each event is being "reassigned" every time the ICS is retrieved. From the research that we've done, this seems to be against the [RFC specification](https://tools.ietf.org/html/rfc5545) and causes the script to think that all the events have been deleted and they have to be all recreated brand-new (this can also cause your script to take a long time to execute).

One thing you can definitely do: you can contact your calendar provider and see if they have an option you can change or if they can change it on their end. I'll look into what solutions we could have on our end too

**Comment by jonas0b1011001** [comment]
> all events is always detected like modified

That's what the ics is telling the script. If you take a look at one of your events 
```
BEGIN:VEVENT
DTSTAMP:20200903T121906Z
DTSTART:20200914T124500Z
DTEND:20200914T144500Z
SUMMARY:1ce7781619dcd256766e66e65b801cd3
LOCATION:4afb5682bf2e4cd0b11d4b7e5d254935
DESCRIPTION:0b1aef731472bccb8c1c23756c53bf56
UID:8fda4f103ec61017f2231b6983a1e109
CREATED:19700101T000000Z
LAST-MODIFIED:20200903T121906Z
SEQUENCE:2024751546
END:VEVENT
```
the _LAST-MODIFIED_ parameter states that the event was changed the same time as the ics was created (that's the _DTSTAMP_ parameter).

You can ignore that by adding
`event.removeProperty('last-modified');`
below [line 225](https://github.com/derekantrican/GAS-ICS-Sync/blob/b50f50a393260b8d47d73a6cf07567999b98ea17/Helpers.gs#L225) in Helpers.gs

**Comment by FabienZa** [comment]
Thanks you, I tried to add  `event.removeProperty('last-modified');` but it doesn't change anything.

**Comment by jonas0b1011001** [comment]
In that case there might be another property that's changing whenever the calendar is created.

You can check that by downloading your source *.ics with a few minutes in between. You can view the *.ics using a text editor and compare any of the events. Did anything change besides _DTSTAMP_ and _LAST-MODIFIED_?

**Comment by Ali1** [comment]
@FabienZa where did you get that view in the screenshot with execution summaries listed like that? Thanks

**Comment by jonas0b1011001** [comment]
That's a screenshot of his gmail inbox, [var emailSummary = true;](https://github.com/derekantrican/GAS-ICS-Sync/blob/940b1489f56d17ef87d99c6771dbbbcf652c0a53/Code.gs#L41) will create these.

**Comment by derekantrican** [comment]
@FabienZa did you try Jonas' suggestion?

**Comment by FabienZa** [comment]
Hello ! Sorry I answer very very later ! But this year I have the same issue ! ;)

I checked with 2 .ics file for try to find the differences.

I found :  
- DTSTAMP that is normal if I understood because it's when I downloaded the .ics file.
- LAST-MODIFIED that correspond to the time when I downloaded the file, it's may be the problem, but remove this property when add `event.removeProperty('last-modified');` don't seem to works.
- SEQUENCE whos is increment by one, but I totally don't know if it s normal or not

```
BEGIN:VEVENT
DTSTAMP:20210914T100920Z
DTSTART:20211018T081500Z
DTEND:20211018T101500Z
SUMMARY::XXXXX
LOCATION::XXXXX
DESCRIPTION::XXXXX
UID::XXXXX
CREATED:19700101T000000Z
LAST-MODIFIED:20210914T100920Z
SEQUENCE:2125743760
END:VEVENT
```

```BEGIN:VEVENT
DTSTAMP:20210914T100941Z
DTSTART:20211018T081500Z
DTEND:20211018T101500Z
SUMMARY:XXXXX
LOCATION:XXXXX
DESCRIPTION:XXXXX
UID:XXXXX
CREATED:19700101T000000Z
LAST-MODIFIED:20210914T100941Z
SEQUENCE:2125743781
END:VEVENT
```

Thanks for your help ! =)
