### ISSUE TITLE
startSync fails

### ISSUE THREAD

**Issue by radratter** [derekantrican/GAS-ICS-Sync#153]
![image](https://user-images.githubusercontent.com/71352906/93265705-9ebef780-f76e-11ea-96de-17172f706d39.png)

**Comment by jonas0b1011001** [comment]
The calendar you are trying to sync does not conform to the ical standard, the events are missing an id.
You can do [this change](https://github.com/derekantrican/GAS-ICS-Sync/issues/89#issuecomment-567065550) to work around the wrong input (in the version you are using the lines to replace are 145-155).

I'm closing the issue, if the solution does not solve your problem feel free to report back.
