### ISSUE TITLE
Add attendees to event description

### ISSUE THREAD

**Issue by traviskorth** [derekantrican/GAS-ICS-Sync#156]
Hi, I don't want to add the attendees from my work account to my Google Calendar events, but I still want to know who was invited and what their responses were.   I've tried to mockup what that might look like and before I added it to my code, I just wanted to make sure it made sense.  I'm a complete noob at Google Script, but make a lot of VBS scripts for Office products.  Please forgive and correct any code errors.  

My thought was to borrow the code for addAttendees, but just use it to make a string like this:

> Attendee List:
> John Smith, jsmith@example.com: Accepted
> Jane Doe, jdoe@example.com: Unknown

Then add that into to the body at the beginning of the description.  

The code uses a new variable that would be defined in the code.gs, addAttendeeToBody, and a string, attendeeList to form the list.

`  
/**
   * Add attendee list to top of invite body.  The top should not 
   * interfere with the Webex and Teams invites. 
   */
  if (addAttendeesToBody && event.hasProperty('attendee')){

	var attendeeList = "Attendee List:\n";
	
    for (var att of icalEvent.attendees){
      var mail = parseAttendeeMail(att.toICALString());
      if (mail != null){

        var name = parseAttendeeName(att.toICALString());

        var resp = parseAttendeeResp(att.toICALString());

		attendeeList = attendeeList + name + ", " + mail + ": " + resp + "\n"
		
      }
    }
  }
`

I would add the attendeeList string to the description:

```
   if (event.hasProperty('description'))
    newEvent.description = attendeeList + icalEvent.description;

```
Does that all make sense?  

Also, would that update every time the attendee responses changed?

Thanks for your thoughts!
Travis

**Comment by jonas0b1011001** [comment]
I don't see any obvious errors. However, the _attendeeList_ will not be added if the original event has no event description. Depending on how likely that is in your scenario you might want to change that.

> Also, would that update every time the attendee responses changed?

Yes it will.

**Comment by traviskorth** [comment]
So maybe I should do it like this:

`if (event.hasProperty('description') ||  attendeeList <> "")
    newEvent.description = attendeeList + icalEvent.description;`

Check to see if either are true.  If there is no description, then add just the attendeeList.   Will it cause any issues if I try to concatenate the icalEvent.description if it is empty?

Thanks!

**Comment by jonas0b1011001** [comment]
```
if (event.hasProperty('description')){
  newEvent.description = attendeeList + icalEvent.description;
}
else{
  newEvent.description = attendeeList
}
```
Should do it just fine.

> Will it cause any issues if I try to concatenate the icalEvent.description if it is empty?

No real issues, but it will add the String "NULL" representing the missing property.

**Comment by traviskorth** [comment]
Thanks for the help.  I got it to work as expected.  Unfortunately, a published ICS from Outlook 365 does not appear to include attendee information...
