### ISSUE TITLE
CheckforUpdate is not defined - trying to use Calendar Sync script

### ISSUE THREAD

**Issue by dnkpercifield** [derekantrican/GAS-ICS-Sync#160]
The CheckForUpdate function is not defined in the Calendar Sync Script.

https://script.google.com/d/1jOJ9Gem0uiesNijafCnztPRKPrEAC7UInaKgd3qiE-wayQV97KbFeTk_/edit?usp=drive_web&folder=0APgbuSzvJzIeUk9PVA&splash=yes

**Comment by derekantrican** [comment]
@dnkpercifield I don't seem to have access to view the script. Please either make it so "anyone with the link can view" or share with "derekantrican@gmail.com"

**Comment by derekantrican** [comment]
Looks like you only copied the Code.gs file. There's a couple files that are required for the script to work. Please follow these instructions to make sure you have all the files: https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually

**Comment by dnkpercifield** [comment]
Hi Derek,

Will Google Calendar sync automatically in 12 hours or so without your
script?

**Comment by dnkpercifield** [comment]
Hi Derek,

Does this work with Outlook 365?

**Comment by derekantrican** [comment]
To answer your questions:

- Yes, you can use Google Calendar's built in ICS sync feature which updates approximately once every 12 hours
- Both our script and Google Calendar's built in feature should support Outlook 365

**Comment by dnkpercifield** [comment]
Thank you for the information and quick response.
