### ISSUE TITLE
New Calendar gets added but does still does not sync

### ISSUE THREAD

**Issue by mark213a** [derekantrican/GAS-ICS-Sync#161]
HI All - Ive manged to use the script in google scripts and install it.
Trying to sync from Outlook ICS file to GCAL
The initial install runs fine - and app is authorised. Entries are ported fine
So does the startsync - this works fine if its run manually

But if I make a change in outlook and then leave it to auto sync it doesnt update. It does not re-sync at the 15min interval default.
If I run start sync again it syncs but only a one off at a time and does not automate going forwards.

Screenshots show that in GCAL still has old entries (m tester file at 9am). New Entries and modified entries are in Outlook but not reflected (see m tester file moved to 5pm and see Kate (Scouts) updated entry not reflected)

Thanks Guys!!!

Screen shots attached from GCAL, Google Scripts, and Outlook

![image](https://user-images.githubusercontent.com/73808822/97830857-54d3a600-1d09-11eb-98a7-3a4686866e0b.png)
![image](https://user-images.githubusercontent.com/73808822/97830901-7896ec00-1d09-11eb-8281-5b915e12de5f.png)
![image](https://user-images.githubusercontent.com/73808822/97830948-995f4180-1d09-11eb-9f39-cdad08a41682.png)
![image](https://user-images.githubusercontent.com/73808822/97831041-e3e0be00-1d09-11eb-81f2-fa4c72055d0c.png)
![image](https://user-images.githubusercontent.com/73808822/97831238-610c3300-1d0a-11eb-965e-fac6cb1c355e.png)
![image](https://user-images.githubusercontent.com/73808822/97831262-6e292200-1d0a-11eb-855d-a851eb513a98.png)

My Code and ICS is below (pls make private if you can!)

/*
*=========================================
*       INSTALLATION INSTRUCTIONS
*=========================================
*
* 1) Click in the menu "File" > "Make a copy..." and make a copy to your Google Drive
* 2) Changes lines 19-41 to be the settings that you want to use
* 3) Click in the menu "Run" > "Run function" > "install" and authorize the program
*    (For steps to follow in authorization, see this video: https://youtu.be/_5k10maGtek?t=1m22s )
* 4) You can also run "startSync" if you want to sync only once.
*
* **To stop the Script from running click in the menu "Run" > "Run function" > "uninstall"
*
*=========================================
*               SETTINGS
*=========================================
*/

var sourceCalendars = [                // The ics/ical urls that you want to get events from along with their target calendars (list a new row for each mapping of ICS url to Google Calendar)
                                       // For instance: ["https://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics", "US Holidays"]
  ["https://outlook.live.com/owa/calendar/[**PLS_EMAIL/PM_ME_FOR_FULL_ADDRESS**]/calendar.ics", "Belinda Paulton (OUTLOOK)"]
  
];

var howFrequent = 15;                  // What interval (minutes) to run this script on to check for new events
var onlyFutureEvents = false;          // If you turn this to "true", past events will not be synced (this will also removed past events from the target calendar if removeEventsFromCalendar is true)
var addEventsToCalendar = true;        // If you turn this to "false", you can check the log (View > Logs) to make sure your events are being read correctly before turning this on
var modifyExistingEvents = true;       // If you turn this to "false", any event in the feed that was modified after being added to the calendar will not update
var removeEventsFromCalendar = true;   // If you turn this to "true", any event created by the script that is not found in the feed will be removed.
var addAlerts = true;                  // Whether to add the ics/ical alerts as notifications on the Google Calendar events, this will override the standard reminders specified by the target calendar.
var addOrganizerToTitle = false;       // Whether to prefix the event name with the event organiser for further clarity
var descriptionAsTitles = false;       // Whether to use the ics/ical descriptions as titles (true) or to use the normal titles as titles (false)
var addCalToTitle = false;             // Whether to add the source calendar to title
var addAttendees = false;              // Whether to add the attendee list. If true, duplicate events will be automatically added to the attendees' calendar.
var defaultAllDayReminder = -1;        // Default reminder for all day events in minutes before the day of the event (-1 = no reminder, the value has to be between 0 and 40320)
                                       // See https://github.com/derekantrican/GAS-ICS-Sync/issues/75 for why this is neccessary.
var addTasks = false;

var emailSummary = false;              // Will email you when an event is added/modified/removed to your calendar
var email = "";                        // OPTIONAL: If "emailWhenAdded" is set to true, you will need to provide your email

**Comment by jonas0b1011001** [comment]
Please share the log of the install() execution at 10:51 (click on the list entry to expand)

**Comment by mark213a** [comment]
Install is empty at 10.51 - but as you can see startsync does have entries. Let me know if you need the full list.
Looked at the other install() logs and they also read
_No logs are available for this execution
For recent executions there may be some delay in log availability._


![image](https://user-images.githubusercontent.com/73808822/97841649-42fdfd00-1d21-11eb-8334-862721c1472e.png)

**Comment by jonas0b1011001** [comment]
For the time being i would suggest manually doing one of the changes described in #137. Replacing your install() function like described [here](https://github.com/derekantrican/GAS-ICS-Sync/issues/137#issuecomment-654286119) should make scheduled syncing work for you.

Unfortunately we currently do not have a better solution.

**Comment by mark213a** [comment]
Thanks Ive updated it with the below install() from your update on 16 Sep? 
Seems to have installed and run ok for the initial
Will see if it runs the updates automatically and let you know.

My new script is as below and screeshots of the executions and triggers

Cheers

//=====================================================================================================
//!!!!!!!!!!!!!!!! DO NOT EDIT BELOW HERE UNLESS YOU REALLY KNOW WHAT YOU'RE DOING !!!!!!!!!!!!!!!!!!!!
//=====================================================================================================
//function install(){
//  try{
//    //Delete any already existing triggers so we don't create excessive triggers
//    deleteAllTriggers();
//    
//    if (howFrequent < 1){
//      throw "[ERROR] \"howFrequent\" must be greater than 0.";
//    }
//    else{
//      ScriptApp.newTrigger("install").timeBased().after(howFrequent * 60 * 1000).create();//Schedule next Execution
//      ScriptApp.newTrigger("startSync").timeBased().after(1000).create();//Start the sync routine
//    }
//  }catch(e){
//    install();//Retry on error
//  }
//}

function install(){
  //Delete any already existing triggers so we don't create excessive triggers
  deleteAllTriggers();
  
  if (howFrequent < 1)
    throw "[ERROR] \"howFrequent\" must be greater than 0.";
  
  var result = callWithBackoff(function(){
    ScriptApp.newTrigger("install").timeBased().after(howFrequent * 60 * 1000).create();//Schedule next Execution
    
    var triggers = ScriptApp.getProjectTriggers().filter(function(trigger){
      return trigger.getHandlerFunction() == "install";
    });
    
    if (triggers.length < 1)
      throw "[ERROR] Failed to create trigger for next execution.";
    
    return true;
  }, 10);
  
  if (result){
    ScriptApp.newTrigger("startSync").timeBased().after(1000).create();//Start the sync routine
  }
  else{
    throw "[ERROR] Installing the script failed."
  }
}

function uninstall(){
  deleteAllTriggers();
}


![image](https://user-images.githubusercontent.com/73808822/98065163-e882af00-1e8e-11eb-8340-b94209157a7f.png)
![image](https://user-images.githubusercontent.com/73808822/98065307-5038fa00-1e8f-11eb-956a-9238e89ab089.png)

**Comment by mark213a** [comment]
Hi - it installed fine - and worked. It then ran after 15 mins again on its own, but has since died. It didnt execute the Startsync and seemed to go to disabled. Then when it tried again after 30mins, neither ran and both now are disabled

![image](https://user-images.githubusercontent.com/73808822/98068540-474c2680-1e97-11eb-9691-8df068448ea3.png)

![image](https://user-images.githubusercontent.com/73808822/98068552-53d07f00-1e97-11eb-9fd6-a3bc2a2cbfd4.png)

Any ideas?

**Comment by jonas0b1011001** [comment]
Try this one

```
function install(){
      ScriptApp.newTrigger("startSync").timeBased().everyMinutes(howFrequent).create();
}
```

**Comment by geogolem** [comment]
> Try this one
> 
> ```
> function install(){
>       ScriptApp.newTrigger("startSync").timeBased().everyMinutes(howFrequent).create();
> }
> ```

This is what I used and it has been working great for me.

**Comment by mark213a** [comment]
Done - lets see how it goes. I tried that first but it never triggered startSync - so will see and leave it a bit 

![image](https://user-images.githubusercontent.com/73808822/98184782-2c84bb00-1f46-11eb-885e-5b27243750b0.png)

**Comment by mark213a** [comment]
Looking good -works perfectly now. Thanks @jonas0b1011001 

![image](https://user-images.githubusercontent.com/73808822/98504523-1fdbcc00-2292-11eb-9e69-e3827435a952.png)
