### ISSUE TITLE
Syncing Not Working: Apple Calendar > Google Calendar 

### ISSUE THREAD

**Issue by michaelh82** [derekantrican/GAS-ICS-Sync#162]
Hi

I am completely new to Apps Script and Github so be gentle ;-)

I have 4 calendars set up in Apple Calendar which are also synced with my Google Calendar.  I have made a new copy of this script, leaving all the settings at their defaults, entering in the shared URL's as provided by Apple Calendar.  These are in the following format (I have replaced the numbers at the end with random numbers for this example):

webcal://p22-caldav.icloud.com/published/2/OTE0NjA5NDY5MTQ2M_AnVySais_s

So, when entering into the script, it looks like this:

["webcal://p22-caldav.icloud.com/published/2/OTE0NjA5NDY5MTQ2M_AnVySais_s", "Family (iCloud)"]

However, this didn't work, as nothing is 'pulling' from Apple Calendar.  I wondered if the URL format is not supported, so I also tried the following versions:

["webcal://p22-caldav.icloud.com/published/2/OTE0NjA5NDY5MTQ2M_AnVySais_s.ics", "Family (iCloud)"]
["http://p22-caldav.icloud.com/published/2/OTE0NjA5NDY5MTQ2M_AnVySais_s", "Family (iCloud)"]
["http://p22-caldav.icloud.com/published/2/OTE0NjA5NDY5MTQ2M_AnVySais_s.ics", "Family (iCloud)"]
["https://p22-caldav.icloud.com/published/2/OTE0NjA5NDY5MTQ2M_AnVySais_s", "Family (iCloud)"]
["https://p22-caldav.icloud.com/published/2/OTE0NjA5NDY5MTQ2M_AnVySais_s.ics", "Family (iCloud)"]

But, no luck - no matter which format I use, nothing is pulling.

When I look at the executions, I get 'Failed' on the startSync continuously when the script is set to run at the default 15 minutes:

![Screenshot 2020-11-05 at 08 43 30](https://user-images.githubusercontent.com/73988417/98219286-b59af280-1f44-11eb-91a4-83a929605db3.png)

However, if I drop the run time down to 1 minute for testing purposes, the number of fails reduces dramatically:

![Screenshot 2020-11-05 at 08 45 26](https://user-images.githubusercontent.com/73988417/98219386-d7947500-1f44-11eb-8bd3-1623861a2702.png)

I am not sure if this is enough to go by, but if anyone has any advice on how to fix this, that would be great.  I assume I am doing something wrong or simply overlooked something somewhere.

Thanks in advance for your help.

Michael

**Comment by michaelh82** [comment]
A quick update on the above...

I noticed that I forgot to include a comma at the end of one of the URL lines, separating the calendars.  I have added that in now, so it looks like this (again, I have added random numbers at the end for this example):

var sourceCalendars = [                
// The ics/ical urls that you want to get events from along with their target calendars (list a new row for each mapping of ICS url to Google Calendar)
// For instance: ["https://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics", "US Holidays"]

  ["https://p22-caldav.icloud.com/published/2/AAAWtGGb8usk4lRdi7m8Mdlr_pettfXQA", "Family (iCloud)"],
  ["https://p22-caldav.icloud.com/published/2/OTE0NjA5NDY5MTQ2dPK_AnV3xpIQS8", "Mike - Shared (iCloud)"],
  ["https://p22-caldav.icloud.com/published/2/OTE0NjA5NNQJM3IIprl1qlu_LK3yYTzZl4", "Mike - Personal (iCloud)"],
  ["https://p22-caldav.icloud.com/published/2/OTE0NjA5NDY5ufKcsl1RLpb8-6RMqS0", "Rachel - Shared (iCloud)"]
  
];

And, now I get a different error:

![Screenshot 2020-11-05 at 09 31 16](https://user-images.githubusercontent.com/73988417/98223198-ae2a1800-1f49-11eb-942e-e3303b4f318f.png)

Not sure if this helps, but thought it was worth updating the thread, just incase.

Thanks
Michael

**Comment by jonas0b1011001** [comment]
Generally speaking, published icloud calendars should work just fine, you can use the link as provided in your icloud account as source URL.

Seems like there is some element in your calendar the parser can not handle.

Please sync each calendar separately and check if they all produce the error.

**Comment by michaelh82** [comment]
Thanks for the reply.

I seem to be making progress.  I have tried syncing the calendars separately, as you advised, and managed to find one calendar that is causing the startSync to fail (the one shown in my earlier screenshot above).  This needs investigating more, but for now, I have removed that calendar and just trying to focus on the other 3 calendars.

Although I am now getting no failed statuses, there does appear to be a permissions issue with the API - see the below screenshot:

![Screenshot 2020-11-05 at 21 48 01](https://user-images.githubusercontent.com/73988417/98300456-368fd380-1fb1-11eb-92ec-c582954c7f85.png)

I have been through my Google settings as per https://stackoverflow.com/questions/57706338/google-calendar-api-writer-access-error-when-setting-up-events-on-someones-cal/57736250#57736250.  However, this hasn't fixed the writer permissions issue.  

Any ideas?

**Comment by jonas0b1011001** [comment]
> Although I am now getting no failed statuses, there does appear to be a permissions issue with the API

You can only sync to calendars you own. I assume you previously imported the icloud clandars using google calendar's web interface which creates a read-only version of the calendar. You can either delete those calendars from your google calendar or change the target calendar names in the script.

> This needs investigating more

If you want i'll have a look at the calendar and try to find what's causing the issue. You can remove sensitive data with [https://derekantrican.github.io/icssanitizer.html](https://derekantrican.github.io/icssanitizer.html)

**Comment by michaelh82** [comment]
Thanks for coming back to me on this.

Ahh, yes...you are correct.  I deleted the calendars from Google Calendar and then the script run and pulled everything in perfectly and is updating every 15 minutes now.  So, this appears to have fixed the issues I was having.

> If you want i'll have a look at the calendar and try to find what's causing the issue. You can remove sensitive data with https://derekantrican.github.io/icssanitizer.html

That would be great, if you don't mind.  The other 3 calendars pull and update perfectly, so it is just this one calendar that it still doesn't like:

![Screenshot 2020-11-08 at 09 45 28](https://user-images.githubusercontent.com/73988417/98461894-e7f85a00-21a7-11eb-8e55-c0d2e7a03fb1.png)

However, and sorry if I am overlooking something simple here, but I cannot get the sanitizer working either.  I enter the calendar URL in the ICS Url field, select 'scramble' for event titles and descriptions.  But, when I click 'Update' it just says 'Working...' and doesn't do anything else.  I've tried a number of times, but it never seems to progress past this.  I assume it is supposed to generate a compressed file that I can then send to you?

**Comment by jonas0b1011001** [comment]
The tool probably uses the same parser as the sync script and therefore has the same error processing your file.

Seems like there is a new line somewhere in the file that is not supposed to be there.
The error message states it is encountering the error while parsing "Bracknell", might that be the location of one of the events?

Please try syncing your calendars using [this version](https://script.google.com/d/1OEk9McqgsQ8UQeybvRfvvx6IbORexFRzSW7c2sxTfBV5v0rTnDrSWa0A/edit?usp=sharing) of the script, this should simply ignore the faulty line(s) instead of throwing an error.

**Comment by michaelh82** [comment]
Yeah, I assumed the same thing and yes, "Bracknell" would be a location of one of the events at some point in the past.

Great news though...that dev version of the script worked perfectly.  I have run a number of tests on all the calendars and everything is now syncing perfectly.

I will close this thread now, but thanks for taking the time to help with this...greatly appreciated.
