### ISSUE TITLE
(Personal request) I would like to edit the code so that "removeEventsFromCalendar" is true for events in the future and false for past events, could someone point me in the right direction?

### ISSUE THREAD

**Issue by philhzss** [derekantrican/GAS-ICS-Sync#168]
Hi,
Really love your script! I've been using it for months and it's wonderful. I'm using it to track my work schedule which is auto-updated by my employer, and I leave  `removeEventsFromCalendar` on false because my employer's auto-updating calendar removes events that are older than one month and I like to keep the historic.

Ran into a small issue today, where I thought I was working but I wasn't, my shift today was cancelled and it never got removed from my calendar because `removeEventsFromCalendar` was set to false! I 100% know this is intended/my fault, but since I have a tiny bit of programming experience, I thought I could try to tweak the code myself to achieve what I'd like, which is to have `removeEventsFromCalendar` false for past events (so I can keep my shift history like I want), but to have it true for future events, so if an upcoming shift is deleted, I can see that change reflected!

I have `modifyExistingEvents` set to true, which is great because future shift changes are always reflected. But future shift deletions are (obviously) not with my current settings.

I tried to tweak the code myself, but I don't think I'm good enough at this to figure out how to do it. I don't want to ask you guys to implement it as it's probably not a common request and it's just for me, but could you give me a little hint to what I could change to make this work?

Thanks a lot for your time and for the script!

**Comment by jonas0b1011001** [comment]
Does [this](https://github.com/derekantrican/GAS-ICS-Sync/issues/117) help?

**Comment by philhzss** [comment]
Oh wow, yes exactly!! I just followed your instructions [here](https://github.com/derekantrican/GAS-ICS-Sync/issues/109#issuecomment-598863265) and ran the script, it did exactly what I want it to do. Thank you!!!

I was messing around in the code for half an hour earlier but didn't think to search the issues, which I should've done before posting. Thanks a lot for the quick reply and for helping me get this to work!!!
