### ISSUE TITLE
"GoogleJsonResponseException: API call to calendar.events.insert failed with error: You need to have writer access to this calendar."

### ISSUE THREAD

**Issue by jblac** [derekantrican/GAS-ICS-Sync#169]
I have a calendar, originally it was a subscribed calendar to the ICS - but I renamed that and created a new Calendar.  

No matter what, the script is giving me the "You need to have writer access";   I have verified that my google account can indeed add events to the calendar, so it does in fact have writer access (it better, since I created the calendar)

I can't give the ICS url as the calendar does contain some personal identifiable information, but i'll try anything at this point - the following is our config, with a modified ical link

```
var sourceCalendars = [ 
  ["https://ourapp.com/reservations/subscribe/ical.ics?id=2022786&key=2fdb7bca1384b89d193172a443b118a2", "Our App"]
 
];

var howFrequent = 15;                  // What interval (minutes) to run this script on to check for new events
var onlyFutureEvents = true;          // If you turn this to "true", past events will not be synced (this will also removed past events from the target calendar if removeEventsFromCalendar is true)
var addEventsToCalendar = true;        // If you turn this to "false", you can check the log (View > Logs) to make sure your events are being read correctly before turning this on
var modifyExistingEvents = true;       // If you turn this to "false", any event in the feed that was modified after being added to the calendar will not update
var removeEventsFromCalendar = true;   // If you turn this to "true", any event created by the script that is not found in the feed will be removed.
var addAlerts = true;                  // Whether to add the ics/ical alerts as notifications on the Google Calendar events, this will override the standard reminders specified by the target calendar.
var addOrganizerToTitle = false;       // Whether to prefix the event name with the event organiser for further clarity
var descriptionAsTitles = false;       // Whether to use the ics/ical descriptions as titles (true) or to use the normal titles as titles (false)
var addCalToTitle = false;             // Whether to add the source calendar to title
var addAttendees = false;              // Whether to add the attendee list. If true, duplicate events will be automatically added to the attendees' calendar.
var defaultAllDayReminder = -1;        // Default reminder for all day events in minutes before the day of the event (-1 = no reminder, the value has to be between 0 and 40320)
                                       // See https://github.com/derekantrican/GAS-ICS-Sync/issues/75 for why this is neccessary.
var addTasks = false;

var emailSummary = false;              // Will email you when an event is added/modified/removed to your calendar
var email = "";    
```

So some things I've tried:
- creating the calendar myself, this did not work
- allowing the script to create the calendar, it doesn't seem to do this

**Comment by derekantrican** [comment]
Can you send a screenshot of your calendar list in Google calendar?

**Comment by jblac** [comment]
<img width="224" alt="Screen Shot 2020-11-27 at 3 48 39 PM" src="https://user-images.githubusercontent.com/2293514/100489262-1d69d680-30c8-11eb-8b2d-0f4a21bd8d1a.png">
Right now this is the list, This was after deleting the "Our App" calendar, and running "startSync" to have it do what it does and see if it created a calendar.   Which it did not.

**Comment by derekantrican** [comment]
Is there a chance that the Google calendar you're looking at and the account you're running the script with are two different accounts? Do you have multiple accounts linked?

**Comment by jblac** [comment]
I had thought of that, so before I set anything up I signed out of all of my google accounts and into just the one account.

**Comment by jonas0b1011001** [comment]
Hi,

changing a calendar's name will not actually change the calendar's _summary_ property but create a _summaryOverride_ property with the new name. As the script is only comparing calendar.summary it still uses the original name and thinks the subscribed calendar is the one to use.

If you want to keep the subscribed calendar in your account you can replace Helpers.gs [line 111](https://github.com/derekantrican/GAS-ICS-Sync/blob/4aafac9c8dcff167f813d22b6ff3cff0ee9bfc83/Helpers.gs#L111) to look like this:

```
var targetCalendar = Calendar.CalendarList.list().items.filter(function(cal) {
  var name = cal.summaryOverride || cal.summary;
  return name == targetCalendarName && cal.accessRole == "owner";
})[0];
```

**Comment by jblac** [comment]
Eventually we'll be getting rid of the subscribed calendar, what you say makes absolute sense and thanks for that tidbit of information!   With that, I think i'll be able to get this thing going - I'll work on it in the morning and update this issue one way or the other.

**Comment by jblac** [comment]
Update: Changing the calendar name to something new and unique worked a dream.   Thanks for the assistance and thanks @jonas0b1011001 for the information that got us over the finish line.
