### ISSUE TITLE
Filter out meetings with status tentative

### ISSUE THREAD

**Issue by desmi** [derekantrican/GAS-ICS-Sync#170]
My office schedules a lot of meetings that are more general reminders for optional things you can attend, all these meetings are now in my Google Calendar because I never declined the invitation.

If its possible it would be nice to be able to skip these kind of events when syncing.

**Comment by jonas0b1011001** [comment]
You can filter them by adding
```
result = result.filter(function(event){
    return !(event.hasProperty(('x-microsoft-cdo-busystatus')) && event.getFirstPropertyValue('x-microsoft-cdo-busystatus').toString() == "TENTATIVE");
  });
```
to [this](https://github.com/derekantrican/GAS-ICS-Sync/blob/4aafac9c8dcff167f813d22b6ff3cff0ee9bfc83/Helpers.gs#L181) part of the code.

**Comment by desmi** [comment]
Thank you so much!! :+1:
