### ISSUE TITLE
X-APPLE-STRUCTURED-LOCATION breaks the ics parser

### ISSUE THREAD

**Issue by mikz** [derekantrican/GAS-ICS-Sync#171]
I'm importing events from iCloud and they have some metadata like:
```
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-ABUID=Domov;X-APPLE-REFERENCEFRAME=1;X-APPLE-MAPKIT-HANDLE=CAES6AEI2TIaEgkzsrNlEgRJQBGEt+MLY8AsQCJzChHEjGVza8OhIHJlcHVibGlrYRICQ1oaFEhsYXZuw60gbcSbc3RvIFByYWhhKgVQcmFoYTIFUHJhaGE6BjE1MiAwMEIHUHJhaGEgNVIJSMO2Z2Vyb3ZhWgIxM2IMSMO2Z2Vyb3ZhIDEzigEHUHJhaGEgNSoMSMO2Z2Vyb3ZhIDEzMgxIw7ZnZXJvdmEgMTMyDDE1MiAwMCBQcmFoYTIRxIxlc2vDoSByZXB1Ymxpa2E4OUABWhkKFxISCTOys2USBElAEYS34wtjwCxAGNky;X-TITLE=Domov:nHögerova 13
15200 Praha
```

Which crashes the parser in `Function.ICAL.parse.parser._handleContentLine (ical.js:1938:13)`

**Comment by jonas0b1011001** [comment]
Please have a look at #162, seems to be the same issue.

**Comment by mikz** [comment]
Yep. I could not find it by searching for the function name, that has the parse error. Only one I found is https://github.com/derekantrican/GAS-ICS-Sync/issues/108 which is similar, but still a bit different.

Anyway, I fixed it for myself by ignoring that entry. Which is fine for me and my case.

Could you point to a commit where you fixed it for the dev branch? I can't see anything relevant between dev and master branch.

**Comment by jonas0b1011001** [comment]
> Could you point to a commit where you fixed it for the dev branch? I can't see anything relevant between dev and master branch.

This actually is not on github yet. This [ParserError](https://github.com/derekantrican/GAS-ICS-Sync/blob/4aafac9c8dcff167f813d22b6ff3cff0ee9bfc83/ical.js.gs#L1926) was replaced with a log entry.

**Comment by derekantrican** [comment]
Going to close this for now since the user is unblocked. We can talk about adding in an actual code change later
