### ISSUE TITLE
Support calendars where events don't have UID properties

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/GAS-ICS-Sync#173]
@jonas0b1011001 has [this](https://script.google.com/d/1IZhiJ6oHOSQTKAcMR2O4lqQqKUkyV6Uvi1uVjGR6WsEQgCqUUye3C_53/edit?usp=sharing) workaround script that can do this - just need to make a PR for the changes

**Comment by bjliu** [comment]
Was the PR ever made?

**Comment by jonas0b1011001** [comment]
Yes, v5.6 has this #188
