### ISSUE TITLE
Instructions don't work with the new code editor

### ISSUE THREAD

**Issue by edent** [derekantrican/GAS-ICS-Sync#174]
## Description of the problem

There is no "File" menu, nor a "Run" menu. I needed to switch back to legacy view in order to get things running.

Would it be better to update the instructions for the new layout, or tell people how to switch back?

## Screenshots
![Screenshot from 2020-12-22 15-14-23](https://user-images.githubusercontent.com/837136/102904127-30728b00-4469-11eb-91f2-17da59a41f51.png)

**Comment by derekantrican** [comment]
Thanks for brining this to my attention - I had no idea the code editor was updated, but it's been a long time coming. I'll look to create some update instructions

**Comment by edent** [comment]
No worries - it is a brilliant script and has saved me a lot of time. Thank you!

**Comment by derekantrican** [comment]
You're welcome! It doesn't seem that I have the new IDE yet, but here's an overview of the new one if you're interested: https://www.benlcollins.com/apps-script/google-apps-script-ide/

**Comment by dao-gh** [comment]
The easiest way in the new interface is to go to the Overview page and click on the "Make a Copy" icon (two overlapping pages on the top right).
 You can also go through the manual steps but it's more involved and required enabling showing the manifest file on the settings page.

**Comment by derekantrican** [comment]
I finally have the new IDE so I updated the instructions for the new IDE
