### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by xbunsenx** [derekantrican/GAS-ICS-Sync#175]
Let me start by saying I love this script! I am running it on three accounts. Two without any issues using version 5.4. One of the accounts is having duplication issues using version 5.5. I don't know if the version has anything to do with it though, but I don't want to change from 5.4 to 5.5 without knowing what the issue is.

The log on the other two accounts shows it skipping unchanged events whereas the one account is not and adds all of the events in and tries to delete the duplicates but hits a `GoogleJsonResponseException: API call to calendar.events.delete failed with error: Rate Limit Exceeded` error. Also, the two accounts running 5.4 have two triggers, one install and one startsync. The problem account running 5.5 has two startsync triggers. After the script runs the first time, one of the triggers is disabled. I have uninstalled the script and installed it back and it still gives the same results. Please let me know if you need additional information.

The source ICS link is [http://tmweb.troopmaster.com/activitymanagement/icalendar/?id=wQOROQ~Oj&timezone=eastern_standard_time](url)

![Screenshot 2020-12-24 102234](https://user-images.githubusercontent.com/76563522/103096487-0ab4c580-45d2-11eb-8cbb-f1a859c388fe.png)

![Screenshot 2020-12-24 102812](https://user-images.githubusercontent.com/76563522/103096685-c1b14100-45d2-11eb-90e0-7ddb941970f6.png)

**Comment by jonas0b1011001** [comment]
This has nothing to do with 5.5, the calendar you linked changes the events' ids everytime you open it. Therefore the script can not match existing events to new events it just pulled from the link..

I will have a look at the rate limit while removing events.

**Comment by xbunsenx** [comment]
I made those edits and they look like they are working. There were 3 or 4 of each of the events and when the script was triggered, it cleaned everything up. I will keep an eye on it and report if I it happens again.

I would like to thank you again for developing this script, it is exactly what we needed.

**Comment by derekantrican** [comment]
Great! You're welcome!
