### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by Rouzax** [derekantrican/GAS-ICS-Sync#176]
First of all thank you for this, it works great!

Do have three questions not so much a bug and I couldn't find it in the Wiki.
If I sync calendar entries from an ics url, can I change anything there (add additional description, location, etc) in the calendar entries that are being created in Google Calendar? Or will it be overwritten again with the next sync?
As far as I can see it will not overwrite and will only recreate the entry if I delete it entirely. So any changes I make to the entry in Google Calendar should stay there. I understand it will not sync back since it is one way.

The other is if you update the github code, how do I make sure I can update the project I created?

Last is can I sync multiple different ics calendars into a single Google Calendar?

**Comment by jonas0b1011001** [comment]
Hi, manual changes will persist as long as the corresponding event in your source calendar does not change. Once the event gets updated it will completely replace the previous version and therefore override all changes you might have done.

There is no auto-update feature, if a new version is released there will always be an updated link to the script which you can copy to your Google Drive. So it's basically: uninstall old version, make a copy of the new version, copy settings from old to new, install new version, delete old version.

You can merge multiple calendars into a single Google calendar by choosing the same target calendar name for each of your ics links.

**Comment by derekantrican** [comment]
To add to this: while there is no auto-update feature, you can subscribe to notifications for new versions by setting `var emailSummary = true;` and `var email` to your email address (eg `var email = "test@test.com";`). With that the script will email you if there is a version released that is greater than your current version

**Comment by derekantrican** [comment]
Hopefully that answers your questions - if you need clarification on any points feel free to add another comment to this issue

**Comment by Rouzax** [comment]
Thank you for all the answers, it is perfectly clear.
