### ISSUE TITLE
Change default visibility?

### ISSUE THREAD

**Issue by edent** [derekantrican/GAS-ICS-Sync#181]
- Please describe the feature you would like to see (it would be helpful if you could add any necessary screenshots, [ics strings](https://github.com/derekantrican/GAS-ICS-Sync/wiki/Debugging-tips#using-an-explicit-ics-string-instead-of-an-url), etc)

When items are added, they are given the visibility of "Public" - there is no way to change this in the script.

This causes a problem. I share my calendar externally. My default visibility doesn't allow external users to see my meeting details. But they can see the details of events added by this script

This is what my calendar looks like - one event has been imported by this script.

![View of my calendar](https://user-images.githubusercontent.com/837136/105172394-762d7c80-5b17-11eb-80cf-2559d75300c1.png)

When I look at the event in my private calendar view, it says it is public.
![Screenshot showing event is public.](https://user-images.githubusercontent.com/837136/105172379-73328c00-5b17-11eb-957a-51e32eecb546.png)

If I edit it, I can change it back to default visibility.
![Screenshot of toggle selection.](https://user-images.githubusercontent.com/837136/105172378-7299f580-5b17-11eb-8100-6ca946a9739f.png)

The access permissions for my calendar are set to "see only free/busy"
![Screenshot of Google settings.](https://user-images.githubusercontent.com/837136/105177608-cf4cde80-5b1e-11eb-9732-741ace77a3ad.png)

But this can be overridden if the event is set to public. As per Google's documentation https://support.google.com/calendar/answer/34580?hl=en#zippy=%2Ci-made-my-calendar-public-people-can-see-only-freebusy

I think the issue is caused by this line of code

https://github.com/derekantrican/GAS-ICS-Sync/blob/ada4567ac1fb543688f2e36eee588993253257d5/Helpers.gs#L358

To be fair, the imported ICS file I have says `CLASS:PUBLIC` in it.

So, I guess I want to either have a setting in the script to override that?

(Or should I just edit my Helpers.gs to always be "Default"?)

**Comment by derekantrican** [comment]
Yes, that is the correct line. As you might notice by that line and the few following lines, the basic premise is thus:

- If the ICS event has a visibility set (the `class` property) then that is what will be set for the Google Calendar Event
- Otherwise, nothing will be set, meaning that the event should default to the Google Calendar's default visibility

I am also in the same boat - where my ICS calendar has the `class` property for all events set to "public" but I want the events to use the calendar default. So I have simply changed the line `newEvent.visibility = classString;` to `newEvent.visibility = "default";`

**Comment by edent** [comment]
Aha, that's what I've done.

Would you like a PR to include:

```js
var defaultVisibility = ""; // /OPTIONAL: if "default" then new events are added with your default visibility, 
// if "public" then new events are added as public,
// if "" then new events are added with the ICS's stated visibility
```

Or is that a bit too niche?

**Comment by derekantrican** [comment]
For now, let's say it's too niche. If someone else asks about it then we'll include it

**Comment by qzdl** [comment]
Just hit this use-case too, I would happy to make a PR if you've changed your mind @derekantrican

**Comment by derekantrican** [comment]
Sure, go ahead and create a PR

**Comment by jonas0b1011001** [comment]
Is this covered by #201?

**Comment by derekantrican** [comment]
Looks like that would cover it (though there would be a few comments I would add). That guy created a bunch of PRs the other day and I still have to go through them.

**Comment by qzdl** [comment]
@jonas0b1011001 actually yeah, that covers the functionality on new events, but won't "migrate" events that exist already
