### ISSUE TITLE
Loosing authentication to access Google account

### ISSUE THREAD

**Issue by Rouzax** [derekantrican/GAS-ICS-Sync#182]
It seems that after some time it looses the authentication to the Google Account and is not allowed to run any more.
Running latest 5.5 version
Didn't notice it soon enough so there is no log information any more.

After installing the project again and giving it access to Google account it will run again.

Is there anything I need to check or do to make sure I can debug this?

**Comment by derekantrican** [comment]
> It seems that after some time it looses the authentication to the Google Account and is not allowed to run any more

This doesn't make much sense to me. Could you share any errors you're seeing? We've seen issues where project triggers stop "retriggering" due to how we previously did iterations so that may be what's going on here

**Comment by Rouzax** [comment]
There were no errors, that I could see. Not sure how long it didn't run but all the logs were empty
