### ISSUE TITLE
Only sync x days of past events

### ISSUE THREAD

**Issue by xbunsenx** [derekantrican/GAS-ICS-Sync#183]
If possible, could an option be added to sync past events but only a specified amount of days in the past like 90 days. One of the ics links I am syncing has to add all events to the calendar and then delete all events due to the event ID changes every time. I would like to see some past events but I don't necessarily need to see the full history of the parent calendar on my website. I have to set the sync frequency to 30 minutes, otherwise I get duplicates that remain after the execution is completed. I am thinking that if the past events are minimized, I can still show some history but reduce the amount of events the script needs to process. This is a new calendar that doesn't have loads of past events, but it will grow as time goes on.

If it is not possible, I understand.

**Comment by jonas0b1011001** [comment]
Just change [this](https://github.com/derekantrican/GAS-ICS-Sync/blob/ada4567ac1fb543688f2e36eee588993253257d5/Code.gs#L126) loc to

`startUpdateTime = new ICAL.Time.fromJSDate(new Date()).adjust(-90,0,0,0);`

and run the script with

`onlyFutureEvents = true;`

**Comment by xbunsenx** [comment]
Thank you, that worked perfectly!
