### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by elshobokshy** [derekantrican/GAS-ICS-Sync#184]
Useless issue for most, but important to my eyes nonetheless. I would like to take a minute to show my gratitude for creating such a helpful script. Thank you for the time you put into creating this and saving lots of time for others. You, sir, deserve a medal.

So thank you!

**Comment by derekantrican** [comment]
@elshobokshy Thank you for the kind words! Definitely glad our program could help you. I don't know if we deserve a medal, but if you'd like to show some support you can spread the word about our program or donate to support here: https://www.paypal.com/donate/?cmd=_donations&business=jonas0b1011001@icloud.com&item_name=GAS-ICS-Sync&currency_code=EUR&bn=PP%2dDonationsBF&Z3JncnB0=
