### ISSUE TITLE
Two calendars cause replication issues

### ISSUE THREAD

**Issue by joey4247** [derekantrican/GAS-ICS-Sync#185]
Hey there,

I'm using the latest version of the script. Sometimes, events from one calendar are (again, only sometimes) duplicated multiple times into another calendar I've got setup in the script.

![image](https://user-images.githubusercontent.com/70319311/107495546-840f7400-6b90-11eb-9b7a-8f4ee21a16ac.png)

In the example above, the yellow is the 'true' calendar that the script should write this event to, and the orange is a secondary calendar which the event should not appear in at all.

This doesn't happen for every event. I thought it could perhaps be data from the MS Teams invite/join link that was causing an error but it also happens in events which do not have a teams invite.

![image](https://user-images.githubusercontent.com/70319311/107495798-d5b7fe80-6b90-11eb-8743-760220716db7.png)

Let me know if you'd like a sanitised export of both calendars or any other data.

**Comment by derekantrican** [comment]
@joey4247 I'd like a copy of your settings in the script (feel free to replace the calendar url "https://......ics" with something like "A.ics" if you are concerned about privacy). I'm also interested in a screenshot of your calendars in the left-hand pane of Google Calendar, if you're willing to share one

**Comment by joey4247** [comment]
@derekantrican Sure thing!

Settings attached as txt, anonymised
[settings.txt](https://github.com/derekantrican/GAS-ICS-Sync/files/5959609/settings.txt)
Calendar screengrab:
![image](https://user-images.githubusercontent.com/70319311/107537296-057ffa00-6bc3-11eb-9fa0-e5e4521a4b49.png)

**Comment by derekantrican** [comment]
*I updated your comment to expand out the settings.txt*

Thanks for that info. 

> In the example above, the yellow is the 'true' calendar that the script should write this event to, and the orange is a secondary calendar which the event should not appear in at all.

Looks like you're syncing to both the orange and yellow calendars - which is why the event is appearing in both. Is that what you intended? Maybe I'm misunderstanding?

**Comment by joey4247** [comment]
> Looks like you're syncing to both the orange and yellow calendars - which is why the event is appearing in both. Is that what you intended? Maybe I'm misunderstanding?
> 
> If you don't want events in the orange calendar, remove this line from the script: `["https://outlook.office365.com/xxxx/calendar.ics", "SSH RA"]` (and the comma on the end of the line before)

Hallo, no - to anonymise, I replaced the string between .com/ and /calendar.ics with the same block (xxxx) - These come from completely different Office 365 domains. That's also why not every event is duplicated, because they don't pull from the same ICS feed.

If they were pulling the same feed, I'd expect the calendars to be exactly duplicated. This is just one odd event in a few that is correctly entered once in the yellow feed (UU Studenten), then entered three times in the orange feed (SSH RA) erroneously. Examples already given above.

**Comment by derekantrican** [comment]
Thanks for the clarification. Is there any chance the events are also duplicated on your outlook calendars? I really doubt there is any "cross contamination" happening between two different calendars in the script

**Comment by joey4247** [comment]
@derekantrican Hey, no. The second calendar has never been invited to this event. It's serves a completely different purpose for a different job. As in one of the previous comments, it's not even possible for it to be a declined event. (most of the events that duplicate are sent to a closed exchange group) So it does seem the script is causing the issue.

**Comment by derekantrican** [comment]
In that case, please share the contents of each ics (you can hide personal information if you wish using https://derekantrican.github.io/icssanitizer.html)

**Comment by joey4247** [comment]
@derekantrican Hey, sorry for the delay.

I can't get your tool to sanitise the ICS files. Both return the same error
![image](https://user-images.githubusercontent.com/70319311/108250752-e64f1280-7156-11eb-8522-83a59358051e.png)

I have checked the logs and they are pulling fine into the script?

**Comment by derekantrican** [comment]
Gotcha. I may have to update the tool and the proxy server that it uses

**Comment by derekantrican** [comment]
You can always put you calendar into the address bar and save it to your computer, then open it in notepad and use find-and-replace to remove sensitive information. Notepad alternatives like notepad++ and VS Code will make this easier

**Comment by derekantrican** [comment]
Ah looks like the CORS proxy service that I used just started limiting access (https://github.com/Rob--W/cors-anywhere/issues/301) I'll have to find another

**Comment by derekantrican** [comment]
@joey4247 I've updated the CORS proxy on https://derekantrican.com/icssanitizer.html - go ahead and give it another try

**Comment by joey4247** [comment]
@derekantrican That was quick! Thank you.

UU Studenten (cal 1) - https://pastebin.com/PVS0zQRi
SSH RA (cal 2) - https://pastebin.com/7KUdxhGj

**Comment by jonas0b1011001** [comment]
I don't see anything wrong with neither your setup nor the calendars you are syncing.

I guess we would need the log output from one of the runs that created a duplicate to actually see what was going wrong. Logs are only available for the last 7 days though, have you noticed any new duplicates in the past week?

**Comment by joey4247** [comment]
Hey, sorry for the delay. I've noticed an event which is replicated but I can't tell when it synced. It appears new.
What I can do is remove it and re-add it, if it duplicates then I will capture the logs at the known time and send them on.

**Comment by joey4247** [comment]
Yep, it's still occurring. It appears to tie to recurring events mostly. Interestingly it doesn't delete the second event.
![image](https://user-images.githubusercontent.com/70319311/108738950-69e07900-7534-11eb-9c4b-5f0acae5b8f8.png)

This was changed at 17:12, so here are the logs after that. In the log from 17:19:30 there's an interesting entry at the end for @esri.com which is the same as the event that has been duplicated.

[logs_22022021_17-19-30.txt](https://github.com/derekantrican/GAS-ICS-Sync/files/6023581/logs_22022021_17-19-30.txt)
[logs_22022021_17-29-30.txt](https://github.com/derekantrican/GAS-ICS-Sync/files/6023582/logs_22022021_17-29-30.txt)
[logs_22022021_17-39-40.txt](https://github.com/derekantrican/GAS-ICS-Sync/files/6023580/logs_22022021_17-39-40.txt)

**Comment by joey4247** [comment]
I think I've found the issue. The event was a recurring series but the event that was duplicating was a non-recurring event in the series (i.e. modified time). I've removed the non-recurring event and set them all to the same, now it's fine

Workaround for now but seems to be a quirk of how it processes events where they're in a series but changed.
![image](https://user-images.githubusercontent.com/70319311/108740923-782f9480-7536-11eb-92ce-affc86a55e50.png)

**Comment by derekantrican** [comment]
Interesting. I still don't know if that explains why it was on two different calendars. @jonas0b1011001 does that make any sense to you?

**Comment by jonas0b1011001** [comment]
The recurrence exceptions array is not cleared after processing a target calendar. That's why the exception from source1 was also processed as if it was part of source2. That's actually fixed by [this](https://github.com/derekantrican/GAS-ICS-Sync/commit/021bd2466f560b78ec3c10ecf277393ad3514e69) commit.

You can either manually copy the latest code from the repo or wait for the next release with the fix included :)

(changing the order in your _var sourceCalendars_ would also work around the issue)

**Comment by derekantrican** [comment]
Thanks for the input - I was not aware of that (or maybe: I didn't remember it). @joey4247 can you try copying the latest version of the code according to https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually? Let us know if you have questions

**Comment by joey4247** [comment]
@derekantrican thank you for your input and that of @jonas0b1011001 too. Really appreciate the help.
I've copied over the code and will give it a go!

**Comment by joey4247** [comment]
@derekantrican It seems resolved, have tried editing occurrences of recurring events and the error hasn't so far replicated. Thanks for your help and that of @jonas0b1011001 - as always, most appreciated.
