### ISSUE TITLE
Error: invalid date-time value

### ISSUE THREAD

**Issue by lyonsupe1** [derekantrican/GAS-ICS-Sync#186]
I started running the script without issue on the 12th, but looking back at the logs it seems that starting yesterday afternoon every execution has failed with the same error (though yesterday the error was 2021-02-13). Had no trouble syncing everything initially, but I unsubscribed from the calendar and attempted a clean re-sync and don't get very far before it fails now.

Error: invalid date-time value: "2021-02-14"
    at ICAL.Time.fromDateTimeString(ical.js:5901:13)
    at decorate(ical.js:781:28)
    at _decorate(ical.js:2939:47)
    at _setDecoratedValue(ical.js:2973:36)
    at setValue(ical.js:3154:14)
    at addPropertyWithValue(ical.js:2684:12)
    at checkSkipEvent(Helpers:477:29)
    at createEvent(Helpers:251:27)
    at processEvent(Helpers:193:18)
    at [unknown function](Code:176:9)

"webcal://p64-caldav.icloud.com/published/2/MTcwOTMxMDQ3MTcwOTMxMNVbxK5VCH8l7F0f06CdvWf2Ek8A0ueM-FhG-3j4GosGfnIlk9B3gvRPkpfbptigVlfG5PsEkkg3EvT5zyCG2Jw" is the calendar link I am using

**Comment by jonas0b1011001** [comment]
Open your copy of the script, in ical.js change the value in [line 1323](https://github.com/derekantrican/GAS-ICS-Sync/blob/02769137a225360e852ef084af2b59ae8737cc01/ical.js.gs#L1323) to `false`

**Comment by lyonsupe1** [comment]
> Open your copy of the script, in ical.js change the value in [line 1323](https://github.com/derekantrican/GAS-ICS-Sync/blob/02769137a225360e852ef084af2b59ae8737cc01/ical.js.gs#L1323) to `false`

Easy fix and works perfect again. Thanks!
