### ISSUE TITLE
How to not exclude past recurring instances?

### ISSUE THREAD

**Issue by khanhtn1** [derekantrican/GAS-ICS-Sync#187]
Right now the script removes past instances of a recurring icalEvent with at least one instance is in the future (this code [here](https://github.com/derekantrican/GAS-ICS-Sync/blob/master/Helpers.gs#L459) I think)
I want to not do that, just remove the recurring event if all instances are in the past. How would I do that, if possible? I commented out the body of the if but that is wrong (the event becomes all-day spreading from startDate to endDate) 

Thank you

PS: same file, line [456](https://github.com/derekantrican/GAS-ICS-Sync/blob/master/Helpers.gs#L456) and [457](https://github.com/derekantrican/GAS-ICS-Sync/blob/master/Helpers.gs#L457) seem useless - loading and then storing same value?

**Comment by jonas0b1011001** [comment]
In the settings part set `var onlyFutureEvents` to `false` and past events/instances will not be removed.

> PS: same file, line 456 and 457 seem useless - loading and then storing same value?

I'll have a look at that, might be left over previous code.
