### ISSUE TITLE
DNS error

### ISSUE THREAD

**Issue by pjh22** [derekantrican/GAS-ICS-Sync#189]
Hi,

I'm new to Google Script and just can't get this to work (sync my Quire calendar with my Google calendar).  Here's what I did,
1. Created a calendar in Google Calendar called 'Quire' (and made sure it's ticked/visible)
2. Copied the script as per your instructions and inserted my Quire calendar so that line 19 looks like this:
var sourceCalendars = ["https://quire.io/r/ical/zywjQAfvcv-mdeK7tY5gleli", "Quire"];
3. I left everything else as default and clicked Run/Install.  The log said,
5:50:59 PM	Notice	Execution started
5:50:59 PM	Info	Intended frequency = 15, Adjusted frequency = 15
5:51:00 PM	Notice	Execution completed
4. I'd created a few dummy tasks with dates but none appeared in Google Calendar
5. I then tried Run/startSync and got this
5:52:42 PM	Notice	Execution started
5:52:42 PM	Info	Error, Retrying...Exception: DNS error: http://h
5:52:42 PM	Info	Error, Retrying...Exception: DNS error: http://h
5:52:42 PM	Info	Error, Retrying...Exception: DNS error: http://h
5:52:42 PM	Info	Syncing 0 calendars to t
5:52:43 PM	Info	Working on calendar: c_g939vh73pnvkdrov45gpmin1ao@group.calendar.google.com
5:52:43 PM	Info	Fetched 0 existing events from t
5:52:43 PM	Info	Parsed 0 events from ical sources
5:52:43 PM	Info	Processing 0 events
5:52:43 PM	Info	Done processing events
5:52:43 PM	Info	Checking 0 events for removal
5:52:43 PM	Info	Done checking events for removal
5:52:43 PM	Info	Processing 0 Recurrence Instances!
5:52:43 PM	Info	Error, Retrying...Exception: DNS error: http://Q
5:52:44 PM	Info	Error, Retrying...Exception: DNS error: http://Q
5:52:44 PM	Info	Error, Retrying...Exception: DNS error: http://Q
5:52:44 PM	Info	Syncing 0 calendars to u
5:52:44 PM	Info	Working on calendar: c_v86hnqd5tiaminv1ee4abbi0hg@group.calendar.google.com
5:52:45 PM	Info	Fetched 0 existing events from u
5:52:45 PM	Info	Parsed 0 events from ical sources
5:52:45 PM	Info	Processing 0 events
5:52:45 PM	Info	Done processing events
5:52:45 PM	Info	Checking 0 events for removal
5:52:45 PM	Info	Done checking events for removal
5:52:45 PM	Info	Processing 0 Recurrence Instances!
5:52:45 PM	Info	Sync finished!
5:52:45 PM	Notice	Execution completed
6. So, I now have new calendars called 't' and 'u' but nothing has synced to them or the calendar called Quire (all are ticked/visible).
7. My account is a Google Workspace account so I'm not sure if there could be permissions issues related to that?

Any help would be much appreciated.

**Comment by jonas0b1011001** [comment]
change line 19 to:
`var sourceCalendars = [["https://quire.io/r/ical/zywjQAfvcv-mdeK7tY5gleli", "Quire"]];`

**Comment by pjh22** [comment]
Fixed!  Thank you so much.
