### ISSUE TITLE
Trello calendar not found

### ISSUE THREAD

**Issue by AsucahMan** [derekantrican/GAS-ICS-Sync#190]
Hi! First of all I'm totally new to GitHub and Google Apps Script, so basically #I'veGotNoIdeaWhatI'mDoing

To cut to the chase, here's what I get when trying to sync [this](https://trello.com/calendar/5ba212fb75bb188928995c8e/5ba21300c3a5115cba395bd5/9e1daa1c8d078e13319c54a2fc8b0602.ics) Trello calendar.
![Google_calendar_script_bug_2](https://user-images.githubusercontent.com/80367564/110557523-0748c900-8141-11eb-91c6-0429b67547f0.png)

The .ics link works, and is downloadable. The script works with another (not from Trello) calendar.
Is there an issue specifically with Trello?

Thanks!

**Comment by derekantrican** [comment]
Seems to work fine for me. Can you give it another try?

**Comment by derekantrican** [comment]
Doublecheck your url. The one you have linked in the bug here (https://trello.com/calendar/5ba212fb75bb188928995c8e/5ba21300c3a5115cba395bd5/9e1daa1c8d078e13319c54a2fc8b0602.ics) is not the same as your screenshot

**Comment by AsucahMan** [comment]
> Doublecheck your url. The one you have linked in the bug here (https://trello.com/calendar/5ba212fb75bb188928995c8e/5ba21300c3a5115cba395bd5/9e1daa1c8d078e13319c54a2fc8b0602.ics) is not the same as your screenshot

Ooops... 😅  You're right, my bad; silly mistake. I had some other issues, but they had already been solved in the comments so now it works!

Sorry for wasting your time, and thanks a lot! The script is truly useful

I'm closing the issue; feel free to delete it, given it doesn't add much value
