### ISSUE TITLE
RangeError: Maximum call stack size exceeded (line 91, file "Code")

### ISSUE THREAD

**Issue by JoCTrem** [derekantrican/GAS-ICS-Sync#193]
After running the install, the error code in the title pops up. The line it is referring to is the "function install(){" line under the editing warning.
![image](https://user-images.githubusercontent.com/81369119/112480776-bba33b80-8d4c-11eb-82a1-c0c9497c9c88.png)
The only edits that have been made are the calendar linking and time increment.

**Comment by JoCTrem** [comment]
<img width="1391" alt="Screen Shot 2021-03-25 at 9 31 48 AM" src="https://user-images.githubusercontent.com/81369119/112481178-1e94d280-8d4d-11eb-9a75-bc45a0e2cdd7.png">
Just in case it would be useful to double check the user edited area

**Comment by derekantrican** [comment]
That's definitely odd. This is from running `install` manually?
