### ISSUE TITLE
Timezone Customized Time Zone unsupported!

### ISSUE THREAD

**Issue by mark213a** [derekantrican/GAS-ICS-Sync#194]
HI all - getting this message on every imported entry
Timezone Customized Time Zone unsupported!
It selects the correct one but has this all the time?
Its coming from Outlook
In Outlook it describes the timezone setting as (UTC +08:00 Perth)

Any issues?

------------
Apr 3, 2021, 6:40:45 AM	Info	Result: 1
Apr 3, 2021, 6:40:45 AM	Info	Syncing 1 calendars to [REDACTED]
Apr 3, 2021, 6:40:45 AM	Info	Creating Calendar: [REDACTED]
Apr 3, 2021, 6:40:46 AM	Info	Working on calendar: [REDACTED]@group.calendar.google.com
Apr 3, 2021, 6:40:46 AM	Info	Fetched 0 existing events from [REDACTED]
Apr 3, 2021, 6:40:46 AM	Info	Parsed 61 events from ical sources
Apr 3, 2021, 6:40:46 AM	Info	Processing 61 events
Apr 3, 2021, 6:40:46 AM	Info	Timezone Customized Time Zone unsupported!
Apr 3, 2021, 6:40:46 AM	Info	Using Timezone Australia/Perth!
Apr 3, 2021, 6:40:46 AM	Info	Adding new event 040000008200E00074C5B7101A82E008000000002A119FE96ED3D6010000000000000000100000002A5C31994DC60246837FE4949B814744

**Comment by jonas0b1011001** [comment]
> Any issues?

Kind of. Google only supports Timezones formatted as an IANA Time Zone Database name. As 'Customized Time Zone' quite obviously is not a standardized timezone identifier we have to _guess_ which timezone it is supposed to be.

If you have a look at [tzid.gs](https://github.com/derekantrican/GAS-ICS-Sync/blob/master/tzid.gs) you can see how this is done. `var tzids` holds a list of all timezone identifiers accepted by Google Calendar API and _tzidreplace_ matches timezone names usually used by outlook to those IANA names.
If we encounter a timezone name that is not supported ("Apr 3, 2021, 6:40:46 AM Info Timezone Customized Time Zone unsupported!") we try to replace it according to `tzidreplace`.
In your case the timezone can not be matched and the script is using the standard timezone set for your target calendar ("Apr 3, 2021, 6:40:46 AM Info Using Timezone Australia/Perth!").

**Comment by mark213a** [comment]
Thanks. Assume there's nothing in Outlook or in tzid.gs I can/ should change? Seems to run fine. Weird that they don't all use a standard list!

**Comment by jonas0b1011001** [comment]
You **could** add an entry to `tzidreplace` 
`"Customized Time Zone": "Australia/Perth"`

However there's no real need as it is already selecting the correct zone.

> Weird that they don't all use a standard list!

Outlook will use _random_ names in some cases, I don't know why.

**Comment by WhiteLupus** [comment]
And in My Calendar all the items are shown in winter time, because in my country we don't change times and the European time changed and all my meetings from Outlook were set by my European colleagues.....

**Comment by jonas0b1011001** [comment]
> And in My Calendar all the items are shown in winter time, because in my country we don't change times and the European time changed and all my meetings from Outlook were set by my European colleagues.....

@WhiteLupus Add an entry to `tzid.gs` as described above to force the script to use your colleagues' timezone.


> Thanks will try and see this suggestion to lower log count

This will produce the same log output, sorry

**Comment by WhiteLupus** [comment]
Thanks for the answers @jonas0b1011001 and @mark213a.

Can you please help me clarify?

My colleagues are from different parts of Europe and India, so they have different time zones.
And I am in Armenia.

I guess I should not put just "Customized Time Zone": "Australia/Perth"

But something that replaces India time or CET to Armenian time right?

Would you help me with the exact code lines replacement?

Thanks in advance

**Comment by jonas0b1011001** [comment]
> I guess I should not put just "Customized Time Zone": "Australia/Perth"
> 
> But something that replaces India time or CET to Armenian time right?

You have to add pairs that match the generic timezone name to the IANA name of that timezone.
So rather "Customized Time Zone 1": "India/X" or "Customized Time Zone 2": "Europe/Y"

To find the first part you have to either check the script's logs for entries stating "Timezone XYZ unsupported!" or open your *.ics in a text editor and check the events manually.
Assuming you have the same issue as discussed in this thread an event created by one of your colleagues (let's assume his local timezone is _Europe/Zurich_) should look like this:

> BEGIN:VEVENT
DTSTAMP:19980309T231000Z
DESCRIPTION:Project XYZ Review Meeting
CREATED:19980309T130000Z
SUMMARY:XYZ Project Review
DTSTART;TZID=**Customized Time Zone 1**:19980312T083000
DTEND;TZID=**Customized Time Zone 1**:19980312T093000
LOCATION:1CP Conference Room 4350
END:VEVENT

In that case one of your entries would be 
`"Customized Time Zone 1": "Europe/Zurich"`

As I don't know your ics I can not provide you the exact lines.

**Comment by WhiteLupus** [comment]
Here is an example of the event that was working fine but after the yearly time change, it is off by an hour now.

Sorry if I am reasking, but I still don't get the line I should set in tzid.gs.

Will be very thanksfull if you could help.


> X-MS-OLK-FORCEINSPECTOROPEN:TRUE
> BEGIN:VTIMEZONE
> TZID:Caucasus Standard Time
> BEGIN:STANDARD
> DTSTART:16010101T000000
> TZOFFSETFROM:+0400
> TZOFFSETTO:+0400
> END:STANDARD
> END:VTIMEZONE
> BEGIN:VTIMEZONE
> TZID:GMT Standard Time
> BEGIN:STANDARD
> DTSTART:16011028T020000
> RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
> TZOFFSETFROM:+0100
> TZOFFSETTO:-0000
> END:STANDARD
> BEGIN:DAYLIGHT
> DTSTART:16010325T010000
> RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
> TZOFFSETFROM:-0000
> TZOFFSETTO:+0100
> END:DAYLIGHT
> END:VTIMEZONE
> BEGIN:VEVENT
> 
> 
> 
> DTEND;TZID="GMT Standard Time":20210420T160000
> DTSTAMP:20210208T161959Z
> DTSTART;TZID="GMT Standard Time":20210420T150000
> LAST-MODIFIED:20210420T113250Z
> LOCATION:Microsoft Teams Meeting
> 
> 
> 
> RECURRENCE-ID;TZID="Caucasus Standard Time":20210420T180000
> SEQUENCE:0

**Comment by jonas0b1011001** [comment]
I would actually expect that event to sync properly.

What timezone are you in and when would you expect the event to show in your calendar?

**Comment by WhiteLupus** [comment]
I am in Yerevan (GMT+4).
And In my Outlook it's correctly set to Tue 6PM-7PM.

But through sync, i get it at 7PM-8PM in my Google calendar.

---------------------------------------------------------

From logs on StartSync, I see those messages:

> Timezone Z unsupported!
> Using Timezone Etc/GMT!
> 
> Timezone W. Europe Standard Time unsupported
> Using Timezone Europe/Berlin!
> 
> Timezone Caucasus Standard Time unsupported!
> Using Timezone Asia/Yerevan!
> 
> Timezone GMT Standard Time unsupported!
> Using Timezone Europe/London!

**Comment by jonas0b1011001** [comment]
> From logs on StartSync, I see those messages:

Looks fine to me.
When you edit the event in the google calendar web interface what time/timezone is it showing for that event?

**Comment by derekantrican** [comment]
I feel like we've seen a lot of concern over the "Timezone ______ unsupported!" log lines recently. Maybe because the log lines are now always visible in the new UI (at the bottom of the window ). I would suggest we change those lines to less aggressive wording. Something like "Converting ICAL timezone _____ to Google Calendar timezone ______" (or, if you want to be more specific, "Converting timezone _______ to IANA timezone ______")

**Comment by WhiteLupus** [comment]
Ok thanks for the hint on checking the timezones.

Seems I found the issue.

Seems that calendar sync crates several instances in my GCalendar.

I managed to manually remove the wrong ones (It's a hustle as there are a lot of overlapping meetings I get, and probably because of my company restrictions on Outlook giving away meeting details, the Calendar Sync only writes "Busy", "Tentative" or "Free" in my Google calendar, so it's a lot of Busyies which are hard to differentiate from one another).

Then, When I synced again, there are only two issues left.

1) There is a meeting created in timezone UTC +00:00 Dublin, Edinburgh, Lisbon, London
In my Outlook in my timezone it's 6pm-7pm.
However sync crates two instances of it. one at 6-7pm, other at 7-8pm.

2) Second is also created from the same guy at the same timezone for 2-3pm in my timezone.
And this one is being created on my Gcalendar at 3-4pm.

I tried deleting all instances and syncing again. But it didn't help.


Thanks for the help so far, is this something you can also help to clarify ?
Do you want me to open another thread for this ? Seems to be a timezone issue, so I put it here.

**Comment by WhiteLupus** [comment]
I have removed all instances of the one that was the correct one, and moved the ones created 1 hour later to by 1 hour (to earlier) for all instances.
Set the ModifyExistingEvents to False

Run it,

Seems all stayed alright.
Then set ModifyExistingEvents to Ture

Run it again.
It didn't move those 1 hour.

So it's solved.

Not sure how it's solved, but it's solved.

Thanks a lot for all the help.
Will let you know if that repeats.
