### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by xbunsenx** [derekantrican/GAS-ICS-Sync#195]
I am getting an error when the trigger is activated and the sync is not happening at all. If I manually run startSync, it works fine. I am currently using version 5.5.

**Error	We're sorry, the JavaScript engine reported an unexpected error. Error code INTERNAL.**

**Comment by derekantrican** [comment]
I think there was a short outage and issues with that today. Can you try again now (or - if the error still happens - trying again tomorrow)?

**Comment by xbunsenx** [comment]
OK, it does seem to be intermittent now that I am watching closer. It sometimes works and sometimes not. Thank you for your quick reply. As always, thank you for all your hard work with this project.

**Comment by derekantrican** [comment]
If you run the script on a automated basis long enough you'll realize Google services (and things like the javascript engine) have intermittent issues fairly frequently. Usually, it's just ignorable
