### ISSUE TITLE
All calendar items are deleted and re-added every iteration.

### ISSUE THREAD

**Issue by jamesmurdza** [derekantrican/GAS-ICS-Sync#212]
It's happened with every test I've done so far. I get the email notifications from Google Apps and from Google Calendar every 15 minutes showing that everything was deleted and re-added. Here's the ICS:
[prod.ics.txt](https://github.com/derekantrican/GAS-ICS-Sync/files/6570187/prod.ics.txt)

**Comment by jamesmurdza** [comment]
This is the log:

2:19:49 PM	Notice	Execution started
2:19:50 PM	Info	Result: 1
2:19:50 PM	Info	Syncing 1 calendars to Makerspace Delft Bookings
2:19:51 PM	Info	Working on calendar: c_1mcudufhdmo7hj6m0ts4t0d0po@group.calendar.google.com
2:19:51 PM	Info	Fetched 5 existing events from Makerspace Delft Bookings
2:19:51 PM	Info	Parsed 5 events from ical sources
2:19:51 PM	Info	Processing 5 events
2:19:51 PM	Info	Timezone Z unsupported!
2:19:51 PM	Info	Using Timezone Etc/GMT!
2:19:51 PM	Info	Adding new event 78fe8440-c8f3-45e7-8a5a-ae98442d5da5
2:19:51 PM	Info	Timezone Z unsupported!
2:19:51 PM	Info	Using Timezone Etc/GMT!
2:19:51 PM	Info	Adding new event b427979f-3d9a-4401-871f-7e8861239b6e
2:19:52 PM	Info	Timezone Z unsupported!
2:19:52 PM	Info	Using Timezone Etc/GMT!
2:19:52 PM	Info	Adding new event a773c470-706a-41fd-bd4c-600e829c00f4
2:19:52 PM	Info	Timezone Z unsupported!
2:19:52 PM	Info	Using Timezone Etc/GMT!
2:19:52 PM	Info	Adding new event 62493768-14dc-4df9-a0ba-8b72f675b620
2:19:53 PM	Info	Timezone Z unsupported!
2:19:53 PM	Info	Using Timezone Etc/GMT!
2:19:53 PM	Info	Adding new event 01c82ed7-5d6c-4c89-94f1-144544d5353c
2:19:53 PM	Info	Done processing events
2:19:53 PM	Info	Checking 5 events for removal
2:19:53 PM	Info	Deleting old event de32c17b-2c94-46ce-9077-3e1f045e52a5
2:19:53 PM	Info	Deleting old event 7a4a7eae-41a3-4b73-9ea4-6d325fe90453
2:19:54 PM	Info	Deleting old event f9eb234c-5c4b-4474-920e-5799f1e2ede7
2:19:54 PM	Info	Deleting old event 551484fd-4ea4-4af3-84be-ecad789fc7f7
2:19:55 PM	Info	Deleting old event 241005bd-8699-43f1-94a6-c7128be21092
2:19:55 PM	Info	Done checking events for removal
2:19:55 PM	Info	Processing 0 Recurrence Instances!
2:19:55 PM	Info	Sync finished!
2:19:56 PM	Notice	Execution completed

**Comment by derekantrican** [comment]
@jonas0b1011001 What if we were a bit more intelligent about our matching rather than just "find an already-existing event with the same UID"? If we don't find an event with the same UID, we could look for an event with all the same properties (everything except UID). If we find a match based on that, we could consider that a "match" (as long as we do some additional handling like two of the same event at the same time)

**Comment by jamesmurdza** [comment]
Hi @derekantrican, thanks for the reply. I should have realized that my issue was related to changing UIDs, but everything else staying the same, which is more of a bug with my software.

In my case, I can easily fix this by fixing the UIDs.

**Comment by jamesmurdza** [comment]
I am going to close this issue because I believe the bug was mine and your software is working properly.

**Comment by derekantrican** [comment]
Yes, our script is working properly and the source calendar provider should not change UIDs all the time but my comment was more for people who can't just fix their source calendar provider (eg Outlook is notorious for this)

**Comment by jonas0b1011001** [comment]
> @jonas0b1011001 What if we were a bit more intelligent about our matching rather than just "find an already-existing event with the same UID"? If we don't find an event with the same UID, we could look for an event with all the same properties (everything except UID). If we find a match based on that, we could consider that a "match" (as long as we do some additional handling like two of the same event at the same time)
> 
> If we manage to do this it could save a lot of headache (and runtime) for a lot of users.

We might do the same as with events that have no ID at all (remove UID property, and compare the MD5s). This has potential to break a lot of things though, especially recurrence related stuff.

**Comment by derekantrican** [comment]
> This has potential to break a lot of things though, especially recurrence related stuff.

For sure. I might have to think about this some more. Obviously Google calendar is handling it somehow (but of course they have the server capacity and computing power that isn't bound like ours is)
