### ISSUE TITLE
Exclude Private Appointments

### ISSUE THREAD

**Issue by ryancasler** [derekantrican/GAS-ICS-Sync#215]
Private Appointments only show up with the title of "Private Appointment".  It would be really useful to be able to use this to exclude event from synchronization with Google Calendar.  It seems like this would be really easy to setup when pulling events from O365 but I can't seem to figure out how to add it.   If not implemented completely, a little assistance on where I would need to add it would be great too.  Thanks so much for this.  It is SOOO much better than the native Google Calendar sync.

**Comment by derekantrican** [comment]
@ryancasler Can you share a vevent example? Is this specific to Outlook?

**Comment by thiagotra** [comment]
Here is what I did to exclude my appointments marked as Private on Outlook.

I took this Pull request: https://github.com/derekantrican/GAS-ICS-Sync/pull/279/files

and on the `var filters = [];`, add "Private Appointment" string.

So, everytime you mark an appointment in Outlook as Private (close the lock), this event will be ignored and therefore not synchronized with Google Calendar.

**Comment by ryancasler** [comment]
Thanks so much @thiagotra!   That's just what I was looking for!   Tried it and it works like a charm.
