### ISSUE TITLE
Mark canceled Outlook events as having status=cancelled.

### ISSUE THREAD

**Issue by rattrayalex** [derekantrican/GAS-ICS-Sync#218]
Events that are canceled in outlook do not use the "cancelled" status in iCal format, eg;
<img width="220" alt="Screen Shot 2021-06-18 at 10 10 23 AM" src="https://user-images.githubusercontent.com/704302/122574243-75910780-d01d-11eb-84c1-a2d9cd1fd003.png">
will have `STATUS:CONFIRMED` in the iCal event, so they show up like a normal event in Google Calendar:
<img width="197" alt="Screen Shot 2021-06-18 at 10 17 00 AM" src="https://user-images.githubusercontent.com/704302/122575279-960d9180-d01e-11eb-94db-b959c5ba2c1b.png">
which means they send notifications as if the event were still happening.

 However, the event's summary will be prefixed with the text `Canceled: `

~Additionally, it is possible that some event producers use the spelling "canceled" while Google Calendar requires the status to be spelled "cancelled" (both are valid english).~ (nevermind, since this would violate the spec as you mentioned).

I made the following code change in my instance to address this, but it's possible that only the latter change is really needed:
```js
  if (event.hasProperty('status')){
    var status = event.getFirstPropertyValue('status').toString().toLowerCase();
    if (["confirmed", "tentative", "cancelled"].indexOf(status) > -1){
      newEvent.status = status;
    }
  }
  if (event.hasProperty('summary') && icalEvent.summary.startsWith('Canceled: ')) {
    Logger.log('Event summary says canceled', icalEvent.summary, 'status had been recognized as', status, 'but setting to "cancelled"');
    newEvent.status = 'cancelled';
  }
```

Alternatively, the canceled events could simply be removed from the new calendar.

I think this can get complicated when a recurring event is cancelled (I'm not really sure how that works).

Happy to put up a PR for this if you like.

**Comment by derekantrican** [comment]
That seems like an Outlook bug. I'd rather report it to them first. Could you provide some repro steps so I can repro on my own Outlook calendar, then submit to them?

If it gets marked as "won't fix" or something, then I'd be happy to consider a workaround fix like yours

**Comment by jonas0b1011001** [comment]
> Additionally, it is possible that some event producers use the spelling "canceled" while Google Calendar requires the status to be spelled "cancelled" (both are valid english).

That's why there are standards that clearly define how things _should_ be done. [RFC5545](https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.1.11) clearly states that **cancelled** should be the only valid version.

> Alternatively, the canceled events could simply be removed from the new calendar.

Setting _status = cancelled_ moves the event to the calendar's recycle bin, so that's basically the same as removing it. I assume that's the same for outlook and gcal, which is why outlook is not setting the status property.

Could you share the definition of the example event from above (open the *.ics in a text editor)? I'm pretty sure there's a outlook specific property to mark it as cancelled.

**Comment by rattrayalex** [comment]
Thanks for the quick eyes on this!

Here's a censored version of the above event:

```ics
BEGIN:VEVENT
DESCRIPTION:adhoc instead\n
UID:040000008200E00074C5B7101A82E00800000000B2AF2AC45A2AD701000000000000000
 01000000020BF252A5398604C817266302DAE11EC
RECURRENCE-ID;TZID=Pacific Standard Time:20210531T153000
SUMMARY:Canceled: Backlog Refinement
DTSTART;TZID=Pacific Standard Time:20210531T153000
DTEND;TZID=Pacific Standard Time:20210531T160000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20210618T140254Z
TRANSP:TRANSPARENT
STATUS:CONFIRMED
SEQUENCE:18
LOCATION:https://us02web.zoom.us/j/CENSORED
X-MICROSOFT-CDO-APPT-SEQUENCE:18
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

I think this may typically happen for situations where the _recurring_ event is canceled, but the individual _instances_ are not themselves canceled. On the Outlook UI there's a button that says "Remove events" (or maybe it was "Remove series") in these situations – so I think it's an "intentional product feature" from their end that "canceled" events aren't _really_ canceled, since they don't seem to want them to go to the recycling bin until the user sends them there.

Speaking of, I think this might be the root/parent recurring event:

```ics
BEGIN:VEVENT
DESCRIPTION:new Backlog refinement meeting structure\n
RRULE:FREQ=WEEKLY;UNTIL=20220616T223000Z;INTERVAL=1;BYDAY=TH;WKST=SU
EXDATE;TZID=Pacific Standard Time:20210429T153000,20210506T153000,20210520T
 153000
UID:040000008200E00074C5B7101A82E008000000007CCB0D865C2AD701000000000000000
 0100000008CBBFCE675A92E4CB0E3AFD4CD248874
SUMMARY:Canceled: Backlog Refinement
DTSTART;TZID=Pacific Standard Time:20210408T153000
DTEND;TZID=Pacific Standard Time:20210408T160000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20210618T140254Z
TRANSP:TRANSPARENT
STATUS:CONFIRMED
SEQUENCE:17
LOCATION:https://us02web.zoom.us/j/CONFIRMED
X-MICROSOFT-CDO-APPT-SEQUENCE:17
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

But nothing jumps out to me as being relevant.

I tried "reporting" this issue [here](https://answers.microsoft.com/en-us/outlook_com/forum/ocalendar-oimportcal/bug-canceled-events-do-not-include-statuscancelled/9bbfba51-66c2-4c84-981a-506514d14276) but based on the non-response to some ~related messages, I don't anticipate a response from Microsoft.
