### ISSUE TITLE
Timezone skipped

### ISSUE THREAD

**Issue by Nuuki9** [derekantrican/GAS-ICS-Sync#219]
I've been using the script for some months and its worked great. However having just got back from a brief holiday, I hit an issue - meetings are appearing at the wrong time in Google Calendar, due to their time zone being ignored. I checked some similar issues, and though they didn't solve it they did give me some troubleshooting pointers.

When I check the logs I see the problem:

```
Timezone Eastern Standard Time 1 unsupported!
Using Timezone Europe/London!
```

Checking the event in the ICS file, the TZID is indeed shown as "Eastern Standard Time 1". Nothing has changed in how people are sending me invites, so I'm assuming there's been a change in how Outlook is reporting the timezone.

I adding an entry to the tzid.gs file, as follows:

`"Eastern Standard Time 1": "America/New_York",`

I now get the following in the logs:

```
Timezone Eastern Standard Time 1 unsupported!
Using Timezone America/New_York!
```

It has assigned the correct TZ and shows up as expected in Google Calendar, so that seems to have sorted it - it may be worth adding this entry into the next version though, as I assume others using Outlook will be affected.

I should add that I haven't tested any other timezones so don't know if there are others that may be affected.

**Comment by derekantrican** [comment]
Thanks. Definitely worth looking into (and probably adding). Do you mind sharing your ICS file from Outlook with this new timezone? You can use https://derekantrican.com/icssanitizer.html to remove sensitive info

**Comment by Nuuki9** [comment]
No problem.

I've stripped out all the specifics and uploaded it as a text file. Let me know if you need anything else.

[ics.txt](https://github.com/derekantrican/GAS-ICS-Sync/files/6696203/ics.txt)

**Comment by derekantrican** [comment]
Summarizing the important bits:
<details>
  <summary>
    [Click to expand]
  </summary>

```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:bec8d9798744d87f2b67e5b5c466f460
VERSION:2.0
X-WR-CALNAME:8ff922bbcd8ad41cdfc48d3c5163b2ab
BEGIN:VTIMEZONE
TZID:Eastern Standard Time
BEGIN:STANDARD
DTSTART:16010101T000000
TZOFFSETFROM:-0400
TZOFFSETTO:-0400
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T000000
TZOFFSETFROM:-0400
TZOFFSETTO:-0400
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:GMT Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T010000
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Pacific Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Eastern Standard Time 1
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Singapore Standard Time
BEGIN:STANDARD
DTSTART:16010101T000000
TZOFFSETFROM:+0800
TZOFFSETTO:+0800
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T000000
TZOFFSETFROM:+0800
TZOFFSETTO:+0800
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Tokyo Standard Time
BEGIN:STANDARD
DTSTART:16010101T000000
TZOFFSETFROM:+0900
TZOFFSETTO:+0900
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T000000
TZOFFSETFROM:+0900
TZOFFSETTO:+0900
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:India Standard Time
BEGIN:STANDARD
DTSTART:16010101T000000
TZOFFSETFROM:+0530
TZOFFSETTO:+0530
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T000000
TZOFFSETFROM:+0530
TZOFFSETTO:+0530
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:GMT Standard Time 1
BEGIN:STANDARD
DTSTART:16010101T000000
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T000000
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Turkey Standard Time
BEGIN:STANDARD
DTSTART:16010101T000000
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T000000
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
END:DAYLIGHT
END:VTIMEZONE
.
.
.
BEGIN:VEVENT
DESCRIPTION:6bec15622e30adf9e7cda06657d690f5
UID:78e61207f5bf813e78a7cf9b5c75fec7
SUMMARY:8b1986cf2dd29ec6f946c2d8f072bd9b
DTSTART;TZID=Eastern Standard Time 1:20210323T103000
DTEND;TZID=Eastern Standard Time 1:20210323T110000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20210622T171254Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:2
LOCATION:3f7913ff98f582b31174eb6671667064
X-MICROSOFT-CDO-APPT-SEQUENCE:2
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
.
.
.
END:VCALENDAR
```

</details>

Wow, you've got a lot of timezone definitions on your calendar! Looks like 9? Did you set these up?

**Comment by derekantrican** [comment]
Also seems odd that your "Eastern Standard Time" is different from "Eastern Standard Time 1":

![image](https://user-images.githubusercontent.com/1558019/122973653-53152c00-d346-11eb-82a9-927a35f18ea0.png)

"Eastern Standard Time" doesn't seem to do much since the "OFFSETFROM" is the same as the "OFFSETTO". And looking through your calendar there seems to be only 1 event using "Eastern Standard Time". Maybe you can remove the "Eastern Standard Time" definition and rename "Eastern Standard Time 1" (remove the " 1")?


Regardless, I think this is something specific to your setup so your workaround of adding "Eastern Standard Time 1" to tzid.gs is probably the solution and no need for us to incorporate it into the main code

**Comment by Nuuki9** [comment]
Yes I deal with a fairly spread out bunch of folks.

I don't see how I can change anything on my end - all of the invites have come from others, and all within a shared Exchange Online environment, so any TZ strangeness is presumably an Outlook or Exchange issue.

That said adding it as an entry has worked fine, so happy to make it as closed - just wanted to post it in case others have similar issues.

Thanks for the quick response, and for maintaining such a useful project!
