### ISSUE TITLE
Reoccurring events duplicated in Outlook do not sync with reoccurrence

### ISSUE THREAD

**Issue by watercrossing** [derekantrican/GAS-ICS-Sync#220]
I have got multiple reoccuring events in Outlook that do not sync to google correctly. Neither using GAS-ICS-Sync, or Google Calendar sync natively.

These events were created by duplicating an existing reoccuring event in Outlook (right click + drag the event, then select copy). I did this so that the meetings retain their Teams link (i.e. the following meeting will have the same chat as the old meeting).

Steps to reproduce in Outlook
- Create event, say 30min, make it reoccuring (for example weekly, end after 2 occurrences)
- right click + drag the event to perhaps 30min later, then select copy
- Make this newly created event also reoccuring
- Both GAS-ICS-Sync and Google calendar sync will fail to sync the reoccurence of the second event.

[Example ICS](https://pastebin.com/raw/HSeApVEz)

Something seems to be wrong with the ICS. The second reoccuring event has a RECURRENCE-ID that links it to the first one, even though they should just be separate events. Is this something that can be fixed / worked-around in GAS-ICS-Sync?

**Comment by derekantrican** [comment]
Thanks for reporting. I would imagine that is a bug with Outlook. I'll report it to them and let you know if there are any updates.

**Comment by jonas0b1011001** [comment]
Add `event.removeProperty('recurrence-id');` after [line 439](https://github.com/derekantrican/GAS-ICS-Sync/blob/94d729a8733b5a81b61db36ff70eb3047aa0eb92/Helpers.gs#L439) in Helpers.gs
<img width="155" alt="Bildschirmfoto 2021-06-30 um 21 18 27" src="https://user-images.githubusercontent.com/43352574/124019012-ce32ae00-d9e8-11eb-8456-3d1561e70159.png">

**Comment by watercrossing** [comment]
> Add `event.removeProperty('recurrence-id');` after [line 439](https://github.com/derekantrican/GAS-ICS-Sync/blob/94d729a8733b5a81b61db36ff70eb3047aa0eb92/Helpers.gs#L439) in Helpers.gs

This creates a toggle scenario, where on first sync the 11:30 event on the 8th appears, but on second sync the event gets deleted again. 
![image](https://user-images.githubusercontent.com/5656196/124101621-74b59800-da57-11eb-83c5-846270da8e05.png)

**Comment by jonas0b1011001** [comment]
True, sorry for that. We have to remove the property at an earlier stage.

Undo the change from above and add
```
if (event.hasProperty('recurrence-id') && (event.hasProperty('rrule') || event.hasProperty('rdate'))){
      event.removeProperty('recurrence-id');
}
```
after [line 171](https://github.com/derekantrican/GAS-ICS-Sync/blob/94d729a8733b5a81b61db36ff70eb3047aa0eb92/Helpers.gs#L171) in Helpers.gs

**Comment by watercrossing** [comment]
Thank you @jonas0b1011001 , that seems to have done the trick. My Google calendar just got much busier! 
While clearly a bug with Exchange/Outlook/Microsoft, I wonder if merging this into GAS-ICS-Sync is possible?

**Comment by jonas0b1011001** [comment]
Just tested if this is still a thing. Looks like Outlook is now completly skipping the recurrence rule of the copied event making the above mentioned fix irrelevant.

I'll close this as _can't fix_.
