### ISSUE TITLE
Pull appointments only "X-Days In the Future"

### ISSUE THREAD

**Issue by luketowen** [derekantrican/GAS-ICS-Sync#221]
It would be helpful if there was a way to limit the script from updating events more than "X Days" in the future.

Background on my use case:
- I am pulling an ICS feed, from a software application, that maintains customers appointment.  The appointments are changed, added, & deleted frequently.
- I am pulling this feed to create a dashboard to display the current day appointments and upcoming appointments for the next 3-7 days.
- The software provider creates unique IDs for all events each time the ICS is pulled.  This means that I have to add and delete each time the script runs. I am requesting that my software provider changes this.
- Filtering out as much as possible has been helpful.  I am only updating future events (with a -1 day offset) and use text filters to only pull relevant events. 
- If I had this feature, I would only update events one day in the past and 7-14 days in the future.  

Thank you for everyone contributing to this project!

**Comment by derekantrican** [comment]
Gonna copy what @jonas0b1011001 mentioned on the discord:

You could do something similar to https://github.com/derekantrican/GAS-ICS-Sync/issues/129#issuecomment-632184284 with `syncStartDate = now` and `syncEndDate = now + X days`

**Comment by luketowen** [comment]
Here is the additional information @jonas0b1011001 on the discord to add on top of #129  to make update only x days in the future:

replace syncLimitStart = new ICAL.Time.fromDateString(syncStartDate); with syncLimitStart = new ICAL.Time.fromJSDate(new Date())
and syncLimitEnd = new ICAL.Time.fromDateString(syncEndDate); with syncLimitEnd = new ICAL.Time.fromJSDate(new Date()).adjust(7,0,0,0);
syncLimitStart = new ICAL.Time.fromJSDate(new Date()).adjust(-1,0,0,0); if you want yesterday to be included as well.

With #129 and the edits above, I set the date from #129 to 3 years in the future and used the edits above.  The script is now updating only items a day before and 7 days in the future.  

Thank you all!

**Comment by derekantrican** [comment]
If you're replaced instances of `syncStartDate` & `syncEndDate` with `new Date()` as in your comment, then you don't need those variable declarations (eg `var syncStartDate = ...`). `new Date()` means "now" so it should automatically adjust
