### ISSUE TITLE
Mixing events in calendars

### ISSUE THREAD

**Issue by supermozzie** [derekantrican/GAS-ICS-Sync#223]
Hi, I've got 2 calendar links to be imported into 2 separate calendars. I'm finding that some (not all) events in my first calendar get added into my second calendar. But the reverse does not happen.

Thank you.

**Comment by jonas0b1011001** [comment]
Sounds like #185, are you using an old version?

**Comment by supermozzie** [comment]
Oh yes, it's exactly that. Sorry about that.
