### ISSUE TITLE
Ticktick tasks syncing to Google Calendar with a difference of 1 hr

### ISSUE THREAD

**Issue by SyedIrtiza555** [derekantrican/GAS-ICS-Sync#227]
Read next comment for details
Email: s.irtizahussain@gmail.com

**Comment by SyedIrtiza555** [comment]
webcal://ticktick.com/pub/calendar/feeds/g028mav19vza/basic.ics

TickTick Task scheduled at 3pm shows at 4pm in Google Calendar

![Screenshot_20210805-142750](https://user-images.githubusercontent.com/52050986/128327616-249bc321-69b0-4f21-ab90-f2565f187ba2.png)
![Screenshot_20210805-142732](https://user-images.githubusercontent.com/52050986/128327622-4519c919-4795-4dec-9e27-bfdc2b4305d9.png)

**Comment by jonas0b1011001** [comment]
What timeframe and timezone is it showing when you click on the event and edit it?

**Comment by SyedIrtiza555** [comment]
Asia/Pakistan

But it isnt a problem of timezone... Tickticks ical by itself gives the start time an hour late... Can this be edited within the script?

**Comment by derekantrican** [comment]
> Tickticks ical by itself gives the start time an hour late

Why? If your task is at 3pm, why does the ical give 4pm?

> Can this be edited within the script?

Sure, but based on your answer to the question above, you might want to talk to ticktick about how to fix this (if it's unintended)

**Comment by SyedIrtiza555** [comment]
Talking to Tick tick is a lengthy step...
I think TickTick's iCal shows starttime=endtime..
Can this be done through the script?

**Comment by jonas0b1011001** [comment]
> Can this be done through the script?

Sure, just change Helpers.gs lines [293-301](https://github.com/derekantrican/GAS-ICS-Sync/blob/94d729a8733b5a81b61db36ff70eb3047aa0eb92/Helpers.gs#L293) to
```

    newEvent = {
      start: {
        dateTime : icalEvent.startDate.adjust(0,-1,0,0).toString(),
        timeZone : tzid
      },
      end: {
        dateTime : icalEvent.endDate.adjust(0,-1,0,0).toString(),
        timeZone : tzid
      },
    };
```

**Comment by SyedIrtiza555** [comment]
@jonas0b1011001 Thanks.... This worked.... 💯

Thanks @derekantrican. Thanks for this script. 💯

**Comment by SyedIrtiza555** [comment]
Kindly someone close this issue... This one's resolved now... I donno how to do this...
