### ISSUE TITLE
Time Zones Off?

### ISSUE THREAD

**Issue by rwwest7** [derekantrican/GAS-ICS-Sync#23]
I use the ical's pulled from here:

http://ical.8to18.com/ , specifically this one: http://ical.8to18.com/link/jacksonville/2018-2019/BBB%20V/EDT

I do a manual import to a Google Calendar, and I do a sync with this script to a different calendar. The times for every single event are different by an hour. 

The GAS-ICS-Sync creates the events an hour behind the manual import. Is it possible to tweak the time in the scrypt? They're both using the exact same ICS file.

**Comment by rwwest77** [comment]
I just now shared it. I haven't made any changed below the danger line.

Thank you!

**Comment by derekantrican** [comment]
@rwwest7 I can reproduce this and will investigate

![image](https://user-images.githubusercontent.com/1558019/52213785-ee280c80-2844-11e9-9f9d-7459a383e8f7.png)

**Comment by derekantrican** [comment]
Related to #3

**Comment by rwwest77** [comment]
Can I hard code the timezone in the script? In our case, we don't really need it to dynamically determine. It will always be EST.

**Comment by derekantrican** [comment]
I made a [JSFiddle](http://jsfiddle.net/7f1q56mb/2/) to see if I can reproduce this issue. I can. So I think it is either a problem with ICAL.js parsing the `VTIMEZONE` object or something where I don't know how to use ICAL.js properly

**Comment by nanobrad** [comment]
The VTIMEZONE component is wrong:
```
BEGIN:VTIMEZONE
    TZID:America/New_York
    BEGIN:DAYLIGHT
    DTSTART:19700308T020000
    TZOFFSETFROM:-0400
    TZOFFSETTO:-0500
    RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
    TZNAME:EDT
    END:DAYLIGHT
    BEGIN:STANDARD
    DTSTART:19701101T020000
    TZOFFSETFROM:-0500
    TZOFFSETTO:-0400
    RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
    TZNAME:EST
    END:STANDARD
END:VTIMEZONE
```
They reversed the TZOFFSET*s. Daylight time in the US for New York (TZOFFSETTO) should be -0400.

Google must be smart enough to not trust the whole VTIMEZONE record, but only pay attention to the TZID.

**Comment by derekantrican** [comment]
>Google must be smart enough to not trust the whole VTIMEZONE record, but only pay attention to the TZID.

That may be exactly what is happening. I condensed the ICS file to this (the same thing in the jsfiddle on the other issue page):

    BEGIN:VCALENDAR
    VERSION:2.0
    PRODID:icalendar-ruby
    CALSCALE:GREGORIAN
    BEGIN:VTIMEZONE
    TZID:America/New_York
    BEGIN:DAYLIGHT
    DTSTART:19700308T020000
    TZOFFSETFROM:-0400
    TZOFFSETTO:-0500
    RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
    TZNAME:EDT
    END:DAYLIGHT
    BEGIN:STANDARD
    DTSTART:19701101T020000
    TZOFFSETFROM:-0500
    TZOFFSETTO:-0400
    RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
    TZNAME:EST
    END:STANDARD
    END:VTIMEZONE
    BEGIN:VEVENT
    DTSTAMP:20190419T152238Z
    UID:4165@8to18
    DTSTART:20190215T193000
    DTEND:20190215T213000
    DESCRIPTION:BASKETBALL-V Get more event information at - http://il.8to18.co
     m/jacksonville/scoreresultdetail?eventid=4165
    LOCATION:HOME - The Bowl
    SUMMARY:BASKETBALL-V Boys - VS Lanphier (Game)
    END:VEVENT
    END:VCALENDAR

I imported it into Google Calendar twice (once as-is, and once using `TZID:test`. I also had to change the `UID` of the event so it didn't get overwritten in Google Calendar). This was the result:

![events](https://i.imgur.com/AN9OBeD.png)

I may have to give an option to use the `VTIMEZONE` or to use the `TZID` exclusively. In the meantime, I'm going to let 8to18.com know that their ics files are being created improperly

**Comment by nanobrad** [comment]
There are no built-in TZIDs in ical.js, so you can't use TZID by itself unless you find a source of vtimezone components. I'd close this issue.

**Comment by derekantrican** [comment]
@nanobrad Right, I understand that there are no built-in ones. But - if I wanted to - I could find a source somewhere (something similar to [this](https://github.com/chrisdavies/js-windows-timezones/blob/master/win-timezones.js)) that has a list of them. The ultimate solution for this particular issue (and user) is to get 8to18.com to fix their ical files

**Comment by derekantrican** [comment]
8to18.com has let me know that they have fixed this. Here is the related ticket: https://8to18.jitbit.com/helpdesk/Ticket/20355119

@rwwest7 @rwwest77 (not sure which account is the primary one for you) Please let me know if this issue is fixed for you going forward. You may have to run the ICS sync program again (or do some other "refreshing")

**Comment by jonas0b1011001** [comment]
I just came across this, and I think that even Google is importing the events at the wrong timeslots.
According ICAL RFC 5545 Dates are assumed 'floating' if no Timezone is referenced (which is the case in the mentioned calendar). Therefore the event starting on DTSTART:20190215T193000 should be placed at 19:30 regardless of timezone differences.

> The date with local time form is simply a DATE-TIME value that does not contain the UTC designator nor does it reference a time zone.  For example, the following represents January 18, 1998, at 11 PM:
> 
> 19980118T230000
> 
> DATE-TIME values of this type are said to be "floating" and are not bound to any time zone in particular.  They are used to represent the same hour, minute, and second value regardless of which time zone is currently being observed.
