### ISSUE TITLE
ICAL is not defined

### ISSUE THREAD

**Issue by kdwhitmire** [derekantrican/GAS-ICS-Sync#231]
I just installed all of this code (thank you so much for a solution to Goggle's problem!), but none of the calendars I've tried are working. I saw another issue posted that said webcal should be converted to http or https and I've tried both as well as changing parts of the url to see if they house the ics file somewhere else but to no avail.  These calendars work in Google. I also verified at iCalendar.org that the webcal and https addresses are correct and have entries. The error I'm getting is:

ReferenceError: ICAL is not defined
parseResponses @ ical.js.gs: 138
startSync @ Code.gs: 192

Any help is appreciated. I'd love to get this code to work!

**Comment by jonas0b1011001** [comment]
Seems like you are missing a [file](https://github.com/derekantrican/GAS-ICS-Sync/blob/master/ical.js.gs).
Did you create a copy of the whole script from [here](https://script.google.com/d/1BOk8MDLbLaHh6SwG1M1tsgNXjkcC-79LE0QoipRuTDxbO3fMVvqoROQD/edit?newcopy=true)?

**Comment by kdwhitmire** [comment]
I did, but I won't swear I did it correctly... this is my first attempt at a Google Apps Script.  Hopefully you can get the image below... it shows how I set up the various files.
![image](https://user-images.githubusercontent.com/54453237/132762810-3d50da7f-599a-43bc-ae9b-d480a0871dc2.png)

**Comment by kdwhitmire** [comment]
So I'm not exactly sure what the difference was, but I just threw everything I had in the trash and started over with a clean copy. All is working now. Thanks so much again for this solution!
