### ISSUE TITLE
Feature to differentiate between Completed and Non Completed Tasks

### ISSUE THREAD

**Issue by prasadkkaranth** [derekantrican/GAS-ICS-Sync#234]
Hi, I have used this script to sync one of my to do list apps calendar with Google Calendar. But what I noticed is that the moment I complete a task in my To do list, it gets removed from the Google Calendar, because of the flag: removeEventsFromCalendar = true. If I disable it, it doesn't do anything, even though onlyFutureEvents = false. I expect it to update completed tasks in some unique way, for ex: Strike through or add DONE prefix etc.., that way we can clearly differentiate between completed and Not completed tasks for both before and after date time scenarios. I went through the Google Calendar API, I couldn't figure out how to do that myself.

**Comment by jonas0b1011001** [comment]
> If I disable it, it doesn't do anything

The events still get deleted or what do you mean?

**Comment by prasadkkaranth** [comment]
If I set it to removeEventsFromCalendar = false, obviously it doesn't remove, but it doesn't mark it as Completed or Show it as Completed. I think the easiest option is to change the color or to change the title, but I am not so good at this programming language. If somebody can share a sample code to do that, I can modify the code to fit to my needs, if its not required for the general public.

**Comment by jonas0b1011001** [comment]
You can do it like this. The code to replace is in helpers.gs starting at [line 603](https://github.com/derekantrican/GAS-ICS-Sync/blob/d24af0ce0ce9aea0f1f8db55432d4172b61ee8c3/Helpers.gs#L603)

```
function processEventCleanup(){
  for (var i = 0; i < calendarEvents.length; i++){
      var currentID = calendarEventsIds[i];
      var feedIndex = icsEventsIds.indexOf(currentID);
      
      if(feedIndex  == -1 && calendarEvents[i].recurringEventId == null){
        Logger.log("Updating completed event " + currentID);
        if (calendarEvents[i].summary.substr(0,6) != "Done: "){
          //Add prefix
          calendarEvents[i].summary = "Done: " + calendarEvents[i].summary;
        }
        //change event color
        calendarEvents[i].colorId = 2;
        callWithBackoff(function(){
          Calendar.Events.update(calendarEvents[i],targetCalendarId, calendarEvents[i].id)
        }, defaultMaxRetries);
      }
    }
}
```

However be aware that your todo list service obviously treats completed tasks just like deleted tasks (both simply get removed from the ics). There is no way for us to tell if the todo item is missing because it was removed by you or marked as completed.

**Comment by prasadkkaranth** [comment]
Perfect! It works great! I commented out the following if statement, as you said the ToDoList App doesn't add prefix "Done: ", so there is no point in doing this. I don't usually delete any tasks, so if the ToDoList service response is same for Completed and Deleted tasks, that's totally fine for me :).. If I delete anything from the ToDoList, I can delete it from the Google Calendar manually.

// if (calendarEvents[i].summary.substr(0,6) != "Done: "){

Thank you so much buddy for such a quick response!

**Comment by prasadkkaranth** [comment]
I made a mistake, I corrected it in the above comments. Thanks again!
