### ISSUE TITLE
GoogleJsonResponseException

### ISSUE THREAD

**Issue by Errious** [derekantrican/GAS-ICS-Sync#238]
Hallo,

im using this script to get data from a calender in an Project Management System and receive this Error on every sync action and would like to know if someone could explain this to me and help to find a solution for this.

Its allways the very first response when the script is running.

07.11.2021, 23:09:31	Error	GoogleJsonResponseException: API call to calendar.events.insert failed with error: The specified time range is empty.
    at [unknown function](Helpers:228:34)
    at callWithBackoff(Helpers:877:16)
    at processEvent(Helpers:227:20)
    at [unknown function](Code:202:9)
    at startSync(Code:201:15)

**Comment by derekantrican** [comment]
Are you willing to share your ICS url or contents? You can use derekantrican.com/icssanitizer to remove sensitive information

**Comment by Errious** [comment]
Here we go ;-)

[https://pastebin.com/4d5GKkF5](url)

**Comment by derekantrican** [comment]
I'm not seeing the same issue when I try to sync (I see some "Rate Limit Exceeded" errors that are retried, but not "specified time range is empty"). Can you share the logs? You can run the "startSync" function then copy the logs from the "Execution Log" pane

**Comment by Errious** [comment]
Well the only thing i get is that another iteration is running!

Do i need to stop the whole script first?

21:00:12	Hinweis	Ausführung begonnen
21:00:11	Info	Another iteration is currently running! Exiting...
21:00:12	Hinweis	Ausführung abgeschlossen

**Comment by derekantrican** [comment]
Yeah, try stopping the script (by running the uninstall function), wait a few minutes (up to a maximum of your "howFrequent" setting) and try again

**Comment by Errious** [comment]
Ok thats done but still... What could be possible is an event without start date? I changed onlyFutureEvents = **true** and the script removed all old events, after this the next sync was running trough without errors.

Because i can see the events are there and it could be an error from what i talked about first it seems ok for me to have an error i know he comes from something old in the list.

23:26:26	Error	
GoogleJsonResponseException: API call to calendar.events.insert failed with error: The specified time range is empty.
(Anonym)	@ Helpers.gs:228
callWithBackoff	@ Helpers.gs:877
processEvent	@ Helpers.gs:227
(Anonym)	@ Code.gs:202
startSync	@ Code.gs:201

**Comment by jonas0b1011001** [comment]
> What could be possible is an event without start date?

The error rather hints at the start date/time being **after** the end date/time.

You should find the id of the event in question right above the error message in the log. This should help you identify which one is causing the error.

**Comment by Errious** [comment]
I discovered this error is related to some events who were not in a normal timeline who should have normal behavior like beginning and ending and thats ok, so i close this here and say thank you for your answer and help!
