### ISSUE TITLE
Need to handle all-day events

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/GAS-ICS-Sync#24]
It seems all-day event times are getting parsed correctly, but not added correctly?

![image](https://user-images.githubusercontent.com/1558019/52212865-5c1f0480-2842-11e9-8183-ae7607234f1b.png)

Instead, we should have a variable called `IsAllDay` on the event class and use this GAS method instead: https://developers.google.com/apps-script/reference/calendar/calendar#createAllDayEvent(String,Date,Date,Object)

**Comment by michaelcadilhac** [comment]
I believe this is due to parsing of the timezone.  My ICS (produced by Org-Mode) used X-WR-TIMEZONE to indicate the timezone, which is nonstandard; I've added a VTIMEZONE group and now it works.

Cheers;
M.

**Comment by derekantrican** [comment]
@michaelcadilhac Good to know

**Comment by derekantrican** [comment]
The ics file I'm using in the screenshot above is for central time. If I change Google Calendar to central time, I don't see the issue

![image](https://user-images.githubusercontent.com/1558019/52542974-1ab6b980-2d5a-11e9-8bc3-8ede972f20b4.png)

**Comment by derekantrican** [comment]
![image](https://user-images.githubusercontent.com/1558019/52595812-9fa9dd80-2e03-11e9-9dae-58f8355c765c.png)
