### ISSUE TITLE
Question - Is there a way to remove all the synced events?

### ISSUE THREAD

**Issue by frankquatt** [derekantrican/GAS-ICS-Sync#240]
I ran the script and had my Outlook events sync directly into my main Google calendar. Now I would like to remove all the Outlook events so I can resync as a separate calendar. Thanks!

**Comment by jonas0b1011001** [comment]
Easiest way is to replace your outlook url with an empty ics (you can use _https://pastebin.com/raw/nZfAYcKS_) and sync it to the same calendar.

**Comment by frankquatt** [comment]
> Easiest way is to replace your outlook url with an empty ics (you can use _https://pastebin.com/raw/nZfAYcKS_) and sync it to the same calendar.

Thanks!
