### ISSUE TITLE
Question - Is it possible to show the title of a private event when imported?

### ISSUE THREAD

**Issue by frankquatt** [derekantrican/GAS-ICS-Sync#241]
If I have private events in Outlook, they are imported into the Google calendar but I can't see the title. I tried changing descriptionAsTitles = true but that didn't do anything. The title shows up as "Private Appointment" whether true or false. I also tried changing overrideVisibility = "public" but the title didn't come through either though it made the appointment public, which is actually not what I want. I want it to stay private but for me to be able to see the title in my Google calendar. Any suggestions? Thanks!

**Comment by derekantrican** [comment]
_Possibly_. When you publish the calendar to an ICS url in Outlook, you may have the option for "Can view all details":

![](https://www.howtogeek.com/wp-content/uploads/2019/08/4-Publish-a-calendar-1.png?trim=1,1&bg-color=000&pad=1,1)

If you've already done that, then it may not be possible as Outlook likely hides the event details when it publishes (making it impossible for our script or any other user of that ICS url to see the event details)

**Comment by frankquatt** [comment]
Thank you for the quick response. Yes, my Outlook is already "Can view all details". I tested looking at the HTML link for Outlook and even there the title is hidden. So like you said, Outlook seems to hide it. Might be an Outlook bug since the options include "view all details" and "view title and location" and testing both, the title doesn't show up in either.

**Comment by derekantrican** [comment]
You could argue it's an Outlook bug (since you're the calendar owner) but ICS urls are also public so you could argue that a "private event" shouldn't have details published.

Regardless, I think Outlook has a "Feedback" option under "Help" where you could send your opinion.

**Comment by frankquatt** [comment]
> You could argue it's an Outlook bug (since you're the calendar owner) but ICS urls are also public so you could argue that a "private event" shouldn't have details published.
> 
> Regardless, I think Outlook has a "Feedback" option under "Help" where you could send your opinion.

I was thinking it was a bug because they give you privacy options when you publish your calendar so I thought it should be the person's choice through the privacy options. However, you're right that the privacy should be for normal events so it shouldn't affect events marked private since presumably you marked it private so other people can't see it. Thanks again!
