### ISSUE TITLE
Changing timezones in gcal causes events to appear at the wrong time

### ISSUE THREAD

**Issue by cboshuizen** [derekantrican/GAS-ICS-Sync#244]
I travel a lot and change time zones on my computers and phones frequently. It seems that the calendar events are stored with incorrect UTC/offset timestamps, because when I change time zones forwards and back, the events appear at the wrong place for a few hours. My expectation would be that the events are stored at a correct UTC time, and changing time zones would move all the events forward or back wards to the relative local time. Instead, they seem to stay at an absolute time and so are wrong in a different time zone. 

It takes several hours before the time zone is represented correctly, and manually running a sync from the script does not correct the time offset. 

Please see a screenshot attached, showing the difference between the GAS-ICS calnedar (dark blue) and the native webdav feed (light blue), where the two hour offset is evident. I had just flown back from central time to pacific, hence the two hour offset. 

Steps to reproduce; Sync events; change the time zone on your PC and/or google phone; observe that the time zone for gas-ics events is wrong; wait a few hrs and the events will eventually shift to the correct relative time; change time zones back; observe that the gas-ics events are wrong again; wait a few hours and they will correct themselves eventually. 
 
![gcal sync timezone issue copy](https://user-images.githubusercontent.com/1034382/145871144-4bdada95-2dea-4640-8825-410ec40adb35.png)

**Comment by amirazimit** [comment]
I have a similar issue with timezones. It used to be working till yesterday but today I faced this bizarre issue. My imported calendar is in the ET timezone but my destination calendar is in another timezone. When events get imported instead of keeping their original timezone they match the timezone of the destination.

**Comment by jonas0b1011001** [comment]
> I have a similar issue with timezones. It used to be working till yesterday but today I faced this bizarre issue. My imported calendar is in the ET timezone but my destination calendar is in another timezone. When events get imported instead of keeping their original timezone they match the timezone of the destination.

@amirazimit  Are you syncing an outlook calendar? Sounds a lot like #225

**Comment by amirazimit** [comment]
Thanks, @jonas0b1011001 👍 I reconnected everything and created a new calendar and the issue got fixed.
