### ISSUE TITLE
Getting info from a empty list

### ISSUE THREAD

**Issue by RDTuta** [derekantrican/GAS-ICS-Sync#246]
Hi, 

Thanks for the code. I have found what I thing is a bug. When you try to sync info from a emty list a task with name No Task is created in a data (I haven t found the correlation -for me is creating the task on Dec 17 but 2020) at teh time of the execution.

**Comment by derekantrican** [comment]
Can you provide an example or some steps to reproduce?

**Comment by RDTuta** [comment]
I have a list in Tick Tick with one task. I works perfectly. When I complete the task I have no active task on that list. In this situation when it syncs a new entry on the google calendar is create with name "No task" and in a date that for me has been the day of today but on 2020. I found it using find function on google cal

**Comment by RDTuta** [comment]
This is the task is created
![image](https://user-images.githubusercontent.com/95448732/146613931-4ceca6f7-c38e-4038-8745-19cc9042dc3b.png)
And is created one task for every execution

**Comment by jonas0b1011001** [comment]
Here is an example how TickTick publishes an empty list:
```
BEGIN:VCALENDAR
PRODID:-//TickTick//task 1.0//EN
VERSION:2.0
CALSCALE:GREGORIAN
X-WR-CALNAME:ticktick.com
BEGIN:VEVENT
DTSTAMP:20211218T125421Z
DTSTART:20201218T125421Z
DTEND:20201218T125421Z
SUMMARY:No task.
UID:fef22fff91d849e1995eab4c67cbc037@calendar.ticktick.com
END:VEVENT
END:VCALENDAR
```
The script works as expected, we have no influence on how TickTick publishes their data.

**Comment by derekantrican** [comment]
I've heard of quite a few users using our script for ticktick. I wonder if this would be worth adding to prod. At the very least, skipping the event in `processEvent` based on a "No task" summary could work (as long as you don't want to name any task that ;) )
