### ISSUE TITLE
Error - Exception: Service Calendar API has not been enabled

### ISSUE THREAD

**Issue by GitGrove** [derekantrican/GAS-ICS-Sync#250]
I followed the basic install instructions for the new Apps Script editor (copy the project, edit the variables, run the code with "install" setting enabled) and everything seemed to work (i.e. I was prompted to allow the app script to access my calendar/storage etc which I approved). However nothing happened. I checked the execution logs and I'm getting a permissions error:

**_**Exception: Service Calendar API has not been enabled for your Apps Script-managed Cloud Platform project. If you recently turned on this advanced Google service, wait a few minutes for the action to propagate to our systems and retry.
    at setupTargetCalendar(Helpers:110:46)
    at startSync(Code:162:26)**_**

![sync permissions issue](https://user-images.githubusercontent.com/97621652/149190215-6010adc6-e370-4b4c-bffd-5491303b42a0.png)

I've been unable to figure where or how to explicitly enable the Service Calendar API for my project. Google's documentation on this appears to be outdated. I should note that my account is part of a paid Google Workspace plan and I have administrative access to change anything that should be necessary to make this happen. Is there perhaps something in the setup instructions that I've missed?

**Comment by jonas0b1011001** [comment]
check step 9 of the [manual install instructions](https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually) to enable the required services.

**Comment by GitGrove** [comment]
So neither option is available to me when I click the "+ Services" link and see the dialog box. However, if I switch to the legacy editor and choose Resources > Advanced Google Services, then I see both APIs you mentioned and they're both enabled already. The error mentioned above persists. Could this be a Google Cloud Services configuration issue?

**Comment by GitGrove** [comment]
That did not help, but here's what did (and you may want to add this to the new install instructions). 

THE SOLUTION: **execute the App Script copying process, in an incognito/private window exclusively logged into your desired target google account.**

CAUSE: There's a known bug with google services when you're logged into multiple accounts on one browser. The "Copy" function for the Apps Script editor defaults to the browser's primary google account (u/0) which causes all types of permissions issues and errors if you have to switch accounts after you've copied the project (which I did). Here's more info [via StackExchange](https://stackoverflow.com/questions/60230776/were-sorry-a-server-error-occurred-while-reading-from-storage-error-code-perm).

I ran into the error mentioned in that StackExchange post and was able to edit the app script in an incognito window with my intended account, however, it caused other problems with the API (hence my bug post). I deleted the project and re-initiated the install process in an incognito window logged in exclusively as my target google account. This worked.

**Comment by derekantrican** [comment]
Glad you got it solved. Yeah, there's definitely issues I've seen when you have multiple Google accounts "linked" (even with Google Drive showing 1 account, but with scripts authorized to run as a different account).

I'll think about a good way to add this to the docs, thanks
