### ISSUE TITLE
Clean up extra whitespace in event descriptions

### ISSUE THREAD

**Issue by simonkotwicz** [derekantrican/GAS-ICS-Sync#253]
Some calendars seem to add extra whitespace in the ics feed event descriptions. I personally added this:
```
    newEvent.description = icalEvent.description
      .replace(/\n[ \t]*\n/g, '\n')
      .replace(/\n\s*\n/g, '\n\n')
      .replace(/ {2,}/g,' ');
```

maybe some version of that would be useful to in the common repo?

**Comment by derekantrican** [comment]
I think this is a case of "specific to your situation, but we can add it if enough people ask for it". So I'm going to say "won't fix" for now.

**Comment by simonkotwicz** [comment]
Right, I'm guessing it's due to how some richly formatted fields get encoded, I thought it would be a wider spread problem but it might not be.
