### ISSUE TITLE
Unable to copy script after changing Google account

### ISSUE THREAD

**Issue by tobydjones** [derekantrican/GAS-ICS-Sync#256]
- Description of the problem
I have two google accounts. On one I was able to copy the script successfully, but on the other I'm getting an error

I started logged in to my Google account, on this page:
https://script.google.com/home/projects/1BOk8MDLbLaHh6SwG1M1tsgNXjkcC-79LE0QoipRuTDxbO3fMVvqoROQD/edit
However, when I selected my second Google account, the URL changed to:
https://script.google.com/u/3/home/projects/1BOk8MDLbLaHh6SwG1M1tsgNXjkcC-79LE0QoipRuTDxbO3fMVvqoROQD
The screen looked exactly the same as before, but when I clicked the copy button, I got the error "Sorry, unable to open the file at present. Please check the address and try again". The tab title was "Page not found".

- Screenshots
![image](https://user-images.githubusercontent.com/1651718/152988695-ef310f4b-947e-4b42-804d-fcea3525ae3c.png)

I appreciate that this is more a weird Google thing than a bug with the script, and I'll just have to copy the script manually, but I thought I'd flag it here for information.

**Comment by derekantrican** [comment]
If both accounts are linked, double-check that you're logged in with the intended account in Google Drive (and on the script page)

**Comment by derekantrican** [comment]
If you're still stuck after the above, you can follow the steps for setting up the script manually: https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually

**Comment by munen** [comment]
I have had the same error shown by Google. An easy fix for me was to create a browser session where I'm only logged in to the account which I use for the calendar. It worked on the first try.

**Comment by derekantrican** [comment]
@tobydjones - were you able to try any of the suggestions that were given above?

**Comment by derekantrican** [comment]
Closing as there has been no response. Please comment again if this is still an issue
