### ISSUE TITLE
Calendar created by script cannot be shared publicly

### ISSUE THREAD

**Issue by eloscyppo** [derekantrican/GAS-ICS-Sync#257]
- Version 5.6 (latest)
- similar issue not found on github
- example .ics (sanitized): https://pastebin.com/GBjcDtPp 

- Description of the problem:
After running this great script it was successfully authorized on my google account and created desired calendar. I can see it and all the changes in the .ics feed are correctly reflected in this google calendar so far. However, I would like to share it publicly. I clicked relevant option and google created a publik link to share the calendar. Unfortunately, no one but me can see the calendar from that link. What could be wrong?

**Comment by derekantrican** [comment]
There shouldn't be any reason why the calendar created by the script would act any differently than an owned calendar. Can you provide the link? Can you provide screenshots of the items you clicked on in Google Calendar?

**Comment by eloscyppo** [comment]
I am surprised that it just started to work... I don't know... maybe cache or something...
