### ISSUE TITLE
Handle missing DTEND or mixed date & datetime for DTSTART & DTEND

### ISSUE THREAD

**Issue by eloscyppo** [derekantrican/GAS-ICS-Sync#258]
Is there a way to correctly take care of the above?

Trello can only set a start date and end date + end time (known as due date/time). But there are some add-ons like Planyway that can handle this and generate correct .ics feed. Actually, I am now using this add-on only for that, and the script is using Planyway's .ics feed instead of Calendar's add-on .ics feed. For now this is the only way to handle the several-days events or several-hours events.

**Comment by derekantrican** [comment]
Can you explain what you're currently seeing and what you would expect? It sounds like it's a difference between "date" & "datetime"?

**Comment by eloscyppo** [comment]
Sure. You see - when an event has set start/end date/time - it is not reflected in Google calendar at all while using the script + trello .ics feed. I managed to handle this only by using 3rd party add-on...

Trello card:
![image](https://user-images.githubusercontent.com/99692546/153979451-c44e7fa5-4a72-481e-9147-55e25563c5a9.png)
![image](https://user-images.githubusercontent.com/99692546/153979465-27bb1ea8-4da4-4651-b868-616bc64a14fd.png)

Google calendar with feed directly from trello (Calendar add-on):
![image](https://user-images.githubusercontent.com/99692546/153979570-1e2f4240-830d-4bd1-b39a-1c956d4ed884.png)

Planyway add-on settings on the same card:
![image](https://user-images.githubusercontent.com/99692546/153979627-1e7fa3b9-e74e-46da-9de6-5ea2e4bfe42e.png)

Google calendar with feed from Planyway trello (Calendar add-on):
![image](https://user-images.githubusercontent.com/99692546/153979683-47f249bc-e492-41d6-8b99-04e14932bfcd.png)

**Comment by jonas0b1011001** [comment]
> Is there a way to correctly take care of the above?

Simple answer: No. Google calendar does not allow to mix date and datetime.

On the 4th screenshot the start also has a time, therefore it is able to sync.

**Comment by jonas0b1011001** [comment]
I agree that it should sync differently, however it all depends on how trello is actually defining the events. Could you share an example ics, so i can have a look where it's going wrong?

**Comment by eloscyppo** [comment]
Now I see that .ics completely omits the start date.... 
Maybe it wouldn't be so hard to implement a simple add-on for trello, that gives you the ability to set date/time ranges of the cards like in normal calendar...?

TEST1 - only start date
![image](https://user-images.githubusercontent.com/99692546/154109230-4eafbd35-1193-494c-ac3b-17ac24a7554d.png)

TEST2 - only end date (and end time, as it is mandatory)
![image](https://user-images.githubusercontent.com/99692546/154109440-e5d337d0-1e97-46b8-a436-9d69de9efae6.png)

TEST3 - both start and end date (and end time, as it is mandatory)
![image](https://user-images.githubusercontent.com/99692546/154109618-357335e0-3a9b-46d9-9b17-a9867843be67.png)

`BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Tri Tech Computers//node-icalendar//EN
X-WR-CALNAME:TEST
X-PUBLISHED-TTL:PT1H
REFRESH-INTERVAL:PT1H
BEGIN:VEVENT
DESCRIPTION:\n\nCard URL: https://trello.com/c/P2bZ6ywT\nNo Assigned Member
 s
SUMMARY:TEST2 [Publiczne]
DTSTART:20220216T110000Z
DURATION:PT1H
UID:620bda0c88ea6c7da2ed1807@trello.com
DTSTAMP:20220215T165319Z
END:VEVENT
BEGIN:VEVENT
DESCRIPTION:\n\nCard URL: https://trello.com/c/TObhzhBM\nNo Assigned Member
 s
SUMMARY:TEST3 [Publiczne]
DTSTART:20220218T110000Z
DURATION:PT1H
UID:620bda3feb31322205379b9c@trello.com
DTSTAMP:20220215T165319Z
END:VEVENT
END:VCALENDAR`
