### ISSUE TITLE
Calendar not pulling Jobber events

### ISSUE THREAD

**Issue by chouston85** [derekantrican/GAS-ICS-Sync#259]
Hi, first of all, thank you for this awesome, much-needed tool!

I am using a service called Jobber for managing a few aspects of my business. The calendar in the app is awesome, but severely lacking in offline capabilities. It has a google calendar/iCalendar sync via URL option, which I am using as a backup for when data service is not available in the field, but the infrequent backups make it almost useless.

I implemented your script and changed the necessary variables to work with my calendar and can see the calendar pop-up. I have set the frequency to 5, but it doesn't seem to be pulling any events from the calendar. I am not sure if I am doing something wrong or if there is some reason that the script will not work in this instance, but I am hoping someone may have some insight for me.

I looked through the execution log and occasionally this error pops up:

Feb 18, 2022, 4:47:51 PM	Info	Result: 1
Feb 18, 2022, 4:47:51 PM	Info	Syncing 1 calendars to Jobber1
Feb 18, 2022, 4:47:51 PM	Info	Working on calendar: c_h95639suurhavo65dmjsl0tghg@group.calendar.google.com
Feb 18, 2022, 4:47:51 PM	Info	Fetched 0 existing events from Jobber1
Feb 18, 2022, 4:47:51 PM	Error	TypeError: Cannot read property 'parent' of null
    at addSubcomponent(ical.js:2609:21)
    at updateTimezones(ical.js:94:14)
    at parseResponses(Helpers:141:18)
    at startSync(Code:191:17)

Thanks!

**Comment by jonas0b1011001** [comment]
Could you share the calendar you are trying to sync? If you are worried about privacy of your calendar, you can use the [ICS Sanitizer](https://derekantrican.github.io/icssanitizer.html)

**Comment by chouston85** [comment]
Sure, it is

https://secure.getjobber.com/calendar/48660508814852170534741278315351512637728218242648/jobber.ics?at%5B%5D=1224830&ot%5B%5D=basic&ot%5B%5D=reminders&ot%5B%5D=events&ot%5B%5D=visits&ot%5B%5D=assessments&at%5B%5D=-1&at%5B%5D=-2

**Comment by jonas0b1011001** [comment]
Do the following change to your script in [ical.js.gs line 92](https://github.com/derekantrican/GAS-ICS-Sync/blob/d99b8be73f5dd1d4185c8feab972930f47e7502e/ical.js.gs#L92)

replace
```
ICAL.TimezoneService.has(i)
```
with
```
ICAL.TimezoneService.has(i) &&
ICAL.TimezoneService.get(i).component
```

**Comment by chouston85** [comment]
Thank you! That got it working perfectly. Again, I cannot thank you enough for this script.
