### ISSUE TITLE
Only process all-day events

### ISSUE THREAD

**Issue by Royal2000H** [derekantrican/GAS-ICS-Sync#263]
I'm just getting started setting up this script to process events from an iCloud calendar to Google Calendar. The iCloud ICS is several MB in size (spans many years) so I haven't been able to sync directly. Finding this script may possibly be the workaround I needed - thank you!!

For cleanliness, I'd like to only import/sync the all-day events because I don't need the other events (with times) to come into Google Calendar. Is there a line somewhere I can most efficiently add this to?

**Comment by jonas0b1011001** [comment]
I suggest adding the following to [Helpers.gs line 155](https://github.com/derekantrican/GAS-ICS-Sync/blob/d99b8be73f5dd1d4185c8feab972930f47e7502e/Helpers.gs#L155)
```
result = result.filter(function(event){
    return (event.getFirstPropertyValue('dtstart').toString().indexOf("T") == -1);
  });
```

**Comment by Royal2000H** [comment]
Thank you! This worked!
