### ISSUE TITLE
Events from different calendars, sync to the same one with different colors, depending of the source calendar

### ISSUE THREAD

**Issue by J3R3M51** [derekantrican/GAS-ICS-Sync#264]
Hello,

Thank you again for this awesome script!

I want to use this script to sync some calendars with a single "Busy" calendar.
But, in this busy calendar, I need to manage events color depending of the source calendar.

At the moment, it's okay if the destination calendar is not the same for each source calendar, the color is well treated.
But, if some source calendars are set to by sync with a single another one, only ColorId of the first one is used and all events managed by the script have this same color.

Is there a way to fix it ?
Thanks

**Comment by jonas0b1011001** [comment]
Please copy the new code from github and see if that fixes it for you. Feel free to reopen the issue if you run into problems.

**Comment by J3R3M51** [comment]
It's working great ! Thanks a lot !
It's perfect !
