### ISSUE TITLE
Don't sync other events if a one day event already exists this day

### ISSUE THREAD

**Issue by J3R3M51** [derekantrican/GAS-ICS-Sync#265]
Hello,

Is it possible to add a condition to check first if a one day event already exists before syncing other events for this day ?
For my use, it would be very great!

Many thanks,
Jérémy

**Comment by jonas0b1011001** [comment]
I suggest adding the following to [Helpers.gs line 155](https://github.com/derekantrican/GAS-ICS-Sync/blob/d99b8be73f5dd1d4185c8feab972930f47e7502e/Helpers.gs#L155)
```
result = result.filter(function(event){
    var allDay = event.getFirstPropertyValue('dtstart').toString().indexOf("T") == -1;
    var date = event.getFirstPropertyValue('dtstart').toString().substring(0,10);
    var otherAllDayExists = result.find(function(elem){
        return elem.getFirstPropertyValue('dtstart').toString() == date;
    });
    return (allDay || (otherAllDayExists == undefined));
  });
```

**Comment by J3R3M51** [comment]
Thank you @jonas0b1011001 , it's working very great !!
Very quick answer ! Thanks a lot !
