### ISSUE TITLE
Zoom call links seem to be stripped out of description of synced event?

### ISSUE THREAD

**Issue by Nezteb** [derekantrican/GAS-ICS-Sync#266]
When an event includes a Zoom call, it seems to be getting stripped out of the event that is synced. I haven't made any of the script settings other than adding the ICAL url in the list.

Original:
![2022-04-12 12_07_11-Calendar _ Fastmail](https://user-images.githubusercontent.com/3588798/163018028-b0e0a78a-a0da-4bc3-a97f-6f5541ff7f4e.png)

GAS-ICS-Sync version:
![2022-04-12 12_07_28-Stoplight - Calendar - Week of April 11, 2022](https://user-images.githubusercontent.com/3588798/163018047-42aef2ec-1f56-43a2-954c-427d0829e634.png)

Here is an ICS string but since most of it is scrambled I don't know how helpful it will be: https://pastebin.com/raw/aBbeQtF5

My best guess is that something is failing on the string that is separating the main message from the automated Zoom call generated (see code snippet below). The separator lines seem to not be rendered by my email provider's UI (Fastmail).

```
<Original email>
-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
<Zoom call info here>
-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
```

**Comment by jonas0b1011001** [comment]
The first screenshot is from Fastmail UI?

Where is the *.ics coming from that you sync with the script?
Generally speaking, the script will not modify event descriptions in any way, my best guess is, that the info is already missing in the source file.

**Comment by Nezteb** [comment]
The ICS file comes from the Fastmail calendar settings:
![2022-04-12 13_00_11-Edit _ Fastmail](https://user-images.githubusercontent.com/3588798/163025629-8562cb58-bbbd-4858-9376-9ffdada2a414.png)

Here is another view of the Fastmail UI of the event:
![2022-04-12 13_01_53-Inbox](https://user-images.githubusercontent.com/3588798/163026084-6b45e2fc-a6d9-4473-9fa2-e74118d36e58.png)

**Comment by Nezteb** [comment]
I copied the description exactly from that Fastmail calendar event and copied it to a new event to reproduce this and it indeed still happens. Before doing that I added a log statement to see what the incoming calendar event looked like: https://github.com/derekantrican/GAS-ICS-Sync/blob/master/Helpers.gs#L364

And this is what the ical event has for a description:
```
{
    "component": [
        "vevent",
        [
            [
                "description",
                {},
                "text",
                "Hi Noah, \n\nYou have been invited to [...]\n\nWhen you are ready, just click on the provided Zoom link.\n\nIf you have any questions, please feel free to reach out to me.\n\n[...]\n\n-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-\nDo not edit this section of the description.\n\nJoin Zoom Meeting\n<Zoom link>\n\nView your event at <Calendar link>\n-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-"
            ]
        ]
    ]
}
```

So, the data is there at one point (despite the series of tildes and colons that Zoom includes in invite emails), but something happens to it before the new event is created. 🤔

**Comment by jonas0b1011001** [comment]
Manually create an event in gcal WebUI and use the string you posted above as description. Save the event, reopen and the second part of the description is missing.

I don't know why, but google seems to not like it.

**Comment by Nezteb** [comment]
Woah, how have I never noticed this before?

I guess that's something we can't control. I wonder if that's documented anywhere; I can't find anything on Google's side. 🤔

**Comment by Nezteb** [comment]
Even a description like this causes this:
```
asdf
-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
hello
-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
what's up
```

`hello` disappears on save. 🤔 

I've tried several subsets of the symbols to see which specific ones are causing this, but I can't figure it out yet.

**Comment by jonas0b1011001** [comment]
You have to break the pattern, editing [Helpers.gs Line 364](https://github.com/derekantrican/GAS-ICS-Sync/blob/master/Helpers.gs#L364) to look like this
`newEvent.description = icalEvent.description.replace("-", "");`
is enough to make it all appear and persist.

**Comment by Nezteb** [comment]
I'm just going to do:
`newEvent.description = icalEvent.description.replace("-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-", "");
😏 

Thank you for the help debugging this! Although this new series of symbols will now haunt my dreams.
