### ISSUE TITLE
Optional Color Parameter for targets

### ISSUE THREAD

**Issue by renenienaber** [derekantrican/GAS-ICS-Sync#267]
When synchronising multiple calendars into the same target calendar, it might be useful to add an Google-Color in the "sourceCalendars"-Array:
```
var sourceCalendars = [
   ["dummy-calendar.com/a-source-calendar.ics", "Target Calendar", "tangerine"],
   ["dummy-calendar.com/another-source-calendar.ics", "Target Calendar", "avocado"],
];
```

The color can be a optional entry.

**Comment by jonas0b1011001** [comment]
Is this different to the [current implementation](https://github.com/derekantrican/GAS-ICS-Sync/commit/663b1a36bf4a7611ae37984208dc68896d078a10)?

**Comment by jonas0b1011001** [comment]
> So when I say "_import calendar A into Z with color 'tangerine'_" and "_import calendar B into Z with color 'avocado'_", in calender Z all appointments of calendar A would appear in 'tangerine' color and all appointments of calendar B would appear in 'avocado' color.

That's exactly what it does. Be aware that the code on the repo is newer than v5.6.

**Comment by derekantrican** [comment]
Here's the PR: #243 . Note that the implementation uses the number values (eg "11") rather than the names. The basic color mapping is as follows:

```
"Default",   0, N/A
"Lavender",  1, "#7986cb"
"Sage",      2, "#33b679"
"Grape",     3, "#8e24aa"
"Flamingo",  4, "#e67c73"
"Banana",    5, "#f6c026"
"Tangerine", 6, "#f5511d"
"Peacock",   7, "#039be5"
"Graphite",  8, "#616161"
"Blueberry", 9, "#3f51b5"
"Basil",    10, "#0b8043"
"Tomato",   11, "#d60000"
```

**Comment by renenienaber** [comment]
> Here's the PR: #243 . Note that the implementation uses the number values (eg "11") rather than the names. The basic color mapping is as follows:
> 
> ```
> "Default",   0, N/A
> "Lavender",  1, "#7986cb"
> "Sage",      2, "#33b679"
> "Grape",     3, "#8e24aa"
> "Flamingo",  4, "#e67c73"
> "Banana",    5, "#f6c026"
> "Tangerine", 6, "#f5511d"
> "Peacock",   7, "#039be5"
> "Graphite",  8, "#616161"
> "Blueberry", 9, "#3f51b5"
> "Basil",    10, "#0b8043"
> "Tomato",   11, "#d60000"
> ```

Okay sorry, I wasn't aware of this! 

> > So when I say "_import calendar A into Z with color 'tangerine'_" and "_import calendar B into Z with color 'avocado'_", in calender Z all appointments of calendar A would appear in 'tangerine' color and all appointments of calendar B would appear in 'avocado' color.
> 
> That's exactly what it does. Be aware that the code on the repo is newer than v5.6.

The Readme of this project links to https://script.google.com/d/1BOk8MDLbLaHh6SwG1M1tsgNXjkcC-79LE0QoipRuTDxbO3fMVvqoROQD/edit?newcopy=true . Is this the newest version? I think not, because the Project Details there say, that it's last changed in 2021-05-13. That's the version I used here.
