### ISSUE TITLE
TypeError: Cannot read property 'parent' of null (line 2609, file "ical.js")

### ISSUE THREAD

**Issue by BigDaddyJoel** [derekantrican/GAS-ICS-Sync#272]
ics is from a 3rd party ... jobber.com

String below with parms removed should reproduce error.
 https://secure.getjobber.com/calendar/31775020257604768740206560738608046762586753217778/jobber.ics?at%5B%5D=1083647&ot%5B%5D=basic&ot%5B%5D=events&ot%5B%5D=visits&ot%5B%5D=assessments&at%5B%5D=-1&at%5B%5D=-2

A portion of email thread between Derek and myself pertaining to this follows:

--- snip ---

Joel,

I tried to set up the script with the parameterless url on my end and when running the "startSync" function manually, I get the following error: TypeError: Cannot read property 'parent' of null (line 2609, file "ical.js")

- Derek Antrican

On Wed, May 25, 2022 at 2:45 PM ############# wrote:
Hey Derek,

I won't bug you anymore after this as to not wear out my welcome.

Still no luck on my end.  I tried changing the Google cal timezone to match the tz from the ics which I think would be Coordinated Universal TIme (UTC+0).  I also manually added both the preferred ics with parms to Google and the ics without parms manually and both work / show up immediately (but of course the dumb 24hr sync delay is still there).  I tried changing the calendar name parm in your script to the same string as the ics string and tried a null string "" neither of which helped;   I removed access to the 3rd party app and re-added and then installed your script with both options as mentioned above.  This time, my calendar did immediately show the ics calendar with the parms under "My Calendars" but showed no items whatsoever.

**Comment by jonas0b1011001** [comment]
Hi, please have a look at #259 and change your code as suggested there.

**Comment by derekantrican** [comment]
@BigDaddyJoel - did @jonas0b1011001 's suggestion work for you?

**Comment by derekantrican** [comment]
Closing as there has been no response. Please comment again if this is still an issue
