### ISSUE TITLE
Out of memory error when running script

### ISSUE THREAD

**Issue by kareem** [derekantrican/GAS-ICS-Sync#273]
### Description of the problem

I use GAS-ICS-Sync to pull events from my Fastmail calendar to a Google cal.  I noticed a few events from my Fastmail calendar were not appearing on my Google Calendar.  I ran the sync manually and this error popped up:

<img width="1154" alt="Sync Fastmail calendar every 5 minutes - Project Editor - Apps Script 2022-05-27 11-17-08" src="https://user-images.githubusercontent.com/26123/170718184-68e8f6d1-331a-4b3b-8fa3-38670b1aaa68.png">

> Does the problem also exist if you use Google Calendar to subscribe to the calendar

I tried subscribing to the Fastmail ICS URL in Google Calendar [as described here](https://help.sportlyzer.com/hc/en-us/articles/207593579-Add-iCal-to-Google-Calendar).  It's been about 30 mins and I don't see ANY events imported yet.

> An input ics string that can reproduce the problem (you can remove sensitive information with https://derekantrican.com/icssanitizer)

I tried sanitizing my .ics file but got this error.  Maybe that's because it's 2.8MB?

<img width="398" alt="Mozilla Firefox 2022-05-27 11-28-49" src="https://user-images.githubusercontent.com/26123/170719861-3b9da36a-e296-4a52-a8c6-6875ded1dd53.png">

In any case you can grab the ICS file here - it's just free/busy info (this is the exact ICS that GAS is accessing):

https://www.dropbox.com/s/4g8j3uhxypzsn6w/Appointments.ics?dl=0

Any ideas how to fix?

**Comment by jonas0b1011001** [comment]
> Any ideas how to fix?

Reduce the amount of events. I don't really know how much memory a gas execution has available but 30k events is alot.

I assume you don't necessarily need to sync all events from the source (which has events scheduled for 2038). I would suggest you take a look at #221 and limit the range to whatever is viable for your use case.

**Comment by kareem** [comment]
> Just out of curiosity, could you add an additional Logger.log above 209 to reconfirm the issue is not caused by the parseResponses function.

Done.  The new line doesn't appear in the logs.  Looks like it's getting OOM in the `for` loop after fetching is complete:

<img width="1428" alt="Sync Fastmail calendar every 5 minutes - Project Editor - Apps Script 2022-05-27 13-11-48" src="https://user-images.githubusercontent.com/26123/170737975-fd43c2f1-1e31-44cb-8e4b-58e787df2393.png">

> If my assumption is true i suggest you sync to a fresh target calendar, that's probably the easiest way to get rid of the 30281 events.

That seemed to work, thanks for your help.  Was the issue that the 30k events were on the calendar? Or the ics?


Only thing I ran into was this.  The script made the right default assumption to use GMT.

```
Timezone Z unsupported!
Using Timezone Etc/GMT!
```

**Comment by jonas0b1011001** [comment]
> Was the issue that the 30k events were on the calendar? Or the ics?

The events in the calendar. Limiting the date range should prevent this from happening again.


> Only thing I ran into was this. The script made the right default assumption to use GMT.

Those are info only, no need to worry.

**Comment by kareem** [comment]
@jonas0b1011001 thanks again for your help!
