### ISSUE TITLE
Wiki Step 9 causes errors due to duplicating the tasks and calendar services already existing in the appsctipt.json file

### ISSUE THREAD

**Issue by topherbuckley** [derekantrican/GAS-ICS-Sync#281]
>"appsscript.json" has errors: Found a service identifier used more than once: Calendar

It can just be removed as per:

https://github.com/topherbuckley/GAS-ICS-Sync-wiki/commit/feda189ee95498dc8254979f86c3dcfa181a2c7c

**Comment by derekantrican** [comment]
Thanks! Updated
