### ISSUE TITLE
Prefix events with local source calendar names

### ISSUE THREAD

**Issue by jpcjpc69** [derekantrican/GAS-ICS-Sync#285]
*Before submitting, know that many features are met with skepticism as we try to make most features relevant to **all** users*
OK
**Please provide the following information:**

- Please describe the feature you would like to see (it would be helpful if you could add any necessary screenshots, [ics strings](https://github.com/derekantrican/GAS-ICS-Sync/wiki/Debugging-tips#using-an-explicit-ics-string-instead-of-an-url), etc)

Firstly - thanks for this awesome script!  It's going to help a lot!
Right now, your code seems to be able to identify the destination calendar name in google calendar - it's based on the name of the calendar. 
I've currently got about 5 "read only" type public calendars for various family sports events.  Some of these calendars do not do a good job with event titles  - just calling things "practice" so when I see them integrated, it is hard to know what calendar they came from.   It would be great if you can somehow pull the source calendar "name" field and allow us to prepend that to the event title.  For example "Eileen Hockey" + (the event name).

That would allow us to know from which calendar it came.
Hope that makes sense.

**Comment by jonas0b1011001** [comment]
Have you tried [`var addCalToTitle = true;`](https://github.com/derekantrican/GAS-ICS-Sync/blob/7523821ab94c2b01ea32399bd6c83b7665452282/Code.gs#L42)?

**Comment by jpcjpc69** [comment]
Yes, but that seems to put in the calendar originator or something - I can
only guess that not all calendars have this setup properly.  I have one
calendar where the value is blank:
https://calendar.google.com/calendar/ical/b0ld0e9lib8mij9o2mmtu0isbfr7j2er%40import.calendar.google.com/public/basic.ics

and another where it says "Jr. Sharks Events" :
https://calendar.google.com/calendar/ical/r4fv6ktfor70viani07ku6q5p9pvg1v4%40import.calendar.google.com/public/basic.ics

Other calendars seem to put more descriptive info into the title of each
event - I'm guessing that these are the individual event titles - like
"2022-23 Cougars 8U" in this calendar:

https://calendar.google.com/calendar/ical/bt8jcisdi48khr6gg42utq8c6968fr7u%40import.calendar.google.com/public/basic.ics

Some of these titles can be so long that they don't work in the calendar
view either.
Open to ideas here!
Thanks!
-pat

**Comment by jonas0b1011001** [comment]
> Yes, but that seems to put in the calendar originator or something - I can only guess that not all calendars have this setup properly.

Maybe have a look at #144 for custom prefixes.

**Comment by derekantrican** [comment]
Closing as there has been no response. Please comment again if this is still an issue
