### ISSUE TITLE
Sync to default calendar?

### ISSUE THREAD

**Issue by chaoscreater** [derekantrican/GAS-ICS-Sync#286]
Hi there,

Is it possible to sync to the default calendar? If I type the name of the default calendar, it creates a new calendar with the same name and syncs into that. I just want it to sync into the default one.

**Comment by jonas0b1011001** [comment]
Use your mail address as calendar name, that should work.

**Comment by chaoscreater** [comment]
> Use your mail address as calendar name, that should work.

Just tested and it works! Perfect!

Thank you so much.
