### ISSUE TITLE
Calendar Sync Error on devices

### ISSUE THREAD

**Issue by supermozzie** [derekantrican/GAS-ICS-Sync#288]
Hi all,

Since 30th Sep 2022, the calendar created by the GAS-ICS-Sync script no longer synchronises to my devices (Android AND iOS). However, the script is still running with no error and all the changes are reflected on my web browser Google calendar. On the Android phone and iPad, other calendars are synchronising, just not this one. On the Android phone, there is a message "Sync error".

I have tried to reset the app cache and storage on my devices and restarted them. Nothing works.

Any ideas? Is this a known issue? Any permissions I have to set / reset?

Thank you so much for your help in advance.

Kind regards,
supermozzie

**Comment by derekantrican** [comment]
Can you provide a screenshot of that error? It sounds like an issue with the Google Calendar app or Android. If that is the case, you may be able to get support by going to https://one.google.com/support
