### ISSUE TITLE
Using vtimezone make script very long to execute

### ISSUE THREAD

**Issue by boillodmanuel** [derekantrican/GAS-ICS-Sync#29]
Hi,
I figure out than using `vtimezone` make the script very long to execute. 
If I remove all code related to `vtimezone` in `Code.js`, execution time decrease from 120s to 2s.
The time is taken by `toJSDate()` method. I don't know why exactly. 
But removing all `vtimezone` occurrences fixes it (for me).

By the way, thanks for your very useful script.

Manuel

**Comment by derekantrican** [comment]
Thanks for reporting this. I'll look into it

**Comment by derekantrican** [comment]
Obviously `toJSDate()` is a very important method and timezones are very important to maintain. One thing I see that we might be able to improve is rather than using `new ICAL.Timezone(vtimezone);` multiple places, we could probably pass around a global `var timezone = new ICAL.Timezone(vtimezone);` object rather than the `var vtimezone` string. That might lead to a time improvement

**Comment by boillodmanuel** [comment]
During my tests, time was great without using timezone, and Google server
was something like UTC-11 and myself UTC+1.

I still was using toJSDate, but without timezone this method doesn't call
the underlying toUnixTime() method which is very slow (I don't know why).

Le dim. 17 févr. 2019 à 19:30, Derek Antrican <notifications@github.com> a
écrit :

**Comment by boillodmanuel** [comment]
Ok, I spent more time in analysis.

So, as you said, you must register timezone.

Registering once at the beginning is enough :
```js
ICAL.TimezoneService.register(vtimezone);
```

Then, you don't need to set date zone, so you can comment the following lines :
```js
if (vtimezone != null)
  dtstart.zone = new ICAL.Timezone(vtimezone);
...
if (vtimezone != null)
    dtend.zone = new ICAL.Timezone(vtimezone);
```

To fix the very long time, I found a workaround. In cal.js, line 4357, add the following condition to do the work only one time :
```js
if (this.expandedUntilYear >= aYear) {
        return
      }
```
Which will looks like :
```js
    _ensureCoverage: function(aYear) {
      if (this.expandedUntilYear >= aYear) {
        return
      }
      if (ICAL.Timezone._minimumExpansionYear == -1) {
        var today = ICAL.Time.now();
        ICAL.Timezone._minimumExpansionYear = today.year;
      }
```
Each calls was lasting about 5s - after the workaround, only the first call lasts 5s.

The script lasts now 10s against 120s (depending on the number of events)

**Comment by derekantrican** [comment]
@boillodmanuel When I was implementing ICAL.js, I found some issues where I set the timezone "globally" (ie `ICAL.TimezoneService.register(vtimezone);`) but some events were still not being created on the calendar in the correct timezone. That is why I added the `dtstart.zone = new ICAL.Timezone(vtimezone);` lines. 

I just made a wiki page on doing testing. Can you please do tests with your changes and those ics files? https://github.com/derekantrican/GAS-ICS-Sync/wiki/Testing

Thanks

**Comment by nanobrad** [comment]
I dug through the ical.js code... ```ICAL.TimezoneService.register(vtimezone)``` does **not** work as a global setting. TimezoneService is just a singleton to cache Timezones.

If the individual vevent component doesn't include a timezone, then ical.js defaults to ```ICAL.Timezone.localTimezone```.

I think the fix is to:
1. Check the zone against ```ICAL.Timezone.localTimezone``` to determine if the "global" calendar ```vtimezone``` should be used.
2. Use ```ICAL.TimezoneService.get()``` instead of creating a new ```ICAL.Timezone``` object.

Here is my code from ```ConvertToCustomEvent```:
```
  if (vtimezone != null && dtstart.zone === ICAL.Timezone.localTimezone) {
    var default_tzid = vtimezone.getFirstPropertyValue('tzid');
    if (default_tzid != null) {
      dtstart.zone = ICAL.TimezoneService.get(default_tzid);
    }
  }

  console.time("toJSDate() calls")  
  event.startTime = dtstart.toJSDate();
  
  if (dtend == null) {
    console.log('dtend is null, setting to default duration');
    event.endTime = new Date(event.startTime.getTime() + defaultDuration * 60 * 1000);
  } else {
    if (dtend.zone === ICAL.Timezone.localTimezone) {
      console.log('dtend has no timezone, setting to dtstart.zone');
      dtend.zone = dtstart.zone;
    }
    event.endTime = dtend.toJSDate();
  }
  console.timeEnd("toJSDate() calls")  
```

This results in the first call to toJSDate() taking about 400ms, but the remaining calls are all ~2ms.

I can now process 75 iCal events in 520ms instead of 13 seconds.

As an aside, it is now much more important to throttle the creation of Google Calendar events to avoid hitting the undocumented rate limit.

**Comment by derekantrican** [comment]
@nanobrad Wow you have done a lot more for this repository than I would have expected for someone who (I assume) found this issue through the one on the ICAL.js repo. I'll definitely implement your suggestions soon.

As far as throttling Google Calendar event creation - that is definitely something that has to be done.

**Comment by nanobrad** [comment]
@derekantrican Actually, thank you. I found all of this (including Google Apps Script) because I was trying to solve the ICAL -> Google Calendar lag. Finding your working solution was great. I just ended up going down the rabbit hole trying to figure out why it was running so slow.

**Comment by staffanf** [comment]
Feedback: I just put the changes from https://github.com/derekantrican/GAS-ICS-Sync/issues/29#issuecomment-485009746 in my script and my execution time went from ~200s to 35s and all the events still seems to be at the correct times.

**Comment by derekantrican** [comment]
@staffanf Can you confirm that #51 also works? If not, we'll have to incorporate those changes too

**Comment by derekantrican** [comment]
### We just released [v5.0](https://github.com/derekantrican/GAS-ICS-Sync/releases/tag/5.0)!

Please check to see if this is fixed.

**Comment by boillodmanuel** [comment]
I tried it today and everything seems OK.
Great work by the way for this new version

**Comment by derekantrican** [comment]
Thanks @boillodmanuel . I'll close this now unless someone else in this thread reports an issue
