### ISSUE TITLE
Using URL parameter from ics

### ISSUE THREAD

**Issue by 3guk** [derekantrican/GAS-ICS-Sync#290]
Hello Everyone,

Some of the ICS files that I use / sync have an URL parameter - that links to the correct meeting request / more information about that particular calendar entry.

When syncing to the ics file in iCal - it seems like the URL is preserved and is clickable for the user.

When I'm using this script - it would appear that either Google or this script strips it - and indeed looking in my Google calendar there appears to be no option to add a clickable URL to an event.

I've had a brief look through the Helper.gs file and it appears this script is set up to handle URLs - my question is, what does it actually do to them ? How hard would it be to modify the script so that the URL shows up in the Google Event Description ?

Apologies if this sounds like a really basic question - only just getting to grips with this sort of stuff.

Below is the VEVENT format:

```
BEGIN:VEVENT
DTSTART:20220715T060000Z
DTEND:20220717T170000Z
SUMMARY:Test Event
DESCRIPTION:INTL001 205464
LOCATION:Cologne
DTSTAMP:20220110T163624Z
CREATED:20220110T163624Z
LAST-MODIFIED:20220830T085225Z
SEQUENCE:1661849545
UID:8bf82a90-8af1-0139-3bf2-12fbcfdb731a/opportunities/122
URL:http://eventmeetingwebsite.com/event122
ORGANIZER;CN=
END:VEVENT
```

**Comment by derekantrican** [comment]
Thanks for providing the VEVENT. Can you provide a screenshot of what shows up for the VEVENT in Google Calendar?

**Comment by 3guk** [comment]
Hi Derek,

Screenshot should be attached - it would appear the URL field always gets discarded.

For me it would be awesome if it could be added to description so that a user could click through.


<img width="1092" alt="Screenshot 2022-10-13 at 18 25 42" src="https://user-images.githubusercontent.com/263355/195652823-87439b4a-8e70-4f30-8aae-6a1b3f2fd131.png">

**Comment by jonas0b1011001** [comment]
That's a bug.

Add
`newEvent.source.title = "link";`
after [this line](https://github.com/derekantrican/GAS-ICS-Sync/blob/7523821ab94c2b01ea32399bd6c83b7665452282/Helpers.gs#L340) in Helpers.gs.

Thanks for reporting!

**Comment by derekantrican** [comment]
@3guk I've merged in @jonas0b1011001 's change (thanks, Jonas!). For you - it might just be easiest to incorporate the change into your copy of the script since it's just 1 line. Check #291
