### ISSUE TITLE
Script runs without errors but doesn't add events to calendar

### ISSUE THREAD

**Issue by ryanbbrown** [derekantrican/GAS-ICS-Sync#293]
I didn't modify the script at all, other than changing the frequency and using the example sourceCalendars mapping. [Here](https://script.google.com/d/1s_NWWTHqf-QtPZk2TNaHFBlkIwUeIG8veUlocJtywAyncIf26H5zdos3/edit?usp=sharing) is the script. I have a calendar called test_cal. The script runs without error, but events never get added. I gave the script all the permissions it asked for when I ran it for the first time.

**Comment by derekantrican** [comment]
First, I don't recommend every minute. I would recommend every 5 minutes at the fastest, or every 15 minutes if that's sufficient for your needs.

Can you try running the "startSync" function and see if that gives any errors?

**Comment by jonas0b1011001** [comment]
> and using the example sourceCalendars mapping

The example ics isn't actually working currently as it is not completely conforming to the ical standard - we should really change the url.
1. Just use any other ics you want to sync and it should work or
2. Change [line 1323](https://github.com/derekantrican/GAS-ICS-Sync/blob/6438b551534e191380b4f10f327ac70a90d36599/ical.js.gs#L1323) in ical.js.gs to make it ignore the wrong syntax:
`strict: false,`

**Comment by ryanbbrown** [comment]
I made those changes and it works now, thank you!
