### ISSUE TITLE
Resource has been deleted

### ISSUE THREAD

**Issue by kdwhitmire** [derekantrican/GAS-ICS-Sync#297]
I was having an issue with Google locking me out because of too many api calls.  The ical calendars I use in the script don't contain very many entries (largest is just over 100), but they all contained "cancelled" events that kept getting recreated (and deleted) every time the script ran.  Upon suggestion by @jonas0b1011001, I changed the showDeleted:true property from false.  However, I had thousands of entries in my Deleted Items and the script timed out trying to process all of them.  I cleared my Google Deleted Items thinking that would provide a clean start.  However, now when the script runs, it shows 349 events from the Google calendar and 111 from the ical.  After it goes through normal processing, I get "Done processing events", then "Deleting old event xxxxxxxxx" (whatever the event id is) and the code errors out with:

GoogleJsonResponseException: API call to calendar.events.delete failed with error: Resource has been deleted
    at [unknown function](Helpers:596:27)
    at callWithBackoff(Helpers:877:16)
    at processEventCleanup(Helpers:595:9)
    at startSync(Code:264:7)

It seems the event(s) is in GAS-ICS-Sync "memory" and tries to delete from Google where it now doesn't exist which throws the error.

**Comment by kdwhitmire** [comment]
Per @jonas0b1011001, I added "calendarEvents[i].status !="cancelled" &&" inline in Helpers.gs line 627 before "calendarEvents[i].recurringEventId == null".  This allowed for events to be deleted correctly.

**Comment by derekantrican** [comment]
Glad to hear jonas' suggestion worked for you. Closing this out.
