### ISSUE TITLE
I don't want any past (recurring) event to be deleted

### ISSUE THREAD

**Issue by azwiep** [derekantrican/GAS-ICS-Sync#298]
Hi, thanks for the great script. makes my lif eeasier, but for one thing:

Currently all my recurring events (not my normal events, they stay) are deleted as soon as they become past. I need all these events to stay in my calendar, even if the last event has passed. Is tehre a way to do so. These are my settings:

var onlyFutureEvents = true;         
var addEventsToCalendar = true;        
var modifyExistingEvents = true;     
var removeEventsFromCalendar = false;

Hope this is a minor thing, mamny thanks in advance!

Nouk

**Comment by jonas0b1011001** [comment]
Recurrence instances are not explicitly deleted by the script, they get removed by editing the recurrence rule of the main event, google calendar handles all the rest. Therefore _removeEventsFromCalendar_ does not apply to recurrence instances. Your best bet is to set `onlyFutureEvents = false` if that does not work the past instances are removed by your source.

**Comment by derekantrican** [comment]
@azwiep - did you have a chance to try @jonas0b1011001 's suggestion?

**Comment by derekantrican** [comment]
Closing as there has been no response. Please comment again if this is still an issue
