### ISSUE TITLE
Script run and calendar added, but zero events are displayed.

### ISSUE THREAD

**Issue by naibarra** [derekantrican/GAS-ICS-Sync#300]
**Description of the problem**:
I'm starting to use this script because of the Google Calendar problem. However, whenever I run the script (or I leave it running), the calendar I'm subscribing to is added, but no calendar events are displayed on my Google Calendar. I tested with different GWorkspaces Calendars and even with a regular @gmail account, and I got the same problem.

I was initially using an ICS from my company's internal calendar (the reason why I started looking into this script solution), however, after starting to receive this problem, I switched to a public ICS like the "US Holidays" one that comes with the script, and I had the same results. 

Btw, I gave all the permissions required and followed the instructions exactly as they are in the script notes.

**Screenshots**
This is what I get when I run the script, using the "US Holidays" ICS:
![image](https://user-images.githubusercontent.com/59583059/211171167-e828e26b-6713-46a9-9a2f-b58bf60a03e9.png)
And this is what I get if I manually add the "US Holidays" ICS, what I expect to receive as a result of the script:
![image](https://user-images.githubusercontent.com/59583059/211171179-5d9d79b2-809a-4611-98d5-b7c4ad8cdee0.png)

Anyways, I already spent a lot of time trying to make this work, I followed the provided instructions, and all permissions were provided. So, if you could throw me some lights here, I'll really appreciate it. Let me know if you want me to share anything with you, the ICS I'm using is https://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics

Thanks

**Comment by jonas0b1011001** [comment]
The example ics from the script actually has bad syntax which is why it's not processed (@derekantrican if you got time could you change that url to any other ics in [this](https://script.google.com/d/1BOk8MDLbLaHh6SwG1M1tsgNXjkcC-79LE0QoipRuTDxbO3fMVvqoROQD/edit?newcopy=true)  version?) 

Are the any errors in the execution log when using the ics you actually want to sync?

**Comment by naibarra** [comment]
Yes, using the one I actually want to sync, I get the following error:
![image](https://user-images.githubusercontent.com/59583059/211172229-624fcf9d-4721-417b-a868-d0522fc7698e.png)

Error: invalid date-time value: "2022-01-01T::"
   at ICAL.Time.fromDateTimeString(ical.js:5900:13)
   at decorate(ical.js:781:28)
   at _decorate(ical.js:2938:47)
   at _hydrateValue(ical.js:2921:44)
   at getFirstValue(ical.js:3067:19)
   at getFirstPropertyValue(ical.js:2499:21)
   at _firstProp(ical.js:9322:29)
   at get startDate(ical.js:9138:19)
   at createEvent(Helpers:266:16)
   at processEvent(Helpers:197:18)

Huhm, strange, I just noticed it says "processing 30 events" and then the errors. So, it is finding the events from the ical, but not adding it because of the error below. Any clue @jonas0b1011001 ?, and thanks for replying.

**Comment by jonas0b1011001** [comment]
Do #2 from [this comment](https://github.com/derekantrican/GAS-ICS-Sync/issues/293#issuecomment-1304734974) and you're set.

Your ics has the same issue as the example url.

**Comment by naibarra** [comment]
@jonas0b1011001 , sir, hats off. That fixed the problem. 
Thank you so much.

**Comment by derekantrican** [comment]
> The example ics from the script actually has bad syntax which is why it's not processed (@derekantrican if you got time could you change that url to any other ics in [this](https://script.google.com/d/1BOk8MDLbLaHh6SwG1M1tsgNXjkcC-79LE0QoipRuTDxbO3fMVvqoROQD/edit?newcopy=true) version?)
> 
> Are the any errors in the execution log when using the ics you actually want to sync?

Thanks for the ping. I think the one I have in https://derekantrican.com/icssanitizer (https://p24-calendars.icloud.com/holidays/us_en.ics) works so I'll update that in various places.
