### ISSUE TITLE
organizer synchronization  and URL facebook event

### ISSUE THREAD

**Issue by GabiPerieteanu** [derekantrican/GAS-ICS-Sync#302]
Hello,

I noticed that the Organizer and URL Facebook event is not synchronized.
My facebook calendar also contains the organizer, in the google calendar the organizer does not appear.
Any idea why it doesn't bring this field?
https://www.facebook.com/events/ical/upcoming/?uid=100072261342209&key=b2iHGfdm5YTXDRF6
https://calendar.google.com/calendar/ical/l7vibtpas72dq2o002rdukrub4%40group.calendar.google.com/public/basic.ics

Thanks

**Comment by jonas0b1011001** [comment]
> URL Facebook event is not synchronized

This was fixed in v5.7, please update to the latest release from this repo.


> Organizer is not synchronized

Google calendar does not show the organizer in the web UI. You could set _var addOrganizerToTitle = true;_.

**Comment by GabiPerieteanu** [comment]
And you can't put the organizer and facebook event url on a separate line?
here why is it possible?
(I don't have the organizer here :(  )
https://calendar.google.com/calendar/ical/ba8r83n0b1s8gjhqiksk036rhrj4la3k%40import.calendar.google.com/public/basic.ics

you cannot create a function to bring the organizer in any of the calendars?

I added an external Facebook calendar
![image](https://user-images.githubusercontent.com/110666277/212694551-a8cc80b6-7a2c-487b-9fc9-e834646b3682.png)

Thanks

**Comment by jonas0b1011001** [comment]
> And you can't put the organizer and facebook event url on a separate line?

No because we can't change the way google is presenting the events. All we can do is add the info to the event title (as descibred in my first comment) or description.

> you cannot create a function to bring the organizer in any of the calendars?

We can add them to the events but they will not show or export. You'd have to ask Google to change the way their calendar works.

**Comment by GabiPerieteanu** [comment]
Ok.
Thank you a lot
