### ISSUE TITLE
calendar.events.update failed with error: "Invalid start time"

### ISSUE THREAD

**Issue by bennesp** [derekantrican/GAS-ICS-Sync#303]
GAS-ICS-Sync only returns errors like the following now:

![Screenshot 2023-01-16 alle 12 49 20](https://user-images.githubusercontent.com/5445545/212698093-a23f55e3-06b8-4448-9a99-869b6cd60914.png)

Adding some logs I have the error happening with this calendar event:

```json
{
  "start": {
    "dateTime": "2022-12-19T10:30:00",
    "timeZone": "America/Chicago"
  },
  "end": {
    "dateTime": "2022-12-19T11:30:00",
    "timeZone": "America/Chicago"
  },
  "status": "confirmed",
  "summary": "This is the summary ",
  "description": "A very long description",
  "location": "Microsoft Teams Meeting",
  "visibility": "public",
  "transparency": "opaque",
  "reminders": {
    "useDefault": true,
    "overrides": []
  },
  "recurrence": [
    "RRULE:FREQ=WEEKLY;UNTIL=20230118T163000Z;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR;WKST=SU",
    "EXDATE;TZID=Central Standard Time:20221228T103000,20221229T103000,20230102T103000,20230116T103000"
  ],
  "extendedProperties": {
    "private": {
      "MD5": "72,22,-13,-121,9,1,103,-20,-24,-17,-68,29,-31,44,-97,62",
      "fromGAS": "true",
      "id": "<CENSORED>"
    }
  }
}
```

The event above is taken right before the update call as per the stacktrace.

I don't have the sensitivity to understand if this is supposed to be wrong or if it is a bug in GAS-ICS-Sync, I am looking for help to understand this.

Thanks

**Comment by jonas0b1011001** [comment]
I don't see anything wrong in the event data. Does this happen on all events on every run?

Could you please update to v5.7 so we are talking about the same code.
