### ISSUE TITLE
Event recreated every time I disable a notification from Thunderbird.

### ISSUE THREAD

**Issue by E-Concept-Applications** [derekantrican/GAS-ICS-Sync#306]
Hello,

I use my Google calendar from Thunderbird, and GAS-ICS-Sync allows me to synchronize GLPI events on my Google calendar.
Everything works well except for one detail:
When an event arrives, I have a notification displayed by Thunderbird (normal), and if I click on "Disable" as I do for any other event, it is automatically recreated by the script at the next execution...

For now, the only "solution" I found is to disable the sync of past events... But I mustn't disable Thunderbird's notification until the event is finished, otherwise, it is recreated anyway...

A solution to avoid this ?

Thank you!

Translated with www.DeepL.com/Translator (free version)

**Comment by jonas0b1011001** [comment]
Have you tried the different _addAlerts_ options in the settings section?

**Comment by derekantrican** [comment]
@E-Concept-Applications - did you look into what @jonas0b1011001 suggested?

**Comment by derekantrican** [comment]
Closing as there has been no response. Please comment again if this is still an issue
