### ISSUE TITLE
All day meetings end early (and might not be synchronized correctly) from outlook

### ISSUE THREAD

**Issue by TotgezocktSV** [derekantrican/GAS-ICS-Sync#331]
### The problem

When creating a event in outlook like this:
![image](https://user-images.githubusercontent.com/59968686/229508190-f040dda6-6130-4ea7-a006-d648a94c3fb4.png)

Example:

From 00:00
To 00:00
Duration 1 Day

Weekly 
Every 1 week(s) on
Monday, Tuesday, Wednesday

Starts: Monday April 3td 2023 
Ends after 3 events

Creating 3 events in summary.
Monday, Tuesday and Wednesday

The event will be synced as 2 events like this:
![image](https://user-images.githubusercontent.com/59968686/229509534-383da007-e4ad-40fc-9647-5395484e974d.png)
![image](https://user-images.githubusercontent.com/59968686/229509605-50829140-112d-4289-94e2-fd708f17eba8.png)

April 3td and 4th 2023
all-day: yes
Weekly monday, tuesday, wednesday till April 4th 2023

But i'm pretty sure this should be till April 5th not 4th, with a total of 3 events.

I hope this .ics is sufficient. (Uploaded as .txt since .ics upload is not supported)
[Test.ics.txt](https://github.com/derekantrican/GAS-ICS-Sync/files/11138271/Test.ics.txt)

Another thing is, that when i (for example) delete the event on April 4th, this update will not be reflected in google calendar after the sync. If needed i can report this as a separate bug though.

### Version of GAS-ICS-Sync

5.7

### Additional information & file uploads

Settings:  (Changed nothing, but for completion)
```
var howFrequent = 15;                  // What interval (minutes) to run this script on to check for new events
var onlyFutureEvents = false;          // If you turn this to "true", past events will not be synced (this will also removed past events from the target calendar if removeEventsFromCalendar is true)
var addEventsToCalendar = true;        // If you turn this to "false", you can check the log (View > Logs) to make sure your events are being read correctly before turning this on
var modifyExistingEvents = true;       // If you turn this to "false", any event in the feed that was modified after being added to the calendar will not update
var removeEventsFromCalendar = true;   // If you turn this to "true", any event created by the script that is not found in the feed will be removed.
var addAlerts = "yes";                 // Whether to add the ics/ical alerts as notifications on the Google Calendar events or revert to the calendar's default reminders ("yes", "no", "default").
var addOrganizerToTitle = false;       // Whether to prefix the event name with the event organiser for further clarity
var descriptionAsTitles = false;       // Whether to use the ics/ical descriptions as titles (true) or to use the normal titles as titles (false)
var addCalToTitle = false;             // Whether to add the source calendar to title
var addAttendees = false;              // Whether to add the attendee list. If true, duplicate events will be automatically added to the attendees' calendar.
var defaultAllDayReminder = -1;        // Default reminder for all day events in minutes before the day of the event (-1 = no reminder, the value has to be between 0 and 40320)
                                       // See https://github.com/derekantrican/GAS-ICS-Sync/issues/75 for why this is neccessary.
var overrideVisibility = "";           // Changes the visibility of the event ("default", "public", "private", "confidential"). Anything else will revert to the class value of the ICAL event.
var addTasks = false;

var emailSummary = false;              // Will email you when an event is added/modified/removed to your calendar
var email = "";                        // OPTIONAL: If "emailSummary" is set to true or you want to receive update notifications, you will need to provide your email address
```

**Comment by jonas0b1011001** [comment]
For me the *.ics you provided produces 3 events as expected.

<img width="579" alt="Bildschirm­foto 2023-04-03 um 16 11 12" src="https://user-images.githubusercontent.com/43352574/229535581-5454ae28-b2d3-4cbd-bad4-2c676dbe497f.png">

Orange: Sync via script
Blue: Import via webinterface

**Comment by TotgezocktSV** [comment]
Seems like the .ics is different when selected and exported specifically, should have tested it before sorry.
This .ics contains the corresponding VEVENT from the "big" .ics . (Naming is a bit different, because this .ics doesn't contain any data.)

[Test.ics.txt](https://github.com/derekantrican/GAS-ICS-Sync/files/11139542/Test.ics.txt)

Unfortunately, the issue also occurs when importing manually, so i assume this might actually be an outlook bug.
