### ISSUE TITLE
[Request] - Option to remove future events only (leave past events unchanged)

### ISSUE THREAD

**Issue by jimstowe** [derekantrican/GAS-ICS-Sync#344]
### Describe the solution you'd like

I have the following options set in the script:
onlyFutureEvents = false
addEventsToCalendar = true
modifyExistingEvents = true
removeEventsFromCalendar = true

One of the ical feeds that I'm monitoring stops sending "past" events after a few days.  I would like those events to remain on the google calendar.  I would like an option that adds past AND future, but only removes/modifies current/future events.  That would leave past events unchanged.

**Comment by jonas0b1011001** [comment]
#317 added the option to master branch. You can manually update by following this [guide](https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually).

**Comment by Nickxsch** [comment]
Oh wow, apparently, my instance wasn't up to date. Thanks @jonas0b1011001!
