### ISSUE TITLE
[Request] Allow custom prefix for imported calendars

### ISSUE THREAD

**Issue by Nickxsch** [derekantrican/GAS-ICS-Sync#345]
### Describe the solution you'd like

We have the `var addCalToTitle = true;  // Whether to add the source calendar to title` parameter to somewhat discern different source calendars, but unfortunately this does not help in case of Microsoft Outlook calendars as you cannot change the default calendar name.

Since we had this cool feature to select a color for each source in the sourceCalendars variable, I was wondering if we could add a name or prefix string in there as well, to add to titles of events. That way you could have one calendar with multiple sources and each event clearly shows the source, i.e.: "(Work) Event title" and "(Sports Team) Awesome event thingy".

It is indeed a tiny feature, maybe not for everyone and I might end up looking for a way to append it to the script myself, but I thought I might share it here first :-) I've put my bags in multiple baskets and also voted on [a Microsoft feedback item/idea](https://feedbackportal.microsoft.com/feedback/idea/02594203-bf92-ed11-a81b-6045bdaf6a9e) to make it possible to rename the default calendar in Outlook.

Anyhow, great script, thanks, and keep on doing awesome things.

**Comment by jonas0b1011001** [comment]
Have a look at #144 for a **very** old example of how it can be done.
