### ISSUE TITLE
Changing password invalides events url key

### ISSUE THREAD

**Issue by Joel-INTO** [derekantrican/GAS-ICS-Sync#35]
This is possibly because I'm working from my own script which hasn't been kept up to date with this repo, but thought I'd add it here in case this hasn't been caught yet.

Thanks!

**Comment by JoelBalmer** [comment]
(Ah, opened that from my other account!)

**Comment by derekantrican** [comment]
@JoelBalmer So is this because you were using a different account? If not, could you provide some more repro steps/screenshots/other information?

**Comment by JoelBalmer** [comment]
Oh sorry, I just meant I opened the issue from a different github account, which was confusing.

To reproduce:
1. Copy your current facebook ical URL from the script
2. Paste into browser and hit enter (it should download an ics file)

Now change your facebook password. Once logged out and back in again, repeat above steps. You should see **_Sorry, this URL is invalid or has expired._**

Here is an example URL (the key query param is now an invalid key):

https://www.facebook.com/events/ical/upcoming/?uid=563891140&key=AQBHTklxXOQJHIYP

**Comment by derekantrican** [comment]
Ah, so it changes the URL if you change your FB password. I think the error the script gives is clear enough and not something we need to fix

**Comment by JoelBalmer** [comment]
Fair enough, although I actually didn't realise this was the problem at first, I just one day noticed all my synced events had been deleted, so I believe currently if the URL changes it just processes the bad URL anyway, which removes all the events from the Cal. Might be worth error checking the data returned from the URL to see whether it contains "Sorry, this URL is invalid or has expired" or similar check. Cheers!
