### ISSUE TITLE
Login information disallowed

### ISSUE THREAD

**Issue by berbigou** [derekantrican/GAS-ICS-Sync#363]
### The problem

While trying to use URL https://user:password@nextcloud.server/blabla for my ics, I got "Login information disallowed".
Digging on Internet gave : https://stackoverflow.com/questions/56821118/how-do-i-fix-login-information-disallowed-error-from-google-script : Bilal Akbar answer 

I changed Helpers.gs lines 81 and 82 :
      var urlResponse = UrlFetchApp.fetch(url, { 'validateHttpsCertificates' : false, 'muteHttpExceptions' : true ,"headers": {
                "Authorization": "Basic " + Utilities.base64Encode("`user:password`")
and use only URL https://nextcloud.server/blabla

and TADAAAH ! all went well.

So I give you that.

By the way, as my scripts was not verified, I had to use Edge instead of Firefox to authorize it...

### Version of GAS-ICS-Sync

var thisVersion = 5.7

### Additional information & file uploads

/*,
  ["icsUrl2", "targetCalendar2"],
  ["icsUrl3", "targetCalendar1"]
  
];*/

var howFrequent = 15;                  // What interval (minutes) to run this script on to check for new events
var onlyFutureEvents = false;          // If you turn this to "true", past events will not be synced (this will also removed past events from the target calendar if removeEventsFromCalendar is true)
var addEventsToCalendar = true;        // If you turn this to "false", you can check the log (View > Logs) to make sure your events are being read correctly before turning this on
var modifyExistingEvents = true;       // If you turn this to "false", any event in the feed that was modified after being added to the calendar will not update
var removeEventsFromCalendar = true;   // If you turn this to "true", any event created by the script that is not found in the feed will be removed.
var addAlerts = "yes";                 // Whether to add the ics/ical alerts as notifications on the Google Calendar events or revert to the calendar's default reminders ("yes", "no", "default").
var addOrganizerToTitle = false;       // Whether to prefix the event name with the event organiser for further clarity
var descriptionAsTitles = false;       // Whether to use the ics/ical descriptions as titles (true) or to use the normal titles as titles (false)
var addCalToTitle = false;             // Whether to add the source calendar to title
var addAttendees = false;              // Whether to add the attendee list. If true, duplicate events will be automatically added to the attendees' calendar.
var defaultAllDayReminder = -1;        // Default reminder for all day events in minutes before the day of the event (-1 = no reminder, the value has to be between 0 and 40320)
                                       // See https://github.com/derekantrican/GAS-ICS-Sync/issues/75 for why this is neccessary.
var overrideVisibility = "";           // Changes the visibility of the event ("default", "public", "private", "confidential"). Anything else will revert to the class value of the ICAL event.
var addTasks = false;

var emailSummary = false;              // Will email you when an event is added/modified/removed to your calendar
var email = "";                        // OPTIONAL: If "emailSummary" is set to true or you want to receive update notifications, you will need to provide your email address

**Comment by GillesMart** [comment]
Thank you so much for that. It works great! It's just required to add at the end:
 }
});

I saved a lot of time thanks to you.

**Comment by derekantrican** [comment]
Glad you got it solved - thanks for sharing your solution for future viewers

**Comment by berbigou** [comment]
‌

Wow!  I feel like I'm a developer !!
Thank you for your work (How can Google be so dumb no to propose reliable ics synchronization every known amount of time ?)‌

Have a nice day.
Bernard from France

(I also noticed that I needed Edge (aka Chromium) instead of Firefox to authorize/sign my script. Maybe this information could be added to Code.gs lines 13-14
   * 4) Authorize: You will have to use Edge or any Chromium-like browser, not the magnificent Firefox and you will be prompted to authorize the program and will need to click "Advanced" > "Go to GAS-ICS-Sync (unsafe)"
   *    (For steps to follow in authorization, see this video: https://youtu.be/_5k10maGtek?t=1m22s )
)
De : "GillesMart"
A : "derekantrican/GAS-ICS-Sync" ,"berbigou" ,"Author"
Envoyé: samedi 30 Septembre 2023 22:08
Objet : Re: [derekantrican/GAS-ICS-Sync] Login information disallowed (Issue #363)
 

 

Thank you so much for that. It works great! It's just required to add at the end:
}
});

I saved a lot of time thanks to you.

**Comment by derekantrican** [comment]
Interesting - I've never had any issues with Firefox & authorization of the script

**Comment by Lonestarjeepin** [comment]
Ironically enough, that's the second time I've seen someone say they had to
use Edge. The other user was using Chrome initially. I couldn't find where
they reported the issue to link them though.


KW

**Comment by FabioRomagnolo** [comment]
Worked like a charm! Thank you so much.
Here's the well formatted code:

```js
var urlResponse = UrlFetchApp.fetch(url, { 'validateHttpsCertificates' : false, 'muteHttpExceptions' : true ,"headers": {
        "Authorization": "Basic " + Utilities.base64Encode("user:password")}});
```
