### ISSUE TITLE
Cannot sync past events older than 30 days

### ISSUE THREAD

**Issue by gmnr** [derekantrican/GAS-ICS-Sync#365]
### The problem

Syncing the calendar works fine, but it automatically removes any event older than 30 days.
I've also modified the file as per issue #183 to explicitly fetch older items; but to no avail.

Is there something I'm missing?

### Version of GAS-ICS-Sync

5.7

**Comment by jonas0b1011001** [comment]
Sounds like the source does not include events older than 30 days.
See if my comment in #344 helps.

**Comment by gmnr** [comment]
> Sounds like the source does not include events older than 30 days. See if my comment in #344 helps.

That makes sense; I have set the variable `removeEventsFromCalendar` to `false`.
I'll check in a few days if it keeps the "expired" events and eventually close the issue.

Thanks a lot

**Comment by jonas0b1011001** [comment]
Keep in mind that `removeEventsFromCalendar = false` will also keep future events that get removed from the source.
You will manually have to update to get a new option specifically for past events.

**Comment by gmnr** [comment]
> Keep in mind that `removeEventsFromCalendar = false` will also keep future events that get removed from the source. You will manually have to update to get a new option specifically for past events.

This will happen also for events that I reschedule?

**Comment by jonas0b1011001** [comment]
No, the setting only affects removing. Editing will work as usual.
