### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by TonyBarganski** [derekantrican/GAS-ICS-Sync#367]
### Is your feature request related to a problem? Please describe.

Q. Is there a way to add the events under “Other calendars” vs “My calendars”?

Background:
 
I’m using ‘[calcurse-caldav](https://calcurse.org/files/calcurse-caldav.html)’ so that I can view my Calendar Schedules from the Command Line (macOS), which is part of my workflow and some terminal todo.txt apps I’ve written.
 
When I subscribe to a calendar using “From URL”, Google puts it under “Other calendars” which works  with 'calcurse-caldav'.

Google CalDav API URL
‘[https://apidata.googleusercontent.com/caldav/v2/<CalendarID>/events/’]
 
Your script is truly a God send but it puts the Calendar under “My Calendars” which gives a different CalendarID URL the for Subscribed calendars when working through the Google Calendar GUI. 'calcurse-cadav' then gives me a 404 error with the new URL.

CalendarID URLs
Other calendars:
/caldav/v2/e1jb65cfvjhh94esv69vd03tj5unhli0@**import**.calendar.google.com/events/

My calendars:
/caldav/v2/7cnlmnds2t57uqvr1g57iahaip@**group**.calendar.google.com/events/

Notice: Google gives a CalendarID with a URL subdomain of "**import**" for subscribed calendars under "Other calendars" and a URL subdomain prefix of "**group**" for calendars under "My calendars"

### Describe the solution you'd like

I'd like to be able to modify the script so that the sync'ed/subscribed ics calendar is put under the "Other calendars" and given a subdomain prefix of "**import**..calendar.google.com".

**Comment by derekantrican** [comment]
Unfortunately not. Calendars in the "Other Calendars" section are subscriptions (they are read-only) and you can't add events to them. Of course, you can subscribe to your calendar directly in Google Calendar, but that will incur the very slow update time of 12-24 hours that is built into Google Calendar
