### ISSUE TITLE
Feature: Add Description and Title to Email Notifications 

### ISSUE THREAD

**Issue by p5hema2** [derekantrican/GAS-ICS-Sync#38]
Add Description and Title to Email Notifications

**Comment by derekantrican** [comment]
It looks like there was a regression here. It was fixed in https://github.com/jonas0b1011001/GAS-ICS-Sync-CalAPIv3/commit/1ddd0dc845cdb38943d43adf235622dce5f7d026 but the latest version only includes Titles in email notifications, not descriptions. We'll work on that
