### ISSUE TITLE
ICS/ICAL parsing issue (multiple lines, "\n" not being accounted for)

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/GAS-ICS-Sync#4]
From Google-Apps-Script-Library created by [derekantrican](https://github.com/derekantrican) : derekantrican/Google-Apps-Script-Library#7  

ICS link: http://msdwarren.blob.core.windows.net/calendar/sports-all.ics

Resulting event:
![image](https://user-images.githubusercontent.com/38076265/38327750-fef34882-3816-11e8-91e9-c8e10144d167.png)

    BEGIN:VEVENT
    CREATED;VALUE=DATE:19000101
    DESCRIPTION:Start Time: 5:30 PM\nEnd Time: 7:30 PM\nSport: Baseball\nGender
     : Male\nClass(es): V\nLocation: Lawrence North\nOpponent(s): Lawrence Nort
     h High School
    DTEND:20190410T233000Z
    DTSTART:20190410T213000Z
    DTSTAMP:20180404T055405Z
    LAST-MODIFIED;VALUE=DATE:19000101
    LOCATION:Lawrence North
    SEQUENCE:0
    SUMMARY:Baseball\, Varsity @ Lawrence North
    TRANSP:Transparent
    UID:e3020681
    END:VEVENT

My program parses the ics file line by line, so that's why the description is getting cut off (because the ics file here has the description split onto multiple lines). I can probably look into adjusting the program to account for this. I'll also look into why the `\n` isn't getting treated properly.

**Comment by derekantrican** [comment]
Originally: https://github.com/derekantrican/Google-Apps-Script-Library/issues/7#

**Comment by blackwind** [comment]
Note the backslashes before the commas as well, along with any other characters that may need unescaping.
