### ISSUE TITLE
End time cannot be same 

### ISSUE THREAD

**Issue by andytrine** [derekantrican/GAS-ICS-Sync#40]
For one-day all-day events I get an error: Event start date must be before event end date. (line 172, file "Code")

Example:
[19-04-11 10:38:53:653 CEST] Title: New Year's Day
[19-04-11 10:38:53:654 CEST] Id: 8299f54d-117f-46c9-84f9-ae35fe12d7c7@vacationtracker.io
[19-04-11 10:38:53:654 CEST] Description: 
[19-04-11 10:38:53:654 CEST] Start: Tue Jan 01 2019 00:00:00 GMT-0800 (PST)
[19-04-11 10:38:53:655 CEST] End: Tue Jan 01 2019 00:00:00 GMT-0800 (PST)

**Comment by derekantrican** [comment]
@andytrine if you are willing, please share with me your ICS file

**Comment by andytrine** [comment]
@derekantrican sure - here is the ical link, hope that works:
https://api.vacationtrackerbot.com/calendar/jointrine/c87d5fa8-032c-42cd-8ae5-1ba04b1bf1d5/upcoming.ical

**Comment by andytrine** [comment]
Also once it does an update synch on existing events they become "normal" events and not all-day events for some reason

**Comment by andytrine** [comment]
Also when it synchs it makes duplicates of the same event?

**Comment by jonas0b1011001** [comment]
> Also when it synchs it makes duplicates of the same event?

So did you get it to sync the ics you shared above? The event-ids used are actually not supported by Google Calendar.

**Comment by jonas0b1011001** [comment]
As mentioned [here](https://github.com/derekantrican/GAS-ICS-Sync/issues/55#issuecomment-534003159) this is not a valid way to describe an one-day all-day event.

**Comment by derekantrican** [comment]
@andytrine I would suggest contacting the developers at "vacationtrackerbot.com" and alert them of this issue. As @jonas0b1011001 mentioned, this is not a valid format for an "all-day" event according to the [official ical documentation](https://tools.ietf.org/html/rfc5545#section-3.8.2.2):

```
BEGIN:VEVENT
UID:2336d2bf-463b-4a23-afad-04b2a809d212@vacationtracker.io
SEQUENCE:0
DTSTAMP:20190925T131403Z
DTSTART;VALUE=DATE:20190101
DTEND;VALUE=DATE:20190101
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
X-MICROSOFT-MSNCALENDAR-ALLDAYEVENT:TRUE
SUMMARY:New Year's Day - Trine Sweden
ORGANIZER;CN="Vacation Tracker":mailto:hello@vacationtrackerbot.com
END:VEVENT
```

The event should actually have the property `DTEND;VALUE=DATE:20190102` (end at midnight of the next day).
