### ISSUE TITLE
ReferenceError: removePastEventsFromCalendar is not defined

### ISSUE THREAD

**Issue by MoonShadow-NM** [derekantrican/GAS-ICS-Sync#405]
### The problem

When running the script, when there are items that are to be deleted, they are not. In the execution log, the very last line is this 
![image](https://github.com/derekantrican/GAS-ICS-Sync/assets/1063503/c9253872-861e-44df-b925-a5db3543ca96)

Yes, the script is configured correctly as I have been running it for several months on version 5.7. I upgraded to 5.8 a few weeks ago and noticed that events that were deleted/removed in Outlook were no longer being removed from GCal.
I see this in the log: 
![image](https://github.com/derekantrican/GAS-ICS-Sync/assets/1063503/9b0ab85a-7838-4cdc-9a61-903c38f1182a)

### Version of GAS-ICS-Sync

5.8

**Comment by MoonShadow-NM** [comment]
Just to note, I reverted back to 5.7 and it works as expected.

**Comment by jonas0b1011001** [comment]
> Yes, the script is configured correctly

5.8 introduced new settings, seems like you are using the 5.7 settings.
https://github.com/derekantrican/GAS-ICS-Sync/blob/17cde1a768ad4c6d5ede0e7401e20606fff0be2a/Code.gs#L39

**Comment by MoonShadow-NM** [comment]
Ah, I know what happened, then. I didn't want to lose my config settings, so I just copied the bottom portion of the script. I think I need to read the entire script to make sure I don't miss important things like this. Thanks.
