### ISSUE TITLE
No attendees found

### ISSUE THREAD

**Issue by passeee** [derekantrican/GAS-ICS-Sync#418]
### The problem

I don't see any attendees in my events.
I checked the code and 
`event.hasProperty('attendee') is false`
Also `icalEvent.attendees.count is undefined` (but idk if .count is even possible)
Edit: Also `icalEvent.attendees.length is 0`

The ICS url should include all details, even the attendees (at least outlook says that)

### Version of GAS-ICS-Sync

5.8

**Comment by jonas0b1011001** [comment]
> The ICS url should include all details, even the attendees (at least outlook says that)

Did you take a look at the ics to confirm that they are actually included?

**Comment by passeee** [comment]
> > The ICS url should include all details, even the attendees (at least outlook says that)
> 
> Did you take a look at the ics to confirm that they are actually included?

How could i read details out of the ics?

**Comment by jonas0b1011001** [comment]
Download the file and open it in any text editor.

You will see blocks of 
```
BEGIN:VEVENT
...
END:VEVENT
```
defining each event.

**Comment by jonas0b1011001** [comment]
I don't know if this is possible in Outlook, sorry. A quick google search did not yield an answer.

Gonna close this as 'not a script issue'.

**Comment by passeee** [comment]
Yeah also didnt find anything helpful.
What I could at least find out is, when exporting one event as ICS file it includes the attendees, but not with the ics url.
Very strange behavior, still thanks for your effort
