### ISSUE TITLE
[Request] Event filters

### ISSUE THREAD

**Issue by pauel3312** [derekantrican/GAS-ICS-Sync#422]
### Is your feature request related to a problem? Please describe.

The calendar I clone creates events for canceled events, and the name of such events starts with `CANCELLED`. Also, during the holidays, there is an event that has no title or just `-`, I'm not sure if that just means the event has no title or if it is the actual title), that is created from midnight to midnight, but that is not an all day event. I guess these are problems with the calendar provider, but I think something can be done on the script's side, and it can just be a good feature.

### Describe the solution you'd like

To fix this, I think what might be useful to have filters for events: name based, date based, weekday based (as suggested in #359 ), etc... This would allow me to solve my issue, and it would make the script overall more convenient.

**Comment by pauel3312** [comment]
> Check out [this branch](https://github.com/derekantrican/GAS-ICS-Sync/tree/event-filtering), it allows to define various filters in _filters.gs_.

Okay this is awesome, I could remove cancelled events
I have one question: why is there no open PR for this?

**Comment by jonas0b1011001** [comment]
So you have it fully working now?



> Also, why is there no open PR for this?

Because i actually intend to further work on it and do some testing, but have not had time to fully commit to it.

**Comment by pauel3312** [comment]
> So you have it fully working now?
Yup, works beautifully.

I don't know what might help, but if you want me to write a readme/user manual for this, I'll gladly help, but I don't really know the script itself.
I mean I could figure out how to use log debugging to get the exact value of the summary of the events it would not delete, but that's about it, but I understand how it works
mostly.

**Comment by ArkadiuszNiemiec** [comment]
Unfortunately it does not work correctly with one occurrence cancelled by the author. The cancelled occurrence is not being deleted and while starting the sync the cancelled meeting is not changing to Free from Tentative until I remove the filter.

**Comment by jonas0b1011001** [comment]
> Unfortunately it does not work correctly with one occurrence cancelled by the series author. The cancelled occurrence is not being deleted and while starting the sync the cancelled meeting is not changing to Free from Tentative until I remove the filter.

With occurrence you mean a single event from a recurrence series?
What filter did you define?
Can you share that calendar?

**Comment by ArkadiuszNiemiec** [comment]
Yes, sure. How can I contact you directly?

śr., 20 mar 2024, 00:36 użytkownik jonas0b1011001 ***@***.***>
napisał:

**Comment by jonas0b1011001** [comment]
> Yes, sure. How can I contact you directly?

You can join [the discord](https://discord.gg/DRBpb4k) or send me an [email](mailto:jonas0b1011001@gmail.com).

**Comment by ArkadiuszNiemiec** [comment]
Thank you, texted you on Discord. Thanks for the great work!

śr., 20 mar 2024 o 00:55 jonas0b1011001 ***@***.***>
napisał(a):
