### ISSUE TITLE
ReferenceError: calendarTz is not defined

### ISSUE THREAD

**Issue by DiemenDesign** [derekantrican/GAS-ICS-Sync#427]
### The problem

ReferenceError: calendarTz is not defined
````
Error	
    ReferenceError: calendarTz is not defined
    validateTimeZone	@ Helpers.gs:830
    createEvent	@ Helpers.gs:376
    processEvent	@ Helpers.gs:291
    (anonymous)	@ Code.gs:219
    startSync	@ Code.gs:218
````
The Calendar Reference is created, but the events are not added, nor updated.

### Version of GAS-ICS-Sync

5.8

**Comment by DiemenDesign** [comment]
Ok, I got this working, I didn't copy the project as per the instructions in the read me, I copied the files from this repository. I guess it pays to actually read things completely, apologies for wasting your time.

**Comment by jonas0b1011001** [comment]
Well, you found a bug in the master branch anyways. Thanks for reporting! :)

**Comment by DiemenDesign** [comment]
Funny how things work out. Hope it helps.
