### ISSUE TITLE
Latest version is 3.0 but latest version in script is 2.0

### ISSUE THREAD

**Issue by Alex-Poon** [derekantrican/GAS-ICS-Sync#43]
`var thisVersion = 2.0;`

Link to copy the code from: https://script.google.com/d/1QeZFLSM1EkuFvYcryECI_xH-IZVe1-IxGRq_n6OoXp1CmVtSeTeigEx4/edit?usp=sharing

**Comment by derekantrican** [comment]
Thanks. Should be resolved
