### ISSUE TITLE
Calendar not defined

### ISSUE THREAD

**Issue by bcwilsondotcom** [derekantrican/GAS-ICS-Sync#433]
### The problem

After installing the latest version of the files directly from the repo, I get the following error on startSync:

ReferenceError: Calendar is not defined
    at setupTargetCalendar(Helpers:179:24)
    at startSync(Code:178:26)

The run then ends and nothing is synced

### Version of GAS-ICS-Sync

5.8

**Comment by jonas0b1011001** [comment]
Go to project settings in the code editor (left sidebar), check _display appsscript.json_, open the file in the editor and compare it to [https://github.com/derekantrican/GAS-ICS-Sync/blob/master/appsscript.json](https://github.com/derekantrican/GAS-ICS-Sync/blob/master/appsscript.json)
