### ISSUE TITLE
Where is .isDate?

### ISSUE THREAD

**Issue by Samdoescode** [derekantrican/GAS-ICS-Sync#45]
G'day team, 

Very very very new to dev world here and am using fun tools like this to build some base skills.

Totally understand if this isn't a focus or isn't even a script on your radar any more!

Installed the script and ran but didn't get any events. Checked out the execution transcript and saw.

Execution failed: TypeError: Cannot read property "isDate" from null. (line 267, file "Code")

I'm using a calendar from my training software. I think the script is looking for DTstart and finding something it doesn't expect and so its struggles to use the class??

the DTstart in the output of the calendar is: DTSTART:20190707T040000

Tried my very best to find a solution but can't quite get me head around it.

**Comment by derekantrican** [comment]
Please share your copy of the script with me (derekantrican@gmail.com)

**Comment by Samdoescode** [comment]
Done!

**Comment by derekantrican** [comment]
@Samdoescode `.isDate` is located in the `ical.js.gs` file. Looking at the copy of the script you shared with me it should be there. After looking at your ics file it looks like the `dtend` value is `null` (because the event has no `DTEND` block - see below)

````
BEGIN:VEVENT
DESCRIPTION:Workout: Run - Recovery Run\n\nPlanned: 30:00
DTSTAMP:20190707T162750Z
DTSTART;VALUE=DATE:20190709
SEQUENCE:0
SUMMARY:Run - Recovery Run
UID:e1f797d9-6f8f-4ab7-b5b4-ecbf701b1268
END:VEVENT
````

I'm going to make a conjecture that `DTEND` is not optional and *should* have been on your ics file. But, nonetheless, we can "code around it". Try changing the `ConvertToCustomEvent` function to this (this successfully worked for your calendar on my end):

````
function ConvertToCustomEvent(vevent){
  var event = new Event();
  event.id = vevent.getFirstPropertyValue('uid');
  
  if (descriptionAsTitles)
    event.title = vevent.getFirstPropertyValue('description') || '';
  else{
    event.title = vevent.getFirstPropertyValue('summary') || '';
    event.description = vevent.getFirstPropertyValue('description') || '';
  }
  
  if (addOrganizerToTitle){
    var organizer = ParseOrganizerName(vevent.toString());

    if (organizer != null)
      event.title = organizer + ": " + event.title;
  }
  
  event.location = vevent.getFirstPropertyValue('location') || '';
  
  var dtstart = vevent.getFirstPropertyValue('dtstart');
  var dtend = vevent.getFirstPropertyValue('dtend');
  
  if (dtstart.isDate || dtend.isDate)
    event.isAllDay = true;
  
  if (vtimezone != null)
    dtstart.zone = new ICAL.Timezone(vtimezone);
    
  event.startTime = dtstart.toJSDate();
  
  if (dtend == null)
  {
    if (event.isAllDay)
      event.endTime = new Date(event.startTime.getTime() + 24 * 60 * 60 * 1000);
    else
      event.endTime = new Date(event.startTime.getTime() + defaultDuration * 60 * 1000);
  }
  else{
    if (vtimezone != null)
      dtend.zone = new ICAL.Timezone(vtimezone);
      
    event.endTime = dtend.toJSDate();
  }
  
  if (addAlerts){
    var valarms = vevent.getAllSubcomponents('valarm');
    for each (var valarm in valarms){
      var trigger = valarm.getFirstPropertyValue('trigger').toString();
      event.reminderTimes[event.reminderTimes.length++] = ParseNotificationTime(trigger);
    }
  }
  
  return event;
}
````

(This may be a helpful change for us to make in the future too)

Please let me know if this solves your problem

**Comment by Samdoescode** [comment]
Hey, 

This is awesome and works well, script is running. Strangely enough the new events in calendar are all 24hr long. 

If I delete the events, then let the script run, it will add the events correctly as an "all day event" because it has not set start or end time only a date. Then when it checks again it makes an event 24 hours starting at 5pm and finishing at 5pm the next day even though 5pm is never specified any where?

It appears to be checking again and finding the same event then calculating a change in end time somehow?

I've been messing around with it unfortunately my skills have been exhausted. 

Hope this helps future development!

**Comment by jonas0b1011001** [comment]
setTime in line 228 converts all day events to regular events, that's what you are experiencing. The 5pm start time seems to be a timezone issue.

You could try changing line 228
e.setTime(fe.startTime, fe.endTime)
to
`if (fe.isAllDay){
	e.setAllDayDates(fe.startTime, fe.endTime)
}else{
	e.setTime(fe.startTime, fe.endTime)
}`

**Comment by derekantrican** [comment]
@Samdoescode it looks like this issue is a bit old now - would you consider this solved? Did @jonas0b1011001 's suggestion fix the issue?
