### ISSUE TITLE
[Request]: shared calendar name in target calendar

### ISSUE THREAD

**Issue by nestor50** [derekantrican/GAS-ICS-Sync#453]
### Is your feature request related to a problem? Please describe.

Hello, and thanks for the script! I've just installed and everything seems to work apart that my ical shared calendars when synced are duplicated in "My calendars", the result is as follow:
- In my calendars I have: "Work" and "Personal" calendar (created by the script)
- In other calendar I have the original shared calendar from Ical

### Describe the solution you'd like

This results in double calendars which is quite weird to see; I now that I can uncheck the original ical calendars in google but I guess there's a way to tell "targetCalendar" that the calendar exists in "other calendars" and shouldn't be created in "my calendars". Is it possible? 
thanks for help!!!

### Additional context

.

**Comment by jonas0b1011001** [comment]
> I guess there's a way to tell "targetCalendar" that the calendar exists in "other calendars" and shouldn't be created in "my calendars". Is it possible?

Hi,
Unfortunately 'other calendars' are **read only** therefore the script can not work on your subscribed calendar.
