### ISSUE TITLE
Anyway to not import a calendar event based on type or keyword?

### ISSUE THREAD

**Issue by MechEng70** [derekantrican/GAS-ICS-Sync#454]
### Is your feature request related to a problem? Please describe.

Right now I have some Time Blocks in my outlook calendar and they are marked private.  I do not necessary want them to come over to my google calendar.  

### Describe the solution you'd like

1. Could there be a switch that allowed the user to not import or disregard "Private" appointments
2. Could a keyword be selected that would stop the import (I use the keyword TB for Time Block.

**Comment by jonas0b1011001** [comment]
Please check #376. This already made it to the master branch.

**Comment by MechEng70** [comment]
Hi @jonas0b1011001 I am having issues with the filter...  I have multiple calendar events with the title "TB - GSD" and they also have the category TB-GSD.  Using the filter below and it is still importing then.  I have uninstalled and installed the code.  Not sure if the parameter "title" is allowed.

```
var filters = [
            { 
              parameter: "categories",
              type: "exclude", //include/exclude
              comparison: "begins with", // equals, begins with, contains, regex
              criterias: ["TB"]
            },
            { 
              parameter: "title",
              type: "exclude", //include/exclude
              comparison: "begins with", // equals, begins with, contains, regex
              criterias: ["TB"]
            }
          ];
```

**Comment by jonas0b1011001** [comment]
Download your source ics files and open them in a text editor to find the parameters you need to filter.
For example `title` should probably be `summary`, category depends on where your files are coming from.
