### ISSUE TITLE
Encountered HTTP error 404 when accessing example.ics (GCal Added, but events don't sync)

### ISSUE THREAD

**Issue by Dabble-NY** [derekantrican/GAS-ICS-Sync#458]
### The problem

I've worked my way through the instructions and ran the script. The two target calendars appear under 'My Calendars' in my Google Calendar, but no events show for them.

When looking at the log I receive this error: "Error: Encountered HTTP error 404 when accessing https://calendar.google.com/calendar/ical/redacted.com/public/basic.ics"

- Removed my calendar name there ^ 
- I took this ICS directly from the targeted Google calendar below the label 'Public address in iCal format'.
- The log states it's fetched, parsed, processed etc. 0 events.

I tried searching if anyone had this issue in the past, but did not see my scenario. 

Please let me know if you have any advice or need more information. Images attached

 Thank you!

### Version of GAS-ICS-Sync

5.8

### Additional information & file uploads

<img width="580" alt="SCR-20241002-lphv" src="https://github.com/user-attachments/assets/f629fa3d-f2ab-479b-83a0-d6507124a7e3">

![SCR-20241002-lqad](https://github.com/user-attachments/assets/48e6124e-2ecf-4edf-bf29-b1c190808b0c)

**Comment by jonas0b1011001** [comment]
Please make sure your calendars are actually shared publicly (in the same settings page you got the ics links from) otherwise the **public** links won't work.
Alternatively you could use the **private** ics links.
