### ISSUE TITLE
ReferenceError: filters is not defined

### ISSUE THREAD

**Issue by ccecvb** [derekantrican/GAS-ICS-Sync#460]
### The problem

filterResults throws error if no filters are defined.
Installed script today from master branch

```
ReferenceError: filters is not defined
    at filterResults(Helpers:282:26)
    at parseResponses(Helpers:244:12)
    at startSync(Code:204:17)
``` 

### Version of GAS-ICS-Sync

5.8

**Comment by jonas0b1011001** [comment]
You forgot to copy/create [filters.gs](https://github.com/derekantrican/GAS-ICS-Sync/blob/master/filters.gs) to your script.

**Comment by ccecvb** [comment]
Thank you for the fast response.
I followed the instructions on  https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually and only copied the files listed in step 6.

**Comment by ccecvb** [comment]
I added filters.gs and now it's working

**Comment by CindyLang** [comment]
Hi, I had this exact same issue and the suggested fix solved it, but I wanted to point out that the instructions on https://github.com/derekantrican/GAS-ICS-Sync/wiki/Setting-up-the-script-manually are still incorrect, and don't list the filters.gs file.  Can someone add that to the instructions?  Would save new users from going through the same troubleshooting steps.  Thanks!

**Comment by yermulnik** [comment]
Somewhat related, though was declined https://github.com/derekantrican/GAS-ICS-Sync/pull/471
