### ISSUE TITLE
Discussion: support full Google Calendar API?

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/GAS-ICS-Sync#47]
@staffanf @jonas0b1011001 @amytencza @nvardi @agentd00nut *(trying to tag most people that have participated in discussions on this repository for supporting recurrence. Feel free to tag others if you think they should be part of this discussion)*

Currently this script uses the "Google Apps Version" of the Google Calendar API. I've thought multiple times about supporting the full Google Calendar API instead. Here are some pros & cons:

**Pros:**

- Some features are more "wholly" supported in the full API. For instance, the "GAS API" doesn't support things like negative `BYMONTHDAY` in RRULEs. RRULE implementation would also be *MUCH* easier as we can simply use the RRULE rather than trying to write a custom parser for the RRULE
- More features are supported in the full API. For instance, if we wanted to change something like event color or event availability/transparency this can only be done through the full API

**Cons:**

- ~~It would be a much more involved process for a user to set up. Currently when a user installs the script they just have to authorize it, then they're good to go. With the full API they would have to authorize it, enable it (`Resources > Advanced Google Services`), and also enable it on the Google Cloud Platform API Dashboard.~~ **Edit:** It seems according to [this](https://developers.google.com/apps-script/guides/services/advanced) that this was reworked a bit in April, 2019. If we move the script to a new document (therefore created after April, 2019) then people should be able to just "Make a Copy", authorize, and use just like before. I just tested it with an example script (you can do the same if you're curious: https://script.google.com/d/1MChjSD4yhIGEcrz1MddTLOfSy1oqZveDuwSNZuEkGd47UcoBHspRRZZi/edit?usp=sharing)
- The script would have to be reworked quite a bit to change from the "GAS API" to the full API

Any thoughts, discussion, etc would be greatly appreciated. What do you think?

**Comment by jonas0b1011001** [comment]
I think switching would be a good idea :)

I've been running my own version based on the full API for several weeks and have not had any issues ever since. The full API handles Recurrence and timezones easily, imho the most difficult issues to solve with GAS.
After the API is enabled once the process of installing the script seems to be exactly the same as with the GAS version.

**Comment by derekantrican** [comment]
@jonas0b1011001 Great! I see you have https://github.com/jonas0b1011001/GAS-ICS-Sync - do you mind updating that with your current code that includes the full API? ([This Chrome extension](https://chrome.google.com/webstore/detail/google-apps-script-github/lfjcgcmkmjjlieihflfhjopckgpelofo?hl=en) should make that process easier). That would help us a ton with "Con" point # 2

My original opinion was to not make the switch because of "Con" point # 1. But it seems that Google made this essentially irrelevant in April. We just have to copy the code to a newer Script document (which I can do since the original one is hosted on my Drive anyway). So I'm much more open to the idea of switching now!

**Comment by amytencza** [comment]
I would also be concerned about con #1, but given there's a solution for that, I greatly recommend using the full API. The recurrence issues are a pretty impactful bug at the moment....

**Comment by jonas0b1011001** [comment]
Updated my current version at https://github.com/jonas0b1011001/GAS-ICS-Sync/tree/jonas0b1011001-patch-1

Takes about 70 seconds to freshly sync 140 Events - no errors on my end but definitely needs testing with some random icals.

**Comment by amytencza** [comment]
ReferenceError: "Calendar" is not defined. at main(Code:150)

tried creating the calendar in Google, and added the targetCalendarId value, but still fails

**Comment by derekantrican** [comment]
@amytencza Is that an issue with @jonas0b1011001 's repo? If so - please raise the issue there

**Comment by amytencza** [comment]
yes, with jonas's patch

**Comment by jonas0b1011001** [comment]
> ReferenceError: "Calendar" is not defined. at main(Code:150)
> 
> tried creating the calendar in Google, and added the targetCalendarId value, but still fails

You have to activate Calendar API. Script Editor: Resources, Advanced Google Services, Calendar API v3 -> activate (that's con 1)

**Comment by amytencza** [comment]
oooooh! makes sense. we should update the installation instructions too then....

**Comment by derekantrican** [comment]
This can be solved if you simply copy the code to a new script file. Google changed something about how the "enable advanced services" stuff works in April, 2019

**Comment by amytencza** [comment]
i did a copy, and the instructions are relevant, but jacob's patch requires an extra step now that isn't covered in the instructions yet....

**Comment by amytencza** [comment]
@jonas0b1011001  i am adding more comments to your patch here:
https://github.com/jonas0b1011001/GAS-ICS-Sync/commit/4c3f34bc9bb40270f82d64bafd026d694833107a#diff-b2598947b32ada69922f17eb96952e70

**Comment by derekantrican** [comment]
@jonas0b1011001 I'm now (more or less) in a position to devote my attention to this. In order to better discuss this, here's an invite to the slack channel: https://join.slack.com/t/gasicssync/shared_invite/enQtNzE4Njk2NzA0Mjc0LTZlMTIwYTU1Njg1NGMyY2Q4ZTIyOWQ5ZTA5NzYzOTRmZDk2ZDAxN2MyNDYyNTljMDY2ZWM3ODE5ZmY1Nzk5MjY

(if anyone else feels like joining, feel free)

**Comment by derekantrican** [comment]
I'm going to close this issue/discussion. Long story, short: we will support the full Google Calendar API and we're working on that in @jonas0b1011001 's [fork](https://github.com/jonas0b1011001/GAS-ICS-Sync-CalAPIv3) for now. Eventually we'll pull that in to this repo
