### ISSUE TITLE
Error with fetching ical calendar feed

### ISSUE THREAD

**Issue by andytrine** [derekantrican/GAS-ICS-Sync#49]
- When adding the following calendar feed it does not understand the ical text it seems. "TypeError: Cannot find function includes in object BEGIN:VCALENDAR VERSION:2.0 "
![image](https://user-images.githubusercontent.com/6923957/63334605-0ae8e500-c33c-11e9-8a2e-24bcf56053b6.png)

- https://app.travelperk.com/api/v1/calendar_feed/494058c36d744a289b9e799904f72736/

**Comment by derekantrican** [comment]
It looks like you only copied one of the files of the script

![image](https://user-images.githubusercontent.com/1558019/63348732-bf6c1200-c30e-11e9-9786-98f8360fd67b.png)

Please make sure you copy all of the files of the script

**Comment by derekantrican** [comment]
@andytrine did you get a chance to try this again with all of the files of the script copied?

**Comment by derekantrican** [comment]
Closing because of no response and obvious files missing
