### ISSUE TITLE
Events show up on wrong timeslot because of timezone

### ISSUE THREAD

**Issue by bearded22** [derekantrican/GAS-ICS-Sync#50]
I already added this as a comment to another bug but I assumed it would be more handy to just create a new bug ticket for it.

I'm encountering a similar problem for events as @amytencza in https://github.com/derekantrican/GAS-ICS-Sync/issues/34.

Events that have been created in a different time zone end up at the wrong time slot in the google calendar. In my case the Event is created in India and should apprear at 11:00 (which it does in the original calendar) but in google calendar it appears at 14:30.

When I check the logs I see the following:
The event has a date of **05:30:00 GMT-0700** but India should be at **GMT-5.5**. I tried to look into the code myself but I have the feeling my programming skills are a bit to limited to really be of support here.

I can do some additional debugging if required
<img width="578" alt="Screenshot 2019-08-21 at 09 51 22" src="https://user-images.githubusercontent.com/54335757/63413075-47c6e180-c3f9-11e9-95c5-1a79e5bf284a.png">

**Comment by jonas0b1011001** [comment]
Could you share the vevent and vtimezone source of the mentioned Event?

**Comment by bearded22** [comment]
Thnx for you quick response. 
Where do I do this ? I do not have enough knowledge of the code to see at what point I have to log those variables.

**Comment by jonas0b1011001** [comment]
You can download the ics you are trying to sync and open it in a text editor.
Events are defined between **BEGIN:VEVENT** and **END:VEVENT** . Would be great if you could share one vevent block that is not sync'd correctly (you can of course delete any private data like location and such).

**Comment by bearded22** [comment]
Sure :-)!
Here you go

`BEGIN:VEVENT
DESCRIPTION:"Here was the description"
UID:040000008200E00074C5B7101A82E008000000004765752D5656D501000000000000000
 010000000215C068EA9A50F42BA01986434136B8D
SUMMARY:Canceled: My Meeting that went wrong
DTSTART;TZID=India Standard Time:20190819T130000
DTEND;TZID=India Standard Time:20190819T133000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20190822T110731Z
TRANSP:TRANSPARENT
STATUS:CONFIRMED
SEQUENCE:3
LOCATION:Microsoft Teams Meeting
X-MICROSOFT-CDO-APPT-SEQUENCE:3
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT`

**Comment by jonas0b1011001** [comment]
Just tried this on my end and the event above syncs fine.
Which timezone is your target calendar set to?

<img width="581" alt="Bildschirmfoto 2019-08-23 um 20 10 51" src="https://user-images.githubusercontent.com/43352574/63614066-70f69600-c5e2-11e9-88df-d05d51f4b1a3.png">

Which version of the script are you using?

**Comment by bearded22** [comment]
Perhaps I posted the wrong event ? I'm not sure as there were some problems because I cancelled it by accident and it was moved to another day so what I did I copied the vevent for a new upcoming meeting that also shows wrong in my calendar.

`BEGIN:VEVENT
DESCRIPTION: Here is the description
UID:040000008200E00074C5B7101A82E0080000000043C8E312A659D501000000000000000
 010000000C09D543D6750EB4CA07EDC026E933335
SUMMARY:HQ flow discussion on Figma
DTSTART;TZID=India Standard Time:20190826T133000
DTEND;TZID=India Standard Time:20190826T150000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20190823T204910Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Microsoft Teams Meeting
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT`

I made sure I have the latest version, this time I did not copy from google scripts but actually copied everything from Github and used that. Still the same problem appears.

I added a screenshot of my target calendar timezone as well.
Thnx again for your support on this topic!

<img width="771" alt="Screenshot 2019-08-23 at 22 53 03" src="https://user-images.githubusercontent.com/54335757/63623099-ecfbd880-c5f8-11e9-98ec-7d59d474820a.png">

**Comment by jonas0b1011001** [comment]
> I noticed that in you example the target timezone is the Indian +5:30 mine is Amsterdam +2 I did not touch the time zone or changed anything related to that.

The Events are created in whatever timezone your targetcalendar is set to, yours is probably set to UTC+2, this however should not affect the actual time of the event.

Please try manually replacing the following lines of code (133-135)
`vtimezone = component.getFirstSubcomponent("vtimezone");`
`if (vtimezone != null)`
`  ICAL.TimezoneService.register(vtimezone);`
with
`var vtimezones = component.getAllSubcomponents("vtimezone");`
` for each (var tz in vtimezones){`
    `ICAL.TimezoneService.register(tz);}`

**Comment by bearded22** [comment]
Thnx you are a hero! 
That indeed seems to solve the problem. Events I personally have created are still in the right spots while events created in India have now also moved to their corresponding time slots.

I will check in the upcoming days If everything remains fine! I will also close this bug-report.

**Comment by derekantrican** [comment]
@jonas0b1011001 Thanks for taking care of this! Looks like that is something that we should incorporate into the main code

**Comment by jonas0b1011001** [comment]
Did some more edits and might have found a final solution for #34 aswell.
Changes are currently in my [fork](https://github.com/jonas0b1011001/GAS-ICS-Sync-CalAPIv3/commit/b395c13d667fb3c4154986dae49a62d571e391d7) - will do more testing before starting a pr but looks good so far.

**Comment by derekantrican** [comment]
@jonas0b1011001 Good to know. Looks like #42 (changes: https://github.com/derekantrican/GAS-ICS-Sync/pull/42/commits/26915b1a4fb5fabc750b2102a92694f52071480a) is also supposed to fix that too, so maybe compare your changes with those.

As far as testing, I don't know about the [wiki page on testing](https://github.com/derekantrican/GAS-ICS-Sync/wiki/Testing) but it has some example calendars you can use
