### ISSUE TITLE
When VEVENT is a "whole day" event the script ends in error

### ISSUE THREAD

**Issue by BompaBeer** [derekantrican/GAS-ICS-Sync#55]
Fout
22 sep. 2019 20:59:53
Error: invalid date-time value: "2019-10-04T::"
    at [unknown function](ical.js:5834)
    at [unknown function](ical.js:760)
    at [unknown function](ical.js:2888)
    at [unknown function](ical.js:2871)
    at [unknown function](ical.js:3017)
    at [unknown function](ical.js:2449)
    at ConvertToCustomEvent(Code:264)
    at main(Code:138)

**Comment by jonas0b1011001** [comment]
Seems like your source calendar is not formatted properly. Could you share the event in question?
If it is a all-day event time definition should look like "DTSTART;VALUE=DATE:YYYYMMDD"

**Comment by BompaBeer** [comment]
Thank you for your quick answer.
here is an example of an all-day event the way I find it in the iCal file

BEGIN:VEVENT
DTSTART:20191004
DTEND:20191004
UID:gimme-PeMomhZrB2g3w63bY
SUMMARY:Saved by the bell
DESCRIPTION:Goed onderwijs voor iedereen! Link:https://app.gimme.eu/mygimme
END:VEVENT

greetings from Belgium

**Comment by jonas0b1011001** [comment]
So there are actually two issues with the source.
1. Start and End Date miss the Value=Date property.
As
> The default value type is DATE-TIME.

the script is expecting a value that includes the time.

2. Start and End Date are the same day.

> [...]its (DTEND) value MUST be later in time than the value of the "DTSTART"
      property.

> The "DTEND" property for a "VEVENT" calendar component specifies the non-inclusive end of the event.

After correcting these error, the valid event would look like this:
`BEGIN:VEVENT`
`DTSTART;VALUE=DATE:20191004`
`DTEND;VALUE=DATE:20191005`
`UID:gimme-PeMomhZrB2g3w63bY`
`SUMMARY:Saved by the bell`
`DESCRIPTION:Goed onderwijs voor iedereen! Link:https://app.gimme.eu/mygimme`
`END:VEVENT`

DTEND can be omitted if the event takes place at a single  day though.
> For cases where a "VEVENT" calendar component specifies a "DTSTART" property with a DATE value type but no "DTEND" nor "DURATION" property, the event's duration is taken to be one day.

Therefore the following would also be valid:
`BEGIN:VEVENT`
`DTSTART;VALUE=DATE:20191004`
`UID:gimme-PeMomhZrB2g3w63bY`
`SUMMARY:Saved by the bell`
`DESCRIPTION:Goed onderwijs voor iedereen! Link:https://app.gimme.eu/mygimme`
`END:VEVENT`

Both versions are processed fine by the script.

It seems like the calendar is created by an App, if you want we can reach out to the developers and try to fix the issue.

**Comment by BompaBeer** [comment]
Hi,

thanks so much for the helpful analysis. I'll communicate your remarks to the creator of the app.

Could you look into the VEVENT below and tell me if it's format is correct please ?

BEGIN:VEVENT
DTSTART:20190925T110500Z
DTEND:20190925T135000Z
UID:gimme-wGamisdAastfj24AN
SUMMARY:Veldloop 
DESCRIPTION: Link:https://app.gimme.eu/mygimme
END:VEVENT

thank you

**Comment by derekantrican** [comment]
I think that looks good to me. As @jonas0b1011001 mentioned, the default is `DATE-TIME` so this event would be on 9/25/2019 and go from 11:05 to 13:50 (in the UTC timezone)

**Comment by jonas0b1011001** [comment]
According specification the event (as well as the previous one) are missing the DTSTAMP property.
`; The following are REQUIRED,`
            `; but MUST NOT occur more than once.`
           ` ;`
            `dtstamp / uid /`

DTSTAMP has no effect on how the event should actually be interpreted therefor i do not believe that one would run into issues omitting the property.
Besides that the VEVENT looks fine and should be processed correctly by the script.

> I'll communicate your remarks to the creator of the app.

In the meantime you can add the following lines at line 264 (right above "if (icalEvent.startDate.isDate && icalEvent.endDate.isDate)") in your code.gs to make it sync.
`  try{`
`    icalEvent.startDate.isDate`
`  }`
`  catch(e){`
`    Logger.log("Error Parsing. Trying manually.");`
`    //getting DTSTART Date`
`    var dtStartMatch = RegExp("DTSTART(.*?):(\\d\\d\\d\\d)-(\\d\\d)-(\\d\\d)T(\\d\\d)?:(\\d\\d)?:(\\d\\d)?", "g").exec(vevent.toString());`
`    var newStart = new ICAL.Time({year: parseInt(dtStartMatch[2]), month: parseInt(dtStartMatch[3]), day: parseInt(dtStartMatch[4]), isDate: dtStartMatch[5] == null}, ICAL.TimezoneService.get("floating"));`
`    icalEvent.startDate = newStart;`
`    //getting DTEND Date`
`    var dtEndMatch = RegExp("DTEND(.*?):(\\d\\d\\d\\d)-(\\d\\d)-(\\d\\d)T", "g").exec(vevent.toString());`
`    var newEnd = new ICAL.Time({year: parseInt(dtEndMatch[2]), month: parseInt(dtEndMatch[3]), day: parseInt(dtEndMatch[4]), isDate: dtEndMatch[5] == null},  ICAL.TimezoneService.get("floating"));`
`    //checking if Startdate equals Enddate`
`    if (newEnd.compare(newStart) == 0)`
`      newEnd.adjust(1,0,0,0)`
`    icalEvent.endDate = newEnd;`
`  }`

This should only be a **temporary** workaround though.

**Comment by BompaBeer** [comment]
Hello,

did you really created a workaround for me ? That's just awesome ! 

so I'm eager to try this but ...

Just one little problem ... I can't find the line

 "if (icalEvent.startDate.isDate && icalEvent.endDate.isDate)") in your code.gs above line 264 in the code.gs

Do I have a different version of your script ?

**Comment by jonas0b1011001** [comment]
Sorry i forgot to mention that it's based on the [latest version](https://github.com/derekantrican/GAS-ICS-Sync/blob/master/Code.gs) in the repo. You can just copy&paste the complete code including the workaround from [https://pastebin.com/raw/3wpvFnsr](https://pastebin.com/raw/3wpvFnsr).

**Comment by BompaBeer** [comment]
Hello,
so I tested the adapted script and at first things seemed to be going well, but after approx. 362 seconds I get a Time-out. I have no idea why since I get no logging info from the server (at least not at this moment). Any idea ?

**Comment by jonas0b1011001** [comment]
Did it create any events in your targetcalendar?

**Comment by BompaBeer** [comment]
No it didn't .. could there be another bad formatting issue in the source iCal file ?
If you want to give it a try ... 

https://api.gimme.eu/PjaDukcCBBx__P10v-_MjuTpPxHaQuLbGd9ADJWlGrq/icsevents/o/JSmysaZjgk4NEPrj6.ics

no big secrets in there :-)

I really appreciate your help

**Comment by jonas0b1011001** [comment]
Please do the following changes in line 276 **and** 280:
replace parseInt(dtStartMatch[2])  with parseInt(dtStartMatch[2], 10)
replace parseInt(dtStartMatch[3])  with parseInt(dtStartMatch[3], 10)
replace parseInt(dtStartMatch[4])  with parseInt(dtStartMatch[4], 10)

Should be 6 changes in total, after that it's running fine on my end :)

**Comment by BompaBeer** [comment]
Works just fine ! Great. 

Those last changes .. should they always be in the script or just in this case ?

many thanks

**Comment by jonas0b1011001** [comment]
They are part of the workaround so no need to adjust the normal script.

As explanation: By default parseInt is expecting a octal number if the provided string starts with "0" (which is the case if an event starts on day/month 00-09). There is no problem with 00-07, as they represent just the same number in octal as in decimal. 08 and 09 however are no valid octal numbers (decimal 8/9 would be octal 10/ 11) which caused issues. By adding the second parameter to parseInt we explicitly tell parseInt that we want the string to be interpreted as decimal number.

**Comment by BompaBeer** [comment]
Thank you for explaining that. I'll keep it in mind ...
and the script (with workaround) is busy... :-)

**Comment by jonas0b1011001** [comment]
Glad we could make it work!
I will close this issue, if you run into any other problems fell free to open a new issue.
