### ISSUE TITLE
All day events (start time = end time) issue

### ISSUE THREAD

**Issue by AlbertoM-BostonCollege** [derekantrican/GAS-ICS-Sync#56]
Yahoo calendar creates all day events by adding the same start time and end time to an event. This causes errors on Google: Event start date must be before event end date. at main(Code:172)

The event in question looks like this on the logs:
Title: Apple picking
Id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Description:
Start: Sat Oct 05 2019 17:00:00 GMT-0700   (PDT)
End: Sat Oct 05 2019 17:00:00 GMT-0700   (PDT)

**Comment by jonas0b1011001** [comment]
Please take a look at #55 and try the workaround suggested there.

**Comment by AlbertoM-BostonCollege** [comment]
error doesn't seem to be with parsing dates, so it doesn't adjust end date., so I assumed an all day event is one that starts and ends 24hrs later.  I added this but didn't quite cut it. 

```
 //checking if Startdate equals Enddate
  if (icalEvent.startDate == icalEvent.endDate)
    Logger.log("Start Date and End Date are the same. Adjusting End Date + 1");
    icalEvent.endDate.adjust(1,0,0,0)
```

**Comment by jonas0b1011001** [comment]
Try replacing your code.gs with the following [code](https://pastebin.com/raw/ksTUnGJD) and try again :)

**Comment by AlbertoM-BostonCollege** [comment]
Yup, that did it!
Thanks for the quick reply!

**Comment by derekantrican** [comment]
@jonas0b1011001 Sounds like this might become enough of a problem that we should just account for this in the main code. Something like:

```
if (duration is 0){
  if (start is date)
    //change duration to 1 day
  else //start is datetime
    //change duration to the "defaultDuration" setting
}
```

What do you think?

**Comment by jonas0b1011001** [comment]
Definitely seems to be a more common error than i thought it would be and might be worth pushing to the repo.
