### ISSUE TITLE
Still shows events that have been deleted

### ISSUE THREAD

**Issue by kevinlemaguer** [derekantrican/GAS-ICS-Sync#59]
Hi! 
I'm using your script since a few weeks now and it's awesome. But for some reasons it seems to not function as well as it used too, the script leave some events that have been deleted from the ICS or have been moved in the ICS (to another date), and sometimes doesn't show all the events.
I'm not sure if it's an error on the script, of if it's on the ICS in itself. 
[ICS link](https://www.italki.com/calendar/1rwI45QRZE0eeZ2gC7bjqs/ics)

**Comment by derekantrican** [comment]
Sorry to hear that your experience has been less than perfect. Can you provide some examples of these events? For instance, the title and date of events that are....

- Deleted in your ICS but still present in the Google calendar
- Moved in the ICS but not moved in the Google calendar

and any other situations. We'll take a look at it.

**Comment by kevinlemaguer** [comment]
Wow, very quick answer! :)

So you'll see in my screenshot that in red is the calendar in which the script copy the events that are in orange (the ICS), but those for today (at 11:30, 12:00 and 15:30) and the one for tomorrow (at 11:30) shouldn't be there. Also it's weird that the ICS gaves me the 15:30 event even tho it has been deleted. 

![Capture d’écran 2019-10-07 à 18 41 12](https://user-images.githubusercontent.com/56269453/66331623-4151e200-e933-11e9-8fcc-55181dc41d38.png)

**Comment by derekantrican** [comment]
We'll look into this when we get a chance.

In the meantime, could you share your copy of the script with me? derekantrican@gmail.com

**Comment by kevinlemaguer** [comment]
Ok thank you so much!

**Comment by jonas0b1011001** [comment]
The issue is quite obvious. If i download your linked ics through the browser i get a ical file with a total of 3 events, the script however receives a version with 7 events!
 
No idea why this happens though..

**Comment by derekantrican** [comment]
@jonas0b1011001 I see 7 events when I downloaded the ics

**Comment by jonas0b1011001** [comment]
Wow..
@kevinlemaguer How many events should there currently be?

**Comment by kevinlemaguer** [comment]
4...

**Comment by jonas0b1011001** [comment]
Yeah just tried the download from a vps..4 events (Priyank, Joss Baldwin, Emily27, Shotaro Nakamura).

**Comment by kevinlemaguer** [comment]
@jonas0b1011001 and Shotaro is for today or on Friday 11th?

**Comment by kevinlemaguer** [comment]
Maybe I shouldn't enter "1" for the `var howFrequent = 1`

**Comment by jonas0b1011001** [comment]
on the 11th 14:30Z

**Comment by kevinlemaguer** [comment]
@jonas0b1011001 yes so it works with your vps

**Comment by kevinlemaguer** [comment]
Ok, so it's the ICS "provider" that doesn't do his job properly I'm guessing. It would make sense, the script was working fine a couple of weeks ago and without touching it, the events started to bug.

**Comment by derekantrican** [comment]
Yeah, I was wondering if italki.com was somehow serving different ics files based on who was accessing it (or even where you were accessing it from)

**Comment by jonas0b1011001** [comment]
Well the ics files get cached (I assume from cloudflare) that might actually be intentional..

You can see the creation date when looking at the dtstamp value of your events:
When i download on my vps (4 events): dtstamp=20191007T171152Z
When i download from my browser(3 events):  dtstamp=20191007T164701Z
The script (7 events): dtstamp=20191007T065855Z <--That's almost 12h old!

**Comment by kevinlemaguer** [comment]
@derekantrican I was about to do it
@jonas0b1011001 so if the is no cache, should I assume that it will work properly? if I add `?noCache` after ics?

**Comment by jonas0b1011001** [comment]
I assume there is a way to ignore cache, but i can't get it to work. Cache-Control headers seem to be ignored..
Contacting italki might be your best bet

**Comment by kevinlemaguer** [comment]
@jonas0b1011001 yes, there were 7 events 12 hours ago for sure.

**Comment by kevinlemaguer** [comment]
And now there should be 5.

**Comment by jonas0b1011001** [comment]
Just found this in the Clountfront [DevGuide](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html):

> You cannot use the HTTP Cache-Control or Pragma header fields in a GET request from a viewer to force CloudFront to go back to the origin server for the object. CloudFront ignores those header fields in viewer requests.

So there's no way for us to fix this.

**Comment by kevinlemaguer** [comment]
Yes so it's what I thought, it's italki.com that has an issue, not the script! 
Sorry for the trouble guys!
And many thanks to you for trying to help me!
