### ISSUE TITLE
Make all events have certain time

### ISSUE THREAD

**Issue by Zangoran** [derekantrican/GAS-ICS-Sync#66]
I use this to sync my Canvas assignments to my personal calendar. Right now, they are created as all day events, but I don't want notifications to come the day before. I want multiple notifications to remind up to the due date. So 1 day before, 6 hours before, 1 hour before, etc. So that I won't forget to submit an assignment. The way canvas formats all the events are by all day. I would like to override those times to make it like 23:00-23:59 or something so that the notifications line up with how they should. I was looking at the code to see if I could hardcord something, but I couldnt figure out how to do that, without like cutting up the event.startTime and then appending the right date or something. I would love any help on this, I know this doesn't apply to everyone, but I would love it if I could get this to work. Thanks!

**Comment by jonas0b1011001** [comment]
You need to hardcode the reminders as well or are they part of the calendar?

**Comment by Zangoran** [comment]
I had them as default in the calendar, so I didn't have to hard code them
into the program. But whatever you think is best

**Comment by derekantrican** [comment]
You'll have to make modifications in two places: the section for adding events (`Code.gs` lines 186-192) and the section where we check if events need to be modified (`Code.gs` lines 231-237). I'm not sure if there's an easy way to check "time of day" for JS Dates, but I'm sure either I or @jonas0b1011001 will come up with a solution for you

**Comment by derekantrican** [comment]
Modification for `Code.gs` lines 186-192:

```
          event.startTime = new Date(event.startTime.getFullYear(), event.startTime.getMonth(), event.startTime.getDate(), 23, 0, 0);
          event.endTime = new Date(event.endTime .getFullYear(), event.endTime .getMonth(), event.endTime .getDate(), 23, 59, 0);
          resultEvent = targetCalendar.createEvent(event.title, 
                                                   event.startTime,
                                                   event.endTime,
                                                   {
                                                     location : event.location, 
                                                     description : event.description
                                                   });
```

Modification for `Code.gs` lines 231-237:

```
          fe.startTime = new Date(event.startTime.getFullYear(), event.startTime.getMonth(), event.startTime.getDate(), 23, 0, 0);
          fe.endTime = new Date(event.endTime .getFullYear(), event.endTime .getMonth(), event.endTime .getDate(), 23, 59, 0);
          if(e.getStartTime().getTime() != fe.startTime.getTime() ||
            e.getEndTime().getTime() != fe.endTime.getTime()){
            if (fe.isAllDay)
              e.setAllDayDates(fe.startTime, fe.endTime);
            else
              e.setTime(fe.startTime, fe.endTime);
          }
```

I think that should work. @jonas0b1011001 let me know if I'm mistaken

**Comment by jonas0b1011001** [comment]
> @jonas0b1011001 let me know if I'm mistaken

I did not actually test it but i think it should run. This will most likely cause timezone issues though.

The nicer option would probably be to do the changes in the ConvertToCustomEvent function.

My suggestion:
Add after line 28
```
var overrideAllDayEvents = true;
var overrideStart = "22:00:00";
```
Replace lines 274+275 with
```
if (icalEvent.startDate.isDate && icalEvent.endDate.isDate){
    if (overrideAllDayEvents){
      event.isAllDay = false;
      icalEvent.startDate.isDate = false;
      var startMatch = RegExp("(\\d\\d):(\\d\\d):(\\d\\d)","g").exec(overrideStart);
      icalEvent.startDate.adjust(0,parseInt(startMatch[1], 10),parseInt(startMatch[2], 10),parseInt(startMatch[3], 10));
    }
    else{
      event.isAllDay = true;
    }
  }
```

**Comment by derekantrican** [comment]
I'm going to close this as this is either described in the Rules issue or would be deemed a very specific use-case (and therefore not applicable as a change for everyone)

**Comment by Zangoran** [comment]
@jonas0b1011001 That doesn't work, it appears to put the end date before the start date for some reason. 
```
[19-11-04 11:25:22:015 CST] CalendarApp.Calendar.createEvent([Chapter 12 Quiz  [BUSADMIN 2330-03], Sun Nov 10 20:00:00 PST 2019, Sat Nov 09 22:00:00 PST 2019, {description=, location=}]) [0 seconds]
[19-11-04 11:25:22:022 CST] Execution failed: Event start time must be before event end time. (line 185, file "Code") [1.143 seconds total runtime]
```

**Comment by derekantrican** [comment]
No worries - glad you got it figured out!
