### ISSUE TITLE
Feature Request: Add toggle to ignore events older than the current time or day

### ISSUE THREAD

**Issue by kjhosein** [derekantrican/GAS-ICS-Sync#70]
Hello,

[If possible] add a toggle (true/false) setting that ignores events in the source calendar older than the current time. In my (personal) Google Calendar, I really don't care about older events from my source (work) calendar.

Perhaps this may even shorten the execution time? 
Thanks!

**Comment by jonas0b1011001** [comment]
Hi, this will actually be part of the next version.
Not sure when it will go live but feel free to test the upcoming version in [this](https://github.com/derekantrican/GAS-ICS-Sync/tree/jonas0b1011001-patch-1) branch (variable onlyFutureEvents is what you are looking for). Testing and feedback is always appreciated!

**Comment by kjhosein** [comment]
Great!
I've copied over the code and run it a few times. Seems to work well, and actually, the _sync_ function runs much faster now too. 

Feedback (mostly minor):
* Since the `sourceCalendars` var is a different type, it needs some expanded docs and examples.
* I'm not getting emails even with both `emailWhenAdded` and `emailWhenModified` set to _true_.
* Is the `startSync` function intentionally set up to disable the periodic Trigger after it's done running?

**Comment by derekantrican** [comment]
Great! Yes, the sync function has a lot of improvements in the next version. I don't know about the email issues, but yes - I think some documentation could be added for the new calendar format (eventually it will be a HTML UI). Yes, the function is set up so that it deletes and recreates it's own trigger on every iteration. It seems odd but it helps us get around Google's restriction that "every X minutes" triggers can only have specific X values (1, 5, 10, 15, etc - or something like that). If you want to run the program every....say 17 minutes... you'll be able to in the next version!

**Comment by jonas0b1011001** [comment]
Thank you for the feedback!

> * I'm not getting emails even with both `emailWhenAdded` and `emailWhenModified` set to _true_.

Could you add a **return** in front of Calendar.Events.update/insert in line 176/186 and try again?

**Comment by kjhosein** [comment]
>  Yes, the function is set up so that it deletes and recreates it's own trigger on every iteration. It seems odd but it helps us get around Google's restriction that "every X minutes" triggers can only have specific X values (1, 5, 10, 15, etc - or something like that). If you want to run the program every....say 17 minutes... you'll be able to in the next version!

Derek - thanks for the quick response. Ah, clever! If I'm reading this correctly, then I should see a new scheduled trigger in my list of triggers, right? It doesn't seem like this is happening and/or if it is and then setting the trigger to disabled, it's not running the `startSync` function because I don't see modified/new events in my source calendar being reflected in my target G calendar.

<img width="962" alt="Screen Shot 2019-10-27 at 12 23 11 PM" src="https://user-images.githubusercontent.com/3866191/67637859-00efdf00-f8b5-11e9-9c7e-4a322b4e86ca.png">

**Comment by kjhosein** [comment]
> > * I'm not getting emails even with both `emailWhenAdded` and `emailWhenModified` set to _true_.
> 
> Could you add a **return** in front of Calendar.Events.update/insert in line 176/186 and try again?

Thanks to you as well jonas for the quick reply. 
Ok, I tried that, but when I ran `startSync`, it threw this error:

  _ReferenceError: "icalEvent" is not defined. (line 179, file "Code")_

On the bright side, the sync itself seemed to work fine. 
I removed the `return`s and re-ran and it's back to running without errors, but of course without email updates coming in.

**Comment by jonas0b1011001** [comment]
I'll look into it later tonight, i don't have gmail set up in my account and therefore can't really test it myself so thanks for your input!

**Comment by jonas0b1011001** [comment]
> > Yes, the function is set up so that it deletes and recreates it's own trigger on every iteration. It seems odd but it helps us get around Google's restriction that "every X minutes" triggers can only have specific X values (1, 5, 10, 15, etc - or something like that). If you want to run the program every....say 17 minutes... you'll be able to in the next version!
> 
> Derek - thanks for the quick response. Ah, clever! If I'm reading this correctly, then I should see a new scheduled trigger in my list of triggers, right? It doesn't seem like this is happening and/or if it is and then setting the trigger to disabled, it's not running the `startSync` function because I don't see modified/new events in my source calendar being reflected in my target G calendar.
> 
> <img alt="Screen Shot 2019-10-27 at 12 23 11 PM" width="962" src="https://user-images.githubusercontent.com/3866191/67637859-00efdf00-f8b5-11e9-9c7e-4a322b4e86ca.png">

That's actually the correct behaviour.
The install function will:

1. Clean up all existing Triggers for our script
2. Create a new Trigger to run itself after the set amount of time (That's the first trigger in your list)
3. Run the startSync function in the background by creating a trigger that fires 1s after it is created (that's the disabled trigger you see)

You can test this by simply deleting your target calendar in between two scheduled runs.

**Comment by kjhosein** [comment]
Thanks jonas. Yep, that does indeed work - I'm seeing my target Google calendar being updated.

I've also downloaded the latest update for #70 and so far it's working! I'm getting email updates. 
Cheers!
