### ISSUE TITLE
CalAPI v3 does not support default reminders for all day events

### ISSUE THREAD

**Issue by jonas0b1011001** [derekantrican/GAS-ICS-Sync#75]
When creating an all day event using Google's Calendar API the default reminders for 'normal' events are applied instead of those defined for all day events.

This may lead to all day events having reminders even though the user has not defined any in the calendar settings at calender.google.com.

This issue was [reported](https://issuetracker.google.com/issues/65576067) to Google but has not been fixed yet.

**Comment by derekantrican** [comment]
### Closing as this is supported by the latest release: [v5.0](https://github.com/derekantrican/GAS-ICS-Sync/releases/tag/5.0)

*If you find that there are still bugs, please comment on this issue and let us know*

**Comment by sollochs** [comment]
I use default 9am on the day reminders for all day events on the google calendar i'm importing to, thought -1 setting would leave this as is, but instead sets to no reminders at all, the custom reminders only allow for the day before, so seems like this isn't an option? but wanted to check I wasn't being dumb with the settings, or if it was a bug, sorry if this is the wrong place to comment i'm new to all this

**Comment by derekantrican** [comment]
No, not an option. We'd love to include it, but Google's API doesn't support it (see the link in Jonas' comment)

**Comment by angelocioci1985** [comment]
I love this App script, but I have a problem. For me is important that if arrive a ical event I receive an email, is possible?

Angelo
