### ISSUE TITLE
Triggers Randomly Fail

### ISSUE THREAD

**Issue by jstride** [derekantrican/GAS-ICS-Sync#77]
- Occasionally Triggers fail, with the new trigger method to allow random times this means that it can stop repeating as the new trigger won't be set up. Reinstalling works with no issues.

![image](https://user-images.githubusercontent.com/1501958/68200788-85e8a000-fffb-11e9-8979-780f41de139c.png)

**Comment by jonas0b1011001** [comment]
For how long does it usually run before it fails?

Could you replace the install function with the following and see if it helps:
```
function install(){
  try{
    //Delete any already existing triggers so we don't create excessive triggers
    deleteAllTriggers();
    
    if (howFrequent < 1){
      throw "[ERROR] \"howFrequent\" must be greater than 0.";
    }
    else{
      ScriptApp.newTrigger("install").timeBased().after(howFrequent * 60 * 1000).create();//Schedule next Execution
      ScriptApp.newTrigger("startSync").timeBased().after(1000).create();//Start the sync routine
    }
  }catch(e){
    install();//Retry on error
  }
}
```

**Comment by jstride** [comment]
I've updated my install function so will let you know if I get anything. For reference, this is fairly intermittent and the script will run for a few days with no problem.

**Comment by jonas0b1011001** [comment]
> this is fairly intermittent and the script will run for a few days with no problem

So far had this error once myself only 5hrs after installing (no error after that for 1,5 days).

Error message was
`We're sorry, a server error occurred. Please wait a bit and try again`
on line 97
`ScriptApp.newTrigger("install").timeBased().after(howFrequent * 60 * 1000).create();`

**Comment by derekantrican** [comment]
Sounds like your `try-catch` suggestion earlier might do the trick. Or maybe even exponential backoff for setting the trigger?

This is such a critical issue that it's unfortunate that we really have to wait a couple days to see if it happens again

**Comment by jonas0b1011001** [comment]
I have to add that it never even went to the catch part since I added the try-catch. I'm externally logging when it reaches the catch block to see if it actually manages to 'overcome' the server error and how many retries it takes to finally create the triggers.

**Comment by jstride** [comment]
I don't think this will help for those that don't want non-standard polling times but updating the install method to check if the time is one that Google normally accepts and just setting up the old style trigger rather than the install and sync could be a partial solution.

**Comment by jonas0b1011001** [comment]
> I don't think this will help for those that don't want non-standard polling times but updating the install method to check if the time is one that Google normally accepts and just setting up the old style trigger rather than the install and sync could be a partial solution.

I currently assume that the issues were due to bad responses/timeouts from google's servers and that setting an 'old style' trigger would have also failed during these periods.

Have you had any additional problems with failed triggers since you posted the issue?

**Comment by jstride** [comment]
No failures for me since then, so yes. Let's assume it's transient.

**Comment by jonas0b1011001** [comment]
My logs show the already mentioned
`We're sorry, a server error occurred. Please wait a bit and try again`
error happened again two hours ago. The code in my first comment kept the script running though.

I think we should incorporate it just to be safe.

**Comment by derekantrican** [comment]
Sounds good

**Comment by mbloodk** [comment]
Yeah same issue.

**Comment by derekantrican** [comment]
@mbloodk Can you try @jonas0b1011001 's suggestion in the second comment here?

**Comment by mbloodk** [comment]
I will try and observe. Unfortunately its random so hard to simulate it.

**Comment by mbloodk** [comment]
After 10d its without any error.
