### ISSUE TITLE
Triggers disabled

### ISSUE THREAD

**Issue by bennychee** [derekantrican/GAS-ICS-Sync#79]
My triggers have been disabled after 1 try and did not wake up after the time set (15 mins). I found out that it has been disabled. I cannot find why it was disabled. Any reason?

![image](https://user-images.githubusercontent.com/714647/68283467-8c881d80-00b6-11ea-90b6-661c2a2333f2.png)

**Comment by jonas0b1011001** [comment]
Did the execution of 'install' fail just like reported in #77?

Please try the change suggested in this [comment](https://github.com/derekantrican/GAS-ICS-Sync/issues/77#issuecomment-549783848) and see if it gets more reliable.

**Comment by bennychee** [comment]
I was suspecting that it could be a quota issue.
https://developers.google.com/apps-script/guides/services/quotas

Each trigger took around 90s to complete which if i set my frequency to 15 mins, it might get > the 90 mins per trigger quota. I m resetting it to 30 mins and see if it is still good.

**Comment by jonas0b1011001** [comment]
Have you had any problems ever since?

**Comment by bennychee** [comment]
> Have you had any problems ever since?

No. The timing change helps to keep it within the free limits.
