### ISSUE TITLE
Helpers Line 470

### ISSUE THREAD

**Issue by roboanalyst** [derekantrican/GAS-ICS-Sync#80]
TypeError: Cannot read property "dateTime" from undefined. (line 470, file "Helpers") 

Getting this error routinely when trigger executes.  Please advise.

**Comment by derekantrican** [comment]
Please share your ics link that is causing the issue

**Comment by roboanalyst** [comment]
I think I was able to resolve the issue.  Appreciate the quick response.   Will seep you posted if I have any more issues.

**Comment by derekantrican** [comment]
Excellent. Let us know if it resurfaces

**Comment by jonas0b1011001** [comment]
And please share your solution if it is a bug in the script :)
