### ISSUE TITLE
Recurrence Not Showing

### ISSUE THREAD

**Issue by atulpatelx** [derekantrican/GAS-ICS-Sync#81]
I am still having issues with recurrence. Below are two separate examples of events that are not showing up. I'm only showing a portion of the recurrence below.  Any help would be great! 

Note: My source calendars are the public free/busy versions of the calendar, that's why the summary is showing as "Busy".

*Event 1*
```
BEGIN:VEVENT
DTSTART:20191204T234500Z
DTEND:20191205T033000Z
DTSTAMP:20191113T082535Z
UID:44v30hsam8kutp4ht0avq0u5od_R20191106T234500@google.com
ATTENDEE;X-NUM-GUESTS=0:mailto:redacted.com_6kf2beo8j26iorfqjhteerl0bs@group.
 calendar.google.com
RECURRENCE-ID:20191204T234500Z
SUMMARY:Busy
END:VEVENT
BEGIN:VEVENT
DTSTART:20191127T234500Z
DTEND:20191128T033000Z
DTSTAMP:20191113T082535Z
UID:44v30hsam8kutp4ht0avq0u5od_R20191106T234500@google.com
ATTENDEE;X-NUM-GUESTS=0:mailto:redacted.com_6kf2beo8j26iorfqjhteerl0bs@group.
 calendar.google.com
RECURRENCE-ID:20191127T234500Z
SUMMARY:Busy
END:VEVENT
BEGIN:VEVENT
DTSTART:20191120T234500Z
DTEND:20191121T033000Z
DTSTAMP:20191113T082535Z
UID:44v30hsam8kutp4ht0avq0u5od_R20191106T234500@google.com
ATTENDEE;X-NUM-GUESTS=0:mailto:redacted.com_6kf2beo8j26iorfqjhteerl0bs@group.
 calendar.google.com
RECURRENCE-ID:20191120T234500Z
SUMMARY:Busy
END:VEVENT
BEGIN:VEVENT
DTSTART:20191113T234500Z
DTEND:20191114T033000Z
DTSTAMP:20191113T082535Z
UID:44v30hsam8kutp4ht0avq0u5od_R20191106T234500@google.com
ATTENDEE;X-NUM-GUESTS=0:mailto:redacted.com_6kf2beo8j26iorfqjhteerl0bs@group.
 calendar.google.com
RECURRENCE-ID:20191113T234500Z
SUMMARY:Busy
END:VEVENT
```

*Event 2*
```
BEGIN:VEVENT
DTSTART:20191112T170000Z
DTEND:20191112T180000Z
DTSTAMP:20191113T083940Z
UID:4gibcp24398on06p4qthshorru@google.com
ATTENDEE;X-NUM-GUESTS=0:mailto:myemail@redacted.com
RECURRENCE-ID:20191112T170000Z
SUMMARY:Busy
END:VEVENT
BEGIN:VEVENT
DTSTART:20191210T170000Z
DTEND:20191210T180000Z
DTSTAMP:20191113T083940Z
UID:4gibcp24398on06p4qthshorru@google.com
ATTENDEE;X-NUM-GUESTS=0:mailto:myemail@redacted.com
RECURRENCE-ID:20191210T170000Z
SUMMARY:Busy
END:VEVENT
BEGIN:VEVENT
DTSTART:20191203T170000Z
DTEND:20191203T180000Z
DTSTAMP:20191113T083940Z
UID:4gibcp24398on06p4qthshorru@google.com
ATTENDEE;X-NUM-GUESTS=0:mailto:myemail@redacted.com
RECURRENCE-ID:20191203T170000Z
SUMMARY:Busy
END:VEVENT
BEGIN:VEVENT
DTSTART:20191126T170000Z
DTEND:20191126T180000Z
DTSTAMP:20191113T083940Z
UID:4gibcp24398on06p4qthshorru@google.com
ATTENDEE;X-NUM-GUESTS=0:mailto:myemail@redacted.com
RECURRENCE-ID:20191126T170000Z
SUMMARY:Busy
END:VEVENT
BEGIN:VEVENT
DTSTART:20191119T170000Z
DTEND:20191119T180000Z
DTSTAMP:20191113T083940Z
UID:4gibcp24398on06p4qthshorru@google.com
ATTENDEE;X-NUM-GUESTS=0:mailto:myemail@redacted.com
RECURRENCE-ID:20191119T170000Z
SUMMARY:Busy
END:VEVENT
```

**Comment by jonas0b1011001** [comment]
The events you shared are defining exceptions to recurrence instances (they override an instance of a recurring event). The corresponding recurring event is not included though, it should be an event with the same UID property and a _RRULE_ property instead of RECURRENCE-ID. Please post these too if possible.

**Comment by derekantrican** [comment]
Atul - I was talking this over with Jonas. Essentially, what we've concluded is that your ical file is improperly formatted. We may be able to provide a workaround, but we'd like to see if the file can be correct first. Your events have the `RECURRENCE-ID` property set on each of them that *refers back to itself* - each event is saying "I am a repeat occurrence of myself". 

Could you possibly tell us where this ical file was generated from? I see a lot of "@google.com" in the `UID` properties - was this exported from a Google calendar?

**Comment by atulpatelx** [comment]
Hi Derek and Jonas.

I'd love to send these to you privately. I'll send it via email. I just had a though, which I'll verify today. What I'm doing is using a "public" version of my calendar to create a global free/busy that then gets synced using GAS into a global free/busy.

Here are the steps I take.

**Set the public permissions to free/busy**
![image](https://user-images.githubusercontent.com/980409/68967051-3bea8180-0794-11ea-8258-97b979dfcf62.png)

**Use the public ICS in GAS**
![image](https://user-images.githubusercontent.com/980409/68966228-718e6b00-0792-11ea-9f11-5704cafc6b22.png)

So I believe what is happening is a free/busy view flattens the recurrence into independent events which creates the issue.

**Comment by atulpatelx** [comment]
As a follow on to the issue, as Derek and Jonas pointed out, there were `RECURRENCE-ID`s that are self-referencing. Given the current behavior of Google Calendar's free/busy ics, I have tweaked the code to try to temporarily rectify this by bypassing the if statement (below). I believe that others may find use for GAS to consolidate free/busy status, so it might be worth enhancing the check here for this case. But it looks to be working for me for now!

![image](https://user-images.githubusercontent.com/980409/68992401-9ed52a80-081f-11ea-9797-ff1d443e3828.png)

**Comment by yellowbarchetta** [comment]
This may or may not be the same issue.  I have a regular appointment with my boss, but it is often moved by her PA.  If I sync directly using Google Calendar's ICS linking (which doesn't update very often, so I'm trying to find an alternative), what I see in Google Calendar matches what I see in my Outlook calendar (and Outlook 365). 

However, using your script I only see the original entries, not ones which have been moved.

Extracting the ics I believe this is the entry that isn't being handled correctly.  Using your script it is showing as taking place on 2019-12-13 but it should be showing as 2019-12-11 1500-1600
`BEGIN:VEVENT
DESCRIPTION:\n\n
UID:040000008200E00074C5B7101A82E0080000000020F650AC9D81D001000000000000000
 0100000001EBCF7850A784448A87BABC08F881A28
RECURRENCE-ID;TZID=GMT Standard Time:20191213T140000
SUMMARY:REDACTED PERSONAL DATA
DTSTART;TZID=GMT Standard Time:20191211T150000
DTEND;TZID=GMT Standard Time:20191211T160000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191210T140148Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:189
LOCATION:Boss's Office
X-MICROSOFT-CDO-APPT-SEQUENCE:189
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT`

**Comment by jonas0b1011001** [comment]
This looks to be the same issue indeed. I still have not found a reason why these events should be valid and i was not able to recreate the issue on my end.

However, you should be able to work around this by changing line 478 in Helpers.gs:
`Logger.log("No Instance found, skipping!");`
to
`Calendar.Events.insert(recEvent, targetCalendarId);`

**Comment by yellowbarchetta** [comment]
Thanks, will substitute that.  The ics file is being generated by Outlook so even if it is non-standard ics compilation, if MS are doing it it's worth coding around!

**Comment by yellowbarchetta** [comment]
I've made that amendment, but there was no difference in behaviour in terms of syncing.  I deleted the calendar from Google Calendar, uninstalled the sync script, changed the calendar name in the script and then reinstalled.  The erroneous entry on Friday / Wednesday this week remained unchanged.

**Comment by jonas0b1011001** [comment]
Could you please share the original event's definition aswell?

**Comment by yellowbarchetta** [comment]
I think this is what you're after:-

> `BEGIN:VEVENT
DESCRIPTION:\n
RRULE:FREQ=WEEKLY;UNTIL=20200612T130000Z;INTERVAL=1;BYDAY=FR;WKST=MO
EXDATE;TZID=GMT Standard Time:20190927T140000,20191025T140000,20191206T1400
 00,20200313T140000
UID:040000008200E00074C5B7101A82E0080000000020F650AC9D81D001000000000000000
 0100000001EBCF7850A784448A87BABC08F881A28
SUMMARY:REDACTED
DTSTART;TZID=GMT Standard Time:20190920T140000
DTEND;TZID=GMT Standard Time:20190920T150000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191212T094908Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:189
LOCATION:Boss's Office
X-MICROSOFT-CDO-APPT-SEQUENCE:189
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT`

**Comment by jonas0b1011001** [comment]
Edit Helpers.gs line 153
`newEvent.recurringEventId = event.getFirstPropertyValue('recurrence-id').toString();`
to
`newEvent.recurringEventId = event.getFirstPropertyValue('recurrence-id').toString() + "Z";`

**Comment by yellowbarchetta** [comment]
I can confirm that my calendar is now putting irregular occurences of recurring events in the right spots now, and all recurring events are showing correctly.

**Comment by derekantrican** [comment]
@atulpatelx does @jonas0b1011001 's suggestion solve your problem?

**Comment by derekantrican** [comment]
@atulpatelx I'm going to close this since we haven't heard from you in a while. Please feel free to comment if you're still seeing an issue after trying @jonas0b1011001 's suggestions

**Comment by derekantrican** [comment]
@jonas0b1011001 I have another situation that seems be similar to this. Note that your suggestion [here](https://github.com/derekantrican/GAS-ICS-Sync/issues/81#issuecomment-564114672) solved it, ust wondering if you have any other thoughts of if there's a better way we can approach issues like this.

```
BEGIN:VEVENT
UID:040000008200E00074C5B7101A82E0080000000090F85469DED5D501000000000000000
 010000000A0B264822DEC95498D0B2E384518EA82
RECURRENCE-ID;TZID=Central Standard Time:20200218T130000
SUMMARY:Busy
DTSTART;TZID=Central Standard Time:20200218T140000
DTEND;TZID=Central Standard Time:20200218T150000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20200225T145723Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:4
X-MICROSOFT-CDO-APPT-SEQUENCE:4
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

Logs:
![image](https://user-images.githubusercontent.com/1558019/75261072-64284a00-579f-11ea-9cf7-e3103ad619b0.png)

**Comment by jonas0b1011001** [comment]
@derekantrican This is a single event taking place 2pm CST with no corresponding RRule?
