### ISSUE TITLE
Timeout on intial run

### ISSUE THREAD

**Issue by rgodsey** [derekantrican/GAS-ICS-Sync#82]
This script times out when I try to run it because it takes longer than 6 minutes.  I haven't dug too deeply in to see if this will be a recurring problem after the initial sync or not.  Any tips?

**Comment by jonas0b1011001** [comment]
Could you share the execution log from a run that timed out?
The script is usually able to sync several hundred events before reaching the execution time limit.

**Comment by rgodsey** [comment]
It was over 6000 records, do you still need the log?

**Comment by jonas0b1011001** [comment]
oh ok, never tried that many to be honest :D
Please try rerunning the script several times, it should skip the already added events and therefore add more and more entries on each run.

**Comment by rgodsey** [comment]
Ok, I'll try that.  I may just let it run on the trigger for a while and see if the timeouts decrease over time.  Although, it seems like it's trying to sync the same number of records each time.  I can only see the logs in the script window, not the executions window.  I'm not super familiar with Google Scripts so I may be missing something.

**Comment by jonas0b1011001** [comment]
It will indeed always check all 6000 events but skip the unchanged ones, this takes only a few milliseconds per event, so it should eventually be able to finish in time.

**Comment by rgodsey** [comment]
It's run approximately 30-40 times over the last couple of days and is still timing out.  After a while, it will stop triggering as well. I'm guessing that's because it times out repeatedly.  As I mentioned, I can't seem to pull the logs on each individual run.  Any thoughts?

**Comment by jonas0b1011001** [comment]
To have anything to work on could you please run startSync directly in the script editor and share the log?
For readability you can put it on pastebin or some similar website.

**Comment by rgodsey** [comment]
Gah... It's my bad.  Apparently as I was tweaking things to try to get this working the way I wanted to, I adjusted something that caused it to try to process all the 6000+ ical events instead of the first 100 the way the script was written.  Sorry for the runaround but thanks for the assistance.
