### ISSUE TITLE
Hourly trigger failures

### ISSUE THREAD

**Issue by yellowbarchetta** [derekantrican/GAS-ICS-Sync#83]
Google has been emailing me hourly with the following error since I started running the script yesterday:-
12/10/19 5:01 PM	startSync	TypeError: Cannot read property "dateTime" from undefined. (line 470, file "Helpers")	time-based	12/10/19 5:02 PM

The failure log under "My Executions" show as:-
Dec 12, 2019, 9:31:23 AM	Error	TypeError: Cannot read property "dateTime" from undefined.
    at [unknown function](Helpers:470)
    at processEventInstance(Helpers:469)
    at startSync(Code:191)

I should note that this is with the modified helpers.gs script with lines 476 / 479 edited to read as follows
 if (eventInstanceToPatch.length == 0){
    //Logger.log("No Instance found, skipping!");
    Calendar.Events.insert(recEvent, targetCalendarId);
  }

Which was suggested to fix the recurrence issue I was seeing.

Hope this is helpful!!

**Comment by derekantrican** [comment]
Is this with the same event you posted [here](https://github.com/derekantrican/GAS-ICS-Sync/issues/81#issuecomment-564932819)?

**Comment by yellowbarchetta** [comment]
I don't see any relation between the two issues? Both are on the same
calendar, but one is an issue with the handling of recurring appointments,
and the other is a trigger failure? I've reset helper.gs back to the
original script and still getting the trigger errors.

If they are related, sorry for duplication!

**Comment by derekantrican** [comment]
At this point I agree - I don't know if they're related or not. But it would be helpful to see the ics file or failing vevent definition

**Comment by yellowbarchetta** [comment]
Aha, yes I see. Difficult to share that without sharing my whole private
calendar though?

**Comment by yellowbarchetta** [comment]
Give me a steer as to what you would want to see.  I'm a bit of a novice to the google script interface etc and have tried playing around with breakpoints and debugging this morning with little joy - I've completely reset the code back to the original and the error continues.

This is probably just my incompetence, but when I set breakpoints on anything other than the initial variables and do "Run > Debug function > startSync" they all seem to get ignored and the function just completes (with the definition error flashing up at the end).  I'd normally expect to be able to set a breakpoint at that line, read off the various variables etc and try to provide some help, but I must be doing something wrong with the debugging tool.  

The code is properly adding / removing calendar entries despite the error being thrown, however.  So the error is not fatal to the process overall I think.

**Comment by jonas0b1011001** [comment]
Looks like a recurrence-exception is trying to override a non-recurring event.

To hunt this down please edit Helpers.gs lines 469++ to
```
var eventInstanceToPatch = calendarEvents.filter(function(item){
    try{
      var origStart = item.originalStartTime.dateTime || item.originalStartTime.date;
      var instanceStart = new ICAL.Time.fromString(origStart);
      return (instanceStart.compare(recIDStart) == 0);
    }catch(e){
      Logger.log("error: " + item.extendedProperties.private['id']);
      return 0;
    }
});
```
Run the script again and check the log for the error message and the id. You can then search the id and only share the anonymized definition of the relevant events.

**Comment by yellowbarchetta** [comment]
OK, hope this extract helps.  Nothing overly personal in the data.   Error traps at the top, events at the bottom, 

'[19-12-13 14:40:47:391 GMT] Processing 50 Recurrence Instances!
[19-12-13 14:40:47:391 GMT] 	2019-09-24
[19-12-13 14:40:47:638 GMT] error: 040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000010000000CB10436115E2534B9C042E04AA829CB5
[19-12-13 14:40:47:640 GMT] No Instance found, skipping!
[19-12-13 14:40:47:640 GMT] 	2019-09-20
[19-12-13 14:40:48:062 GMT] No Instance found, skipping!
[19-12-13 14:40:48:063 GMT] 	2019-10-01
[19-12-13 14:40:48:279 GMT] error: 040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000010000000CB10436115E2534B9C042E04AA829CB5
[19-12-13 14:40:48:280 GMT] No Instance found, skipping!
[19-12-13 14:40:48:281 GMT] 	2019-10-04
[19-12-13 14:40:48:635 GMT] No Instance found, skipping!
[19-12-13 14:40:48:636 GMT] 	2019-10-08
[19-12-13 14:40:48:843 GMT] error: 040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000010000000CB10436115E2534B9C042E04AA829CB5
[19-12-13 14:40:48:844 GMT] No Instance found, skipping!
[19-12-13 14:40:48:844 GMT] 	2019-10-11
[19-12-13 14:40:49:206 GMT] No Instance found, skipping!
[19-12-13 14:40:49:207 GMT] 	2019-10-15
[19-12-13 14:40:49:477 GMT] error: 040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000010000000CB10436115E2534B9C042E04AA829CB5
[19-12-13 14:40:49:478 GMT] No Instance found, skipping!
[19-12-13 14:40:49:479 GMT] 	2019-10-18
[19-12-13 14:40:49:768 GMT] No Instance found, skipping!
[19-12-13 14:40:49:769 GMT] 	2019-10-22
[19-12-13 14:40:49:986 GMT] error: 040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000010000000CB10436115E2534B9C042E04AA829CB5
[19-12-13 14:40:49:987 GMT] No Instance found, skipping!'





'BEGIN:VEVENT
DESCRIPTION:\n
RRULE:FREQ=WEEKLY;UNTIL=20191022T070000Z;INTERVAL=1;BYDAY=TU;WKST=MO
UID:040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000
 010000000CB10436115E2534B9C042E04AA829CB5
SUMMARY:Retention Group
DTSTART;TZID=GMT Standard Time:20190910T080000
DTEND;TZID=GMT Standard Time:20190910T090000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191210T140148Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Boardroom Two
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
BEGIN:VEVENT
DESCRIPTION:\n
UID:040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000
 010000000CB10436115E2534B9C042E04AA829CB5
RECURRENCE-ID;TZID=GMT Standard Time:20190910T080000
SUMMARY:Retention Group
DTSTART;TZID=GMT Standard Time:20190910T080000
DTEND;TZID=GMT Standard Time:20190910T090000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191210T140148Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Boardroom Two
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

BEGIN:VEVENT
DESCRIPTION:\n
RRULE:FREQ=WEEKLY;UNTIL=20191022T070000Z;INTERVAL=1;BYDAY=TU;WKST=MO
UID:040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000
 010000000CB10436115E2534B9C042E04AA829CB5
SUMMARY:Retention Group
DTSTART;TZID=GMT Standard Time:20190910T080000
DTEND;TZID=GMT Standard Time:20190910T090000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191210T140148Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Boardroom Two
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

BEGIN:VEVENT
DESCRIPTION:\n
UID:040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000
 010000000CB10436115E2534B9C042E04AA829CB5
RECURRENCE-ID;TZID=GMT Standard Time:20190917T080000
SUMMARY:Retention Group
DTSTART;TZID=GMT Standard Time:20190917T080000
DTEND;TZID=GMT Standard Time:20190917T090000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191210T140148Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Boardroom Two
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

BEGIN:VEVENT
DESCRIPTION:\n
UID:040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000
 010000000CB10436115E2534B9C042E04AA829CB5
RECURRENCE-ID;TZID=GMT Standard Time:20191001T080000
SUMMARY:Retention Group
DTSTART;TZID=GMT Standard Time:20191001T080000
DTEND;TZID=GMT Standard Time:20191001T090000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191210T140148Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Boardroom Two
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

BEGIN:VEVENT
DESCRIPTION:\n
UID:040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000
 010000000CB10436115E2534B9C042E04AA829CB5
RECURRENCE-ID;TZID=GMT Standard Time:20191008T080000
SUMMARY:Retention Group
DTSTART;TZID=GMT Standard Time:20191008T080000
DTEND;TZID=GMT Standard Time:20191008T090000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191210T140148Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Boardroom Two
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

BEGIN:VEVENT
DESCRIPTION:\n
UID:040000008200E00074C5B7101A82E00800000000D0CA6E41A35DD501000000000000000
 010000000CB10436115E2534B9C042E04AA829CB5
RECURRENCE-ID;TZID=GMT Standard Time:20191015T080000
SUMMARY:Retention Group
DTSTART;TZID=GMT Standard Time:20191015T080000
DTEND;TZID=GMT Standard Time:20191015T090000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191210T140148Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Boardroom Two
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT'

**Comment by jonas0b1011001** [comment]
Did these errors appear only after you did the change in my comment [here](https://github.com/derekantrican/GAS-ICS-Sync/issues/81#issuecomment-564114672)?

If so please try deleting the target calendar or freshly sync to a different calendar with [this](https://github.com/derekantrican/GAS-ICS-Sync/issues/81#issuecomment-565448867) change.

**Comment by yellowbarchetta** [comment]
I've done as suggested and the code seems to be running error free now, so I think your assumption above is correct.
