### ISSUE TITLE
No emails sent when new or updated appointments added

### ISSUE THREAD

**Issue by yellowbarchetta** [derekantrican/GAS-ICS-Sync#84]
Setup code has been amended to:
`var emailWhenAdded = true;            // Will email you when an event is added to your calendar
var emailWhenModified = true;         // Will email you when an existing event is updated in your calendar
var email = 'myemail.name@gmail.com';                        // OPTIONAL: If "emailWhenAdded" is set to true, you will need to provide your email`

But no emails are sent, despite new entries appearing in the calendar.  No errors are thrown that I can see, and the logger doesn't report any issues.

Adding a line of code to send an email when "install" or "startSync" is first run using the email variable above does work, so I believe this would rule out any settings or restricitons on my gmail account causing the issue.

**Comment by jonas0b1011001** [comment]
Thanks for the report.

1. in Code.gs add a new line
`var targetCalendarName;`
at line 113 below
`var startUpdateTime;`

2. Edit line 126
`var targetCalendarName = calendar[0];`
to
`targetCalendarName = calendar[0];`

Will be fixed in the next release.

**Comment by yellowbarchetta** [comment]
Perfect, working fine now.
