### ISSUE TITLE
Exceeded maximum execution time (with large calendar)

### ISSUE THREAD

**Issue by scarlottie** [derekantrican/GAS-ICS-Sync#85]
This may or may not be a bug but I LOVE this script and I offer many thanks to you for writing it!

Here is the problem - I have successfully run this script to pull my Mac calendar into my wife's Google calendar.  However, it does not pull in all my events.  It almost feels random.  The script always times out with the message "Exceeded maximum execution time".  

My guess is that there are so many events on my calendar (it goes back many years) that it causes a time out.  I switched the variable to only pull in new events but it doesn't fix the problem. The logs suggest that the script is still looking at the old stuff, just skipping the import. Assuming I'm right, perhaps there's a way to only pull things from today forward and ignore the old stuff?

MANY THANKS!!!

**Comment by jonas0b1011001** [comment]
How much events are you trying to import in total?

If you provide a log i will take a look at it.

**Comment by scarlottie** [comment]
Well to be honest, I don’t know how many.  It’s just my personal calendar but it goes back years.  I have no reason to share the old events but it looks like it does that automatically.   I’ll get a log when I’m back on the computer.  


-----------------------------------

**Comment by derekantrican** [comment]
Usually when we see a case like this it's because the website generating the ics file is changing event IDs (UUID) every time the ics file is accessed. So every time the script runs it has to delete all the existing events and re-add everything from scratch.

That may be what is happening here - we will have to take a look through the log or with the ics URL

**Comment by scarlottie** [comment]
Gotcha. Well it's a Mac Calendar. As far as I know it's a totally standard setup which the mac gives you. but perhaps there's a goofy setting on my end?  Here is the URL:

webcal://p15-caldav.icloud.com/published/2/MjAwMDAyNjIwNjIyMDAwMByt46STHd04-TUcyhbHbSavWJ8E6Z4YJXE02IislrdH

**Comment by jonas0b1011001** [comment]
Here's a faster option to filter past events.
Add the following to Helpers.gs at line 122:
```
  if (onlyFutureEvents){
    result = result.filter(function(event){
      var eventEnde;
      eventEnde = new ICAL.Time.fromString(event.getFirstPropertyValue('dtend').toString());
      return (eventEnde.compare(startUpdateTime) >= 0);
    });
  }
```

And run the script with _onlyFutureEvents = true_.

This will **not** be compatible with recurring events!

**Comment by scarlottie** [comment]
INCREDIBLE!!! IT WORKS!!!  THANK YOU!!! 

I owe you many beers my friend!!!
