### ISSUE TITLE
Helpers Line 128

### ISSUE THREAD

**Issue by abelsantiagocortes** [derekantrican/GAS-ICS-Sync#86]
Excellent job @derekantrican , but I am getting one error with an specific ics calendar, it works when I add it as a URL directly from Google Calendar but not from the script.

TypeError: Cannot call method "toString" of null. (line 128, file "Helpers")

My ICS Link:
https://notionics.evertheylen.eu/ics?url=aHR0cHM6Ly93d3cubm90aW9uLnNvL2ZhZjY1MTI4MWNhZjQ4MWFiMzgwMjQzMDAzNjFjN2MwP3Y9MDIwMzViYTBiNGMwNDRjYjlmOTI0OWJiMWYzY2U0OTI%3D&format=e05BTUV9

Not sure what is happening, the calendar is created but events are not shown.
Thanks in advance.

**Comment by jonas0b1011001** [comment]
The events you are trying to add are missing the 'uid' parameter which is a required component of an event definition according to the ICAL standard. Therefore the file you are trying to sync is not a valid ics file.

We can probably provide a workaround for you but it might be a better option to reach out to the developers of notion and try to change their export functionality to create properly formatted outputs.

**Comment by derekantrican** [comment]
Yeah, UUID is one of the base properties of the ics events. When it is missing, it is almost as bad as if there were no date for the ics events. Please contact evertheylen.eu (or whoever generates this ics file) and tell them

**Comment by abelsantiagocortes** [comment]
Thanks for your response, I will contact them.
