### ISSUE TITLE
Email of new items converted into "digest"

### ISSUE THREAD

**Issue by yellowbarchetta** [derekantrican/GAS-ICS-Sync#87]
The email alert for new entries is a good idea, but sometimes creates large numbers of entries if multiple new diary entries added.

How about condensing the appointments into a single list and adding them to the text of one single email e.g.

To: [email address]
Subject: [NN] new appointment(s) added to [CalendarName] 
Contents:-
The following appointments have been added by GAS-ICS Sync:-
[Date] [Title] [Location] [Time]
[Date] [Title] [Location] [Time]
[Date] [Title] [Location] [Time]
[Date] [Title] [Location] [Time]
[Date] [Title] [Location] [Time]
[Date] [Title] [Location] [Time]
etc

**Comment by derekantrican** [comment]
Good suggestion!
