### ISSUE TITLE
Support for feeds without UIDs

### ISSUE THREAD

**Issue by jonaswouters** [derekantrican/GAS-ICS-Sync#89]
- Description of the problem
I've got a feed that does not contain UIDs. You'll get at least 1 error when it is trying to parse this feed
```
TypeError: Cannot call method "toString" of null.
    at [unknown function](Helpers:128)
    at parseResponses(Helpers:123)
    at startSync(Code:159)
```

- An input ics string that can reproduce the problem

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Ensemble Independent//Toggl.com pg_iCal//EN
CALSCALE:Gregorian
X-WR-TIMEZONE:Europe/Brussels
X-WR-CALNAME:Toggl
X-WR-CALDESC:Toggl (Jonas Wouters)
BEGIN:VEVENT
SUMMARY:Internal
DESCRIPTION:A description
DTSTART:20191217T145337Z
DTEND:20191217T160037Z
END:VEVENT
BEGIN:VEVENT
SUMMARY:Projectname
DESCRIPTION:Description of the task
DTSTART:20191217T122228Z
DTEND:20191217T145337Z
END:VEVENT
BEGIN:VEVENT
SUMMARY:Projectname
DESCRIPTION:Another description
DTSTART:20191217T121231Z
DTEND:20191217T122228Z
END:VEVENT
BEGIN:VEVENT
SUMMARY:Projectname 2
DESCRIPTION:Code review
DTSTART:20191217T062632Z
DTEND:20191217T145324Z
END:VEVENT
BEGIN:VEVENT
SUMMARY:Internal
DESCRIPTION:Looking into calendar sync
DTSTART:20191217T045306Z
DTEND:20191217T062630Z
END:VEVENT
BEGIN:VEVENT
SUMMARY:Projectname 2
DESCRIPTION:Code review
DTSTART:20191216T190051Z
DTEND:20191216T202329Z
END:VEVENT
BEGIN:VEVENT
SUMMARY:Projectname 3
DESCRIPTION:Hello world
DTSTART:20191216T081604Z
DTEND:20191216T160212Z
END:VEVENT
END:VCALENDAR
```

**Comment by derekantrican** [comment]
This is definitely tricky because the UID is so integral to the ICS definition and how the script handles modified/deleted events.

It seems like Google Calendar at least successfully adds the events, but I haven't checked what it does if an event is modified or deleted (I would imagine that it would simply add a new event and the old event would stay)

**Comment by derekantrican** [comment]
If you can, the first step here is definitely to contact whatever website/application is generating this ICS feed and see if they can correct this. We've seen many times where websites do not follow the standard (for instance: recurrence issues) and sometimes we've been able to "code around that". But in this case, UID is such an integral part of the ICS definition that it's almost like your events don't have any start times.

**Comment by jonaswouters** [comment]
It's toggl.com and their feed has been like this for years. 
I might as well just fix [this project](https://github.com/KATT/toggl-iCal) and use the feed generated by that.

Thanks for the feedback!

**Comment by jonas0b1011001** [comment]
You can sync by changing Helpers.gs Lines 123-133 to
```
result.forEach(function(event){
    if(event.hasProperty('recurrence-id')){
      icsEventsIds.push(event.getFirstPropertyValue('uid').toString() + "_" + event.getFirstPropertyValue('recurrence-id').toString());
    }
    else if (event.hasProperty('uid')){
      icsEventsIds.push(event.getFirstPropertyValue('uid').toString());
    }
    else{
      event.updatePropertyWithValue('uid', Utilities.computeDigest(Utilities.DigestAlgorithm.MD5, event).toString());
      icsEventsIds.push(event.getFirstPropertyValue('uid').toString());
    }
  });
```
