### ISSUE TITLE
Recurring events are not been added

### ISSUE THREAD

**Issue by kurokirasama** [derekantrican/GAS-ICS-Sync#90]
Hello, only the first event of a recurrent series is added....

**Comment by derekantrican** [comment]
Could you please provide some additional information to help us troubleshoot? For example: ICS url, ICS text, or the problematic event?

**Comment by kurokirasama** [comment]
Hello, i cannot give you the url since is a company outlook calendar, but how do i get the ics text to see if i can share it?
The event is just a 1 hour meeting that repeats every week. It was added to gcal only the first time. I run the script manually and in the section where you log the results: `//------------------------ Check results -------------------------` the event is not displayed. All other non recurrent event are added just fine.

**Comment by derekantrican** [comment]
If you put the ICS url in your browser you should be able to download it as a .ics file to your computer. That file is just a text file and can be opened in any text editor (eg Notepad). Find the problematic event. You're looking for something like this:

```
BEGIN:VEVENT
.
.
.
END:VEVENT
```

And paste it here

**Comment by kurokirasama** [comment]
Ok, thanks. Here it goes:

```
BEGIN:VEVENT
DESCRIPTION:\n.............................................................
 ..........................................................................
 ..\nHi\n\n........................................................
 ..........................................................................
 .......\n
RRULE:FREQ=WEEKLY;UNTIL=20200224T140000Z;INTERVAL=1;BYDAY=MO;WKST=SU
UID:040000008200E00074C5B7101A82E0080000000034002094E1A6D501000000000000000
 0100000007928D79D2796724988035721A8B3C99B
SUMMARY:Programación Semana
DTSTART;TZID=Pacific SA Standard Time 1:20191202T110000
DTEND;TZID=Pacific SA Standard Time 1:20191202T120000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20191220T120700Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Sala Roja
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

**Comment by jonas0b1011001** [comment]
The event you shared syncs fine for me (with correct recurrence). 

Are you using the latest version? If so please share the execution log, maybe there's something in there.

**Comment by kurokirasama** [comment]
cool, i haven't noticed a new version. That fixed it. Thanks.
