### ISSUE TITLE
Add Title To Events/Calendar

### ISSUE THREAD

**Issue by hcwyatt145** [derekantrican/GAS-ICS-Sync#91]
I am using this script to combine 20 different ics calendars from a service called WhenIWork. The event titles as they come are all very vauge - "Shift as ______, etc". I need to attach a name to each event/calendar. I was successful in adding a 3rd item to each array in sourceCalendars[] like: 

`["calendarlinkstring.ics", "Target Calendar", "Name of Employee"]`

I also had to adjust some here and there, but it all works fine from what I can tell. The only issue I am running into now is with **removeEventsFromCalendar** - it now removes all events except for the first array's events in sourceCalendars[] when set to 'true'.

Any help would be greatly appreciated!

**Comment by jonas0b1011001** [comment]
Assuming your sourceCalendars array looks like this
`["calendarlinkstring.ics", "Target Calendar", "Name of Employee"]`

Replace in Helpers.gs:
1. condenseCalendarMap function (line 22-26):
```
    if (index > -1)
      result[index][1].push([mapping[0], mapping[2]]);
    else
      result.push([ mapping[1], [[ mapping[0], mapping[2] ]] ]);
```

2. fetchSourceCalendars function (line 51-67)
```
for each (var srcUrl in sourceCalendarURLs){
    var url = srcUrl[0].replace("webcal://", "https://");      
    
    try{
      var urlResponse = UrlFetchApp.fetch(url).getContentText();
      //------------------------ Error checking ------------------------
      if(!urlResponse.includes("BEGIN:VCALENDAR")){
        Logger.log("[ERROR] Incorrect ics/ical URL: " + url);
      }
      else{
        result.push([urlResponse, srcUrl[1]]);
      }
    }
    catch(e){
      Logger.log(e);
    }
  }
```

3. parseResponses function line 106:
```
var jcalData = ICAL.parse(resp[0]);
```
and line 117-118
```
    if (calName != null)
      allEvents.forEach(function(event){event.addPropertyWithValue("parentCal", calName); });
    if (resp[1] != null)
      allEvents.forEach(function(event){event.updatePropertyWithValue("summary", resp[1]); });
```

Let me know if it works and if this is what you are actually looking for!

**Comment by derekantrican** [comment]
@hcwyatt145 Did @jonas0b1011001 's suggestion do what you are looking for?
