### ISSUE TITLE
Support Calendar name in "X-WR-CALNAME" field

### ISSUE THREAD

**Issue by hippysurfer** [derekantrican/GAS-ICS-Sync#94]
Hi

The calendars that I am syncing put their names in the "X-WR-CALNAME" field. They have no "NAME" field.

To support "X-WR-CALNAME", I added the following at line 119 of Helpers.gs in function "parseResponses":

    var xwrcalName = component.getFirstPropertyValue("x-wr-calname");
    
    if (calName == null) {
      calName = xwrcalName;
    }

**Comment by derekantrican** [comment]
Ok, I think we'll just change `Helpers.gs` to something like this:

````js
    var calName = component.getFirstPropertyValue("name");

    if (calName == null)
      calName = component.getFirstPropertyValue("x-wr-calname");

    if (calName != null)
      allEvents.forEach(function(event){event.addPropertyWithValue("parentCal", calName); });
````

**Comment by derekantrican** [comment]
This is now supported in the latest release. Please grab the new code
