### ISSUE TITLE
Support new V8 runtime

### ISSUE THREAD

**Issue by jeffhaskin** [derekantrican/GAS-ICS-Sync#98]
SyntaxError: Unexpected identifier (line 129, file "Code.gs") appears and won't let me install.

Line 129 says:

 for each (var calendar in sourceCalendars){

No idea what that's about.

**Comment by derekantrican** [comment]
@jeffhaskin Please share your script with me (derekantrican@gmail.com)

**Comment by mbloodk** [comment]
Same issue, script stop working and cant be installed. 

SyntaxError: Unexpected identifier (Line 126, file„Code“)

**Comment by jonas0b1011001** [comment]
> Same issue, script stop working and cant be installed.
> 
> SyntaxError: Unexpected identifier (Line 126, file„Code“)

What version are you using?

**Comment by mbloodk** [comment]
where i can find it ?

**Comment by jonas0b1011001** [comment]
You can find a _thisVersion_ variable at the bottom of helpers.gs

**Comment by mbloodk** [comment]
5.0

**Comment by jonas0b1011001** [comment]
Please copy the latest version from [here](https://github.com/derekantrican/GAS-ICS-Sync/releases/tag/5.1) and try again.

**Comment by mbloodk** [comment]
it works. 
i got info message: 
Enable new Apps Script runtime powered by Chrome V8 for this project.

if i enable it it dont work

**Comment by jonas0b1011001** [comment]
> i got info message:
> Enable new Apps Script runtime powered by Chrome V8 for this project.

The new runtime requires different code syntax and therefore is **not** compatible with the current version of the script.

**Comment by derekantrican** [comment]
Here's some info: https://developers.google.com/apps-script/guides/v8-runtime (glad to hear this is finally getting updated!)

@jonas0b1011001 we should probably work on changing our `for each (` uses into regular `for (` syntax so that people don't hit this issue and we can fully support the runtime

**Comment by mbloodk** [comment]
Question regarding updates: as you fix my problem by new update and new version was live before. Is it possible implement some autoupdate? I know we have copy of script so that was not possible, but is there any way how to do it?

**Comment by derekantrican** [comment]
Are you talking about an auto update for the script or for the runtime?

**Comment by mbloodk** [comment]
actually i dont know. this script and google cooding is way to my paycheck :) 
but from my perspective. You and Jonas sometimes relase new version with some upgrades. And me as user i must check git (or probably set some notification if is it possible) to be inform about it. But better way will be autoupgrade of script. Yes every script is different so it will not be possible or easy but it will be more user friendly. 

It's only gantle wish for me its not problem to make another clone and set it.

**Comment by derekantrican** [comment]
I think the script should send an email when a new version is released - I can check into that and make sure it's still working. As to auto-updating I unfortunately don't think it's possible with Google Apps Script but I can look more into it and see

**Comment by jonas0b1011001** [comment]
> And me as user i must check git (or probably set some notification if is it possible) to be inform about it.

If you define an email address at the top of code.gs you will be notified about new releases.


> @jonas0b1011001 we should probably work on changing our `for each (` uses into regular `for (` syntax so that people don't hit this issue and we can fully support the runtime

Definitely!
I'm not sure if v8 is available to all users because I do not have an option to change the runtime through the editor's UI yet.

**Comment by jeffhaskin** [comment]
So how do I turn off v8 runtime to make the script work if I already
enabled it?

**Comment by jonas0b1011001** [comment]
> So how do I turn off v8 runtime to make the script work if I already enabled it?

> If your script is using V8 and you need to switch it to use the original Rhino runtime, do the following:
>
>Open the script in the Apps Script editor.
>Select Run > Disable new Apps Script runtime powered by V8.

**Comment by jeffhaskin** [comment]
Thank you!!

**Comment by derekantrican** [comment]
Here's an official migration doc from Rhino to V8: https://developers.google.com/apps-script/guides/v8-runtime/migration

**Comment by jeffhaskin** [comment]
I reversed V8, but now the script just adds a new calendar to my calendars
called "0" with no events. I even tried using the example us holidays
snippet included in the comments to troubleshoot, and it just adds a "0"
calendar with no events.

**Comment by jeffhaskin** [comment]
Never mind, I got it to work by reading the comments more carefully here:
https://support.google.com/calendar/thread/9037280?hl=en&msgid=22733200

**Comment by jeffhaskin** [comment]
Much thanks all!

**Comment by derekantrican** [comment]
*Removed comments that were not relevant to the new runtime and the migration discussion*
